#!/usr/bin/env python3
"""Turn the cached AllTrails harvest into a claims migration.

The harvest itself cannot run from a script. AllTrails' robots.txt disallows
ClaudeBot, Claude-User and Claude-SearchBot from all of /, and /api/ from
everybody; the MCP server at https://www.alltrails.com/mcp is the interface
they built for agent access, and it is driven a call at a time by a model, not
by a loop. So a model appends rows to data/alltrails/pilot.jsonl and this turns
that file into SQL.

Everything is recorded, including the rows we are unsure about. A verdict of
reject or no-match still produces a claim group where there is a trail to point
at, marked identity_certain = false with the reason in the note -- because a
source saying something about the wrong waterfall is still a thing that source
said, and deleting it invites the next importer to make the same match again.

    python3 script/alltrails/fetch.py      # responses to data/alltrails/raw/
    python3 script/alltrails/match.py      # raw -> data/alltrails/verdicts.jsonl
    python3 script/import_alltrails/build.py > db/migrations/059_alltrails_claims.sql
"""

import json
import pathlib
import sys

CACHE = pathlib.Path("data/alltrails/verdicts.jsonl")
SOURCE = "alltrails"


def sql(text):
    """Quote a string for SQL, or NULL."""
    if text is None:
        return "NULL"
    return "'" + str(text).replace("'", "''") + "'"


def certain(row):
    """Only a clean accept is certain.

    An accept-note is still an accept: the note explains a distance that looks
    wrong and is not, usually trailhead-to-falls on a long route. A flag or a
    reject is recorded and left uncertain.
    """
    return row.get("verdict", "") == "accept"


def main():
    if not CACHE.exists():
        sys.exit(f"no cache at {CACHE}")
    rows = [json.loads(line) for line in CACHE.read_text().splitlines() if line.strip()]
    rows = [r for r in rows if r.get("trail_id")]

    out = []
    out.append("-- AllTrails claims, generated by script/import_alltrails/build.py")
    out.append("-- from data/alltrails/pilot.jsonl. Do not hand-edit: re-generate.")
    out.append("--")
    out.append("-- One claim group per (feature, trail). The counts describe a walk and a")
    out.append("-- walk is not a waterfall, so they are never summed onto the feature --")
    out.append("-- see migration 057 and docs/MATCHING.md.")
    out.append("--")
    out.append("-- Groups that failed the name test are recorded with identity_certain =")
    out.append("-- false and the reason in the note. They are kept rather than dropped so")
    out.append("-- the next importer can see the match was considered and refused.")
    out.append("")

    for r in rows:
        ref = f"alltrails:{r['trail_id']}:{r['feature_id']}"
        url = f"https://www.alltrails.com/trail/{r['slug']}" if r.get("slug") else None
        note_bits = [r.get("verdict", ""), r.get("why", "")]
        for key in ("correction", "counts_note", "description_note", "slug_note"):
            if r.get(key):
                note_bits.append(r[key])
        # Both distances are recorded and they answer different questions: the
        # pin is the trail's own point and is what the match was decided on;
        # the trailhead is where you park, which can be miles from the water.
        if r.get("pin_km") is not None:
            note_bits.append(f"Trail pin {r['pin_km']*1000:.0f} m from our coordinate.")
        if r.get("trailhead_m") is not None:
            note_bits.append(f"Trailhead {r['trailhead_m']} m.")
        note = " ".join(b for b in note_bits if b)

        out.append(
            "INSERT INTO claim_groups (ref, feature_id, source, url, observed_on, "
            "identity_certain, note)\nVALUES ("
            f"{sql(ref)}, {r['feature_id']}, {sql(SOURCE)}, {sql(url)}, DATE '2026-09-14', "
            f"{str(certain(r)).lower()}, {sql(note)})\nON CONFLICT (ref) DO NOTHING;"
        )

        # A claim carries feature_id, so a claim says something about OUR
        # waterfall -- not about the trail in the abstract. Writing this
        # trail's photo count against a feature whose match we REFUSED would
        # assert a number we have just decided is about somewhere else, and
        # a feature with ten nearby candidates would end up asserting ten
        # different photo counts about itself. So a refused group records
        # only what the source called the place, plus the reason in the note.
        claims = []
        if r.get("trail"):
            claims.append(("name", sql(r["trail"])))
        if not certain(r):
            for field, value in claims:
                jsonb = f"to_jsonb({value}::text)"
                out.append(
                    "INSERT INTO claims (group_id, feature_id, field, value, accepted)\n"
                    f"SELECT cg.id, cg.feature_id, {sql(field)}, {jsonb}, false\n"
                    f"  FROM claim_groups cg WHERE cg.ref = {sql(ref)}\n"
                    "ON CONFLICT DO NOTHING;")
            out.append("")
            continue
        if r.get("photos") is not None:
            claims.append(("photos_count", r["photos"]))
        if r.get("hikes") is not None:
            claims.append(("completed_hikes_count", r["hikes"]))
        if r.get("reviews") is not None:
            claims.append(("reviews_count", r["reviews"]))
        if r.get("gain_ft") is not None:
            claims.append(("elevation_gain_ft", r["gain_ft"]))
        # hike_distance is stored as the string the source presents, like every
        # other source's prose distance -- features.rt_hike_distance is a
        # derived round-trip number and these are route lengths.
        if r.get("length_mi") is not None:
            claims.append(("hike_distance", sql(f"{r['length_mi']} mi")))

        for field, value in claims:
            literal = value if isinstance(value, (int, float)) else value
            jsonb = (
                f"to_jsonb({literal}::numeric)"
                if isinstance(value, (int, float))
                else f"to_jsonb({literal}::text)"
            )
            # accepted is named rather than left to the column default, even
            # though the value is the same. It is a judgement -- "this is the
            # reading the published columns reflect" -- and every one of these
            # is false on purpose: AllTrails describes a ROUTE, and a route's
            # gain and distance are not the waterfall's. Leaving it implicit
            # would make a deliberate false indistinguishable from a forgotten
            # one, and the alias matcher in migration 058 reads accepted across
            # every source. An importer copying this pattern without the column
            # would hand that matcher a name it never endorsed.
            out.append(
                "INSERT INTO claims (group_id, feature_id, field, value, accepted)\n"
                f"SELECT cg.id, cg.feature_id, {sql(field)}, {jsonb}, false\n"
                f"  FROM claim_groups cg WHERE cg.ref = {sql(ref)}\n"
                "ON CONFLICT DO NOTHING;"
            )
        out.append("")

    # The view in 057 does not filter on identity_certain, which is safe only
    # while every group is a match. It is not: most groups here are candidates
    # we refused, and an unfiltered view pairs a feature with every trail near
    # it. Narrow it where the data that exposes the gap arrives.
    out.append("""CREATE OR REPLACE VIEW trail_engagement AS
SELECT cg.id AS group_id, cg.feature_id, f.name AS feature_name, cg.source, cg.url,
       cg.identity_certain,
       ((p.value #>> '{}')::integer) AS photos,
       ((h.value #>> '{}')::integer) AS hikes,
       ((r.value #>> '{}')::integer) AS reviews,
       round(((p.value #>> '{}')::numeric) / ((h.value #>> '{}')::numeric), 4) AS photos_per_hike
FROM claim_groups cg
JOIN features f ON f.id = cg.feature_id
JOIN claims p ON p.group_id = cg.id AND p.field = 'photos_count'
JOIN claims h ON h.group_id = cg.id AND h.field = 'completed_hikes_count'
LEFT JOIN claims r ON r.group_id = cg.id AND r.field = 'reviews_count'
WHERE ((h.value #>> '{}')::numeric) > 0
  AND cg.identity_certain;""")
    out.append("")
    kept = sum(1 for r in rows if certain(r))
    out.append(f"-- {len(rows)} groups: {kept} certain with counts, "
               f"{len(rows) - kept} recorded uncertain with a name and a reason.")
    print("\n".join(out))


if __name__ == "__main__":
    main()
