-- Areas as flat tags, not a hierarchy.
--
-- A fall can carry several: Lake Toxaway AND Lake Toxaway South, because the
-- two sources describe the same ground at different grain and both are worth
-- filtering by. No parent/child -- "tag it as both" says the same thing with
-- none of the machinery, and it makes disagreements harmless rather than
-- something to resolve.
--
-- Sources:
--   cmc    the Location column of seed.csv (94 assignments)
--   adams  the Location/Hub column of the Kevin Adams 500 list (461)
--
-- The seed column needed cleaning first -- it carries working notes, not just
-- place names: 'Brevard A WRONG????', 'Grandfather Mtn C -- this doesn't seem
-- right???'. Trailing A/B/C suffixes and everything after '--' are dropped,
-- and '/' or ' - ' splits into separate tags, so 'GSMNP / Cherokee' becomes two
-- tags rather than an unresolvable value. Mtn/Mt are spelled out so the two
-- sources' names for one place land on one tag.

BEGIN;

CREATE TABLE areas (
    id         serial PRIMARY KEY,
    name       varchar(80) NOT NULL UNIQUE,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE feature_areas (
    feature_id integer NOT NULL REFERENCES features(id) ON DELETE CASCADE,
    area_id    integer NOT NULL REFERENCES areas(id) ON DELETE CASCADE,
    -- part of the key: when both sources put a fall in the same area, that is
    -- corroboration and worth keeping, not a duplicate to collapse.
    source     varchar(20) NOT NULL,
    PRIMARY KEY (feature_id, area_id, source)
);

CREATE INDEX feature_areas_area_idx ON feature_areas (area_id);

INSERT INTO areas (name) VALUES
    ('Asheville'),
    ('Balsam Grove'),
    ('Big Creek & Harmon Den'),
    ('Big Ivy'),
    ('Blowing Rock'),
    ('Boone'),
    ('Brevard'),
    ('Brevard North'),
    ('Brevard South'),
    ('Bryson City'),
    ('Burnsville'),
    ('Cashiers'),
    ('Central and Eastern NC'),
    ('Cherokee'),
    ('Craggy Gardens'),
    ('Cullowhee'),
    ('Dupont Forest'),
    ('Elk Park'),
    ('Franklin'),
    ('GSMNP'),
    ('Grandfather Mountain'),
    ('Greenville County SC'),
    ('Hanging Rock & Mayo River'),
    ('Hickory Nut Gorge'),
    ('Highlands'),
    ('Hot Springs'),
    ('Lake Toxaway'),
    ('Lake Toxaway North'),
    ('Lake Toxaway South'),
    ('Linville Falls'),
    ('Linville Gorge'),
    ('Little Switzerland'),
    ('Maggie Valley'),
    ('Marion'),
    ('Morganton'),
    ('Mount Mitchell'),
    ('Murphy & Hayesville'),
    ('Nantahala Gorge'),
    ('Oconee County SC'),
    ('Old Fort'),
    ('Pickens County SC'),
    ('Robbinsville'),
    ('Rosman'),
    ('Saluda'),
    ('Saluda-Tryon-Columbus'),
    ('Shining Rock'),
    ('Shining Rock & Middle Prong'),
    ('South Mountains'),
    ('Spruce Pine'),
    ('Stone Mountain State Park'),
    ('Sylva'),
    ('Valdese'),
    ('West Jefferson'),
    ('Wilkesboro'),
    ('Wilson''s Creek');

INSERT INTO feature_areas (feature_id, area_id, source)
SELECT v.fid, a.id, v.src
FROM (VALUES
    (310, 'Lake Toxaway North', 'adams'),
    (311, 'Grandfather Mountain', 'adams'),
    (311, 'Grandfather Mountain', 'cmc'),
    (312, 'Oconee County SC', 'cmc'),
    (313, 'Brevard', 'cmc'),
    (313, 'Brevard North', 'adams'),
    (314, 'Elk Park', 'cmc'),
    (315, 'GSMNP', 'cmc'),
    (316, 'Lake Toxaway', 'cmc'),
    (316, 'Lake Toxaway South', 'adams'),
    (317, 'Lake Toxaway', 'cmc'),
    (318, 'Lake Toxaway', 'cmc'),
    (318, 'Lake Toxaway South', 'adams'),
    (319, 'Lake Toxaway', 'cmc'),
    (319, 'Lake Toxaway North', 'adams'),
    (320, 'Lake Toxaway', 'cmc'),
    (321, 'Pickens County SC', 'cmc'),
    (321, 'Rosman', 'adams'),
    (322, 'Brevard', 'cmc'),
    (322, 'Brevard North', 'adams'),
    (323, 'Cashiers', 'adams'),
    (323, 'Cashiers', 'cmc'),
    (324, 'Cherokee', 'adams'),
    (324, 'Cherokee', 'cmc'),
    (325, 'Cherokee', 'adams'),
    (325, 'Cherokee', 'cmc'),
    (327, 'Franklin', 'adams'),
    (327, 'Franklin', 'cmc'),
    (328, 'Grandfather Mountain', 'adams'),
    (328, 'Grandfather Mountain', 'cmc'),
    (328, 'Wilson''s Creek', 'cmc'),
    (330, 'Highlands', 'adams'),
    (330, 'Highlands', 'cmc'),
    (331, 'Highlands', 'adams'),
    (331, 'Highlands', 'cmc'),
    (332, 'Highlands', 'adams'),
    (333, 'Lake Toxaway', 'cmc'),
    (333, 'Lake Toxaway South', 'adams'),
    (334, 'Lake Toxaway', 'cmc'),
    (335, 'Oconee County SC', 'cmc'),
    (336, 'Oconee County SC', 'cmc'),
    (337, 'Oconee County SC', 'cmc'),
    (338, 'Balsam Grove', 'adams'),
    (338, 'Rosman', 'cmc'),
    (339, 'Shining Rock', 'cmc'),
    (339, 'Shining Rock & Middle Prong', 'adams'),
    (340, 'Brevard', 'cmc'),
    (340, 'Brevard North', 'adams'),
    (341, 'Brevard', 'cmc'),
    (341, 'Brevard North', 'adams'),
    (342, 'Lake Toxaway South', 'adams'),
    (343, 'Hickory Nut Gorge', 'adams'),
    (343, 'Hickory Nut Gorge', 'cmc'),
    (344, 'Lake Toxaway', 'cmc'),
    (344, 'Lake Toxaway North', 'adams'),
    (345, 'Lake Toxaway', 'cmc'),
    (345, 'Lake Toxaway North', 'adams'),
    (346, 'Lake Toxaway', 'cmc'),
    (346, 'Lake Toxaway South', 'adams'),
    (347, 'Brevard North', 'adams'),
    (347, 'Oconee County SC', 'cmc'),
    (348, 'Robbinsville', 'cmc'),
    (349, 'Balsam Grove', 'adams'),
    (349, 'Rosman', 'cmc'),
    (350, 'Shining Rock', 'cmc'),
    (350, 'Shining Rock & Middle Prong', 'adams'),
    (351, 'Brevard', 'cmc'),
    (352, 'Bryson City', 'adams'),
    (353, 'Brevard South', 'adams'),
    (353, 'Dupont Forest', 'cmc'),
    (354, 'Brevard', 'cmc'),
    (354, 'Dupont Forest', 'cmc'),
    (355, 'Grandfather Mountain', 'adams'),
    (355, 'Grandfather Mountain', 'cmc'),
    (356, 'Grandfather Mountain', 'adams'),
    (356, 'Grandfather Mountain', 'cmc'),
    (357, 'Greenville County SC', 'cmc'),
    (358, 'Cherokee', 'adams'),
    (358, 'Cherokee', 'cmc'),
    (358, 'GSMNP', 'cmc'),
    (359, 'Highlands', 'cmc'),
    (359, 'Lake Toxaway South', 'adams'),
    (360, 'Highlands', 'adams'),
    (360, 'Highlands', 'cmc'),
    (361, 'Lake Toxaway', 'cmc'),
    (361, 'Lake Toxaway South', 'adams'),
    (362, 'Lake Toxaway', 'cmc'),
    (363, 'Morganton', 'cmc'),
    (363, 'South Mountains', 'adams'),
    (364, 'Balsam Grove', 'adams'),
    (364, 'Rosman', 'cmc'),
    (365, 'Shining Rock', 'cmc'),
    (366, 'Brevard', 'cmc'),
    (366, 'Brevard North', 'adams'),
    (367, 'Grandfather Mountain', 'adams'),
    (367, 'Grandfather Mountain', 'cmc'),
    (368, 'Highlands', 'adams'),
    (368, 'Highlands', 'cmc'),
    (369, 'Lake Toxaway', 'cmc'),
    (369, 'Lake Toxaway North', 'adams'),
    (370, 'Lake Toxaway', 'cmc'),
    (370, 'Lake Toxaway North', 'adams'),
    (371, 'Oconee County SC', 'cmc'),
    (373, 'Big Creek & Harmon Den', 'adams'),
    (373, 'Maggie Valley', 'cmc'),
    (374, 'Grandfather Mountain', 'adams'),
    (374, 'Grandfather Mountain', 'cmc'),
    (376, 'Blowing Rock', 'adams'),
    (378, 'Brevard', 'cmc'),
    (378, 'Brevard North', 'adams'),
    (379, 'Brevard North', 'adams'),
    (380, 'Brevard', 'cmc'),
    (380, 'Brevard North', 'adams'),
    (381, 'Brevard', 'cmc'),
    (381, 'Brevard North', 'adams'),
    (382, 'Brevard', 'cmc'),
    (383, 'Brevard', 'cmc'),
    (383, 'Brevard North', 'adams'),
    (384, 'Brevard', 'cmc'),
    (385, 'Brevard', 'cmc'),
    (385, 'Brevard North', 'adams'),
    (386, 'Grandfather Mountain', 'adams'),
    (386, 'Grandfather Mountain', 'cmc'),
    (387, 'Grandfather Mountain', 'adams'),
    (387, 'Grandfather Mountain', 'cmc'),
    (388, 'Grandfather Mountain', 'adams'),
    (388, 'Grandfather Mountain', 'cmc'),
    (389, 'Lake Toxaway South', 'adams'),
    (390, 'GSMNP', 'cmc'),
    (391, 'Lake Toxaway', 'cmc'),
    (391, 'Lake Toxaway North', 'adams'),
    (392, 'Lake Toxaway', 'cmc'),
    (393, 'Lake Toxaway', 'cmc'),
    (394, 'Lake Toxaway', 'cmc'),
    (394, 'Lake Toxaway South', 'adams'),
    (395, 'Linville Falls', 'cmc'),
    (395, 'Linville Gorge', 'adams'),
    (396, 'Little Switzerland', 'adams'),
    (396, 'Little Switzerland', 'cmc'),
    (397, 'Big Creek & Harmon Den', 'adams'),
    (397, 'Maggie Valley', 'cmc'),
    (398, 'Marion', 'adams'),
    (398, 'Marion', 'cmc'),
    (399, 'Mount Mitchell', 'adams'),
    (399, 'Mount Mitchell', 'cmc'),
    (400, 'Mount Mitchell', 'adams'),
    (400, 'Mount Mitchell', 'cmc'),
    (401, 'Big Ivy', 'cmc'),
    (401, 'Craggy Gardens', 'adams'),
    (401, 'Mount Mitchell', 'cmc'),
    (402, 'Oconee County SC', 'cmc'),
    (403, 'Oconee County SC', 'cmc'),
    (404, 'Oconee County SC', 'cmc'),
    (405, 'Old Fort', 'adams'),
    (405, 'Old Fort', 'cmc'),
    (407, 'Balsam Grove', 'adams'),
    (407, 'Rosman', 'cmc'),
    (408, 'Saluda', 'cmc'),
    (408, 'Saluda-Tryon-Columbus', 'adams'),
    (409, 'Brevard North', 'adams'),
    (409, 'Saluda', 'cmc'),
    (410, 'Saluda', 'cmc'),
    (410, 'Saluda-Tryon-Columbus', 'adams'),
    (411, 'Shining Rock', 'cmc'),
    (412, 'Shining Rock', 'cmc'),
    (412, 'Shining Rock & Middle Prong', 'adams'),
    (413, 'Lake Toxaway North', 'adams'),
    (414, 'Lake Toxaway North', 'adams'),
    (415, 'Lake Toxaway North', 'adams'),
    (416, 'Lake Toxaway North', 'adams'),
    (417, 'Brevard South', 'adams'),
    (418, 'Brevard North', 'adams'),
    (419, 'Boone', 'adams'),
    (420, 'Blowing Rock', 'adams'),
    (422, 'Old Fort', 'adams'),
    (423, 'Hickory Nut Gorge', 'adams'),
    (424, 'Saluda-Tryon-Columbus', 'adams'),
    (425, 'Brevard North', 'adams'),
    (426, 'Shining Rock & Middle Prong', 'adams'),
    (428, 'Shining Rock & Middle Prong', 'adams'),
    (429, 'Lake Toxaway South', 'adams'),
    (430, 'Lake Toxaway North', 'adams'),
    (432, 'Bryson City', 'adams'),
    (461, 'Brevard South', 'adams'),
    (462, 'Brevard South', 'adams'),
    (463, 'Brevard North', 'adams'),
    (464, 'Brevard North', 'adams'),
    (468, 'Lake Toxaway South', 'adams'),
    (469, 'Lake Toxaway South', 'adams'),
    (471, 'Cashiers', 'adams'),
    (472, 'Brevard North', 'adams'),
    (473, 'Shining Rock & Middle Prong', 'adams'),
    (482, 'Brevard South', 'adams'),
    (483, 'Bryson City', 'adams'),
    (484, 'Bryson City', 'adams'),
    (486, 'Brevard North', 'adams'),
    (487, 'Shining Rock & Middle Prong', 'adams'),
    (488, 'Shining Rock & Middle Prong', 'adams'),
    (489, 'Shining Rock & Middle Prong', 'adams'),
    (490, 'Shining Rock & Middle Prong', 'adams'),
    (491, 'Hanging Rock & Mayo River', 'adams'),
    (492, 'Hanging Rock & Mayo River', 'adams'),
    (493, 'Hanging Rock & Mayo River', 'adams'),
    (494, 'Hanging Rock & Mayo River', 'adams'),
    (495, 'Hanging Rock & Mayo River', 'adams'),
    (498, 'Balsam Grove', 'adams'),
    (500, 'Brevard North', 'adams'),
    (501, 'Brevard North', 'adams'),
    (502, 'Brevard North', 'adams'),
    (503, 'Balsam Grove', 'adams'),
    (504, 'Shining Rock & Middle Prong', 'adams'),
    (505, 'Brevard North', 'adams'),
    (506, 'Brevard South', 'adams'),
    (507, 'Brevard South', 'adams'),
    (508, 'Stone Mountain State Park', 'adams'),
    (511, 'Lake Toxaway North', 'adams'),
    (512, 'Shining Rock & Middle Prong', 'adams'),
    (518, 'Brevard North', 'adams'),
    (526, 'Lake Toxaway North', 'adams'),
    (528, 'Stone Mountain State Park', 'adams'),
    (531, 'Balsam Grove', 'adams'),
    (532, 'Balsam Grove', 'adams'),
    (536, 'Shining Rock & Middle Prong', 'adams'),
    (538, 'Lake Toxaway South', 'adams'),
    (539, 'Lake Toxaway South', 'adams'),
    (540, 'Lake Toxaway South', 'adams'),
    (541, 'Lake Toxaway South', 'adams'),
    (542, 'Lake Toxaway South', 'adams'),
    (543, 'Lake Toxaway South', 'adams'),
    (544, 'Brevard North', 'adams'),
    (545, 'Lake Toxaway North', 'adams'),
    (548, 'Brevard North', 'adams'),
    (549, 'Cashiers', 'adams'),
    (550, 'Highlands', 'adams'),
    (551, 'Highlands', 'adams'),
    (552, 'Highlands', 'adams'),
    (553, 'Highlands', 'adams'),
    (554, 'Lake Toxaway South', 'adams'),
    (555, 'Lake Toxaway North', 'adams'),
    (556, 'Lake Toxaway North', 'adams'),
    (557, 'Lake Toxaway North', 'adams'),
    (562, 'Lake Toxaway South', 'adams'),
    (564, 'Lake Toxaway South', 'adams'),
    (565, 'Lake Toxaway South', 'adams'),
    (567, 'Lake Toxaway South', 'adams'),
    (568, 'Lake Toxaway South', 'adams'),
    (569, 'Linville Gorge', 'adams'),
    (570, 'Old Fort', 'adams'),
    (571, 'Little Switzerland', 'adams'),
    (572, 'Craggy Gardens', 'adams'),
    (573, 'Mount Mitchell', 'adams'),
    (574, 'Balsam Grove', 'adams'),
    (575, 'Shining Rock & Middle Prong', 'adams'),
    (576, 'Rosman', 'adams'),
    (577, 'Balsam Grove', 'adams'),
    (578, 'Balsam Grove', 'adams'),
    (580, 'Brevard South', 'adams'),
    (581, 'Rosman', 'adams'),
    (582, 'Balsam Grove', 'adams'),
    (583, 'Brevard North', 'adams'),
    (584, 'Brevard North', 'adams'),
    (585, 'Saluda-Tryon-Columbus', 'adams'),
    (586, 'Saluda-Tryon-Columbus', 'adams'),
    (587, 'Saluda-Tryon-Columbus', 'adams'),
    (589, 'Saluda-Tryon-Columbus', 'adams'),
    (590, 'Saluda-Tryon-Columbus', 'adams'),
    (594, 'Brevard North', 'adams'),
    (595, 'Brevard North', 'adams'),
    (602, 'Highlands', 'adams'),
    (603, 'Highlands', 'adams'),
    (605, 'Highlands', 'adams'),
    (606, 'Highlands', 'adams'),
    (608, 'Highlands', 'adams'),
    (609, 'Nantahala Gorge', 'adams'),
    (610, 'Nantahala Gorge', 'adams'),
    (612, 'Nantahala Gorge', 'adams'),
    (613, 'Nantahala Gorge', 'adams'),
    (614, 'Nantahala Gorge', 'adams'),
    (622, 'Brevard North', 'adams'),
    (629, 'Highlands', 'adams'),
    (630, 'Highlands', 'adams'),
    (631, 'Highlands', 'adams'),
    (632, 'Highlands', 'adams'),
    (634, 'Highlands', 'adams'),
    (636, 'Brevard South', 'adams'),
    (637, 'Brevard South', 'adams'),
    (638, 'Saluda-Tryon-Columbus', 'adams'),
    (639, 'Highlands', 'adams'),
    (640, 'Highlands', 'adams'),
    (641, 'Highlands', 'adams'),
    (642, 'Highlands', 'adams'),
    (643, 'Robbinsville', 'adams'),
    (644, 'Robbinsville', 'adams'),
    (645, 'Rosman', 'adams'),
    (646, 'Rosman', 'adams'),
    (647, 'Rosman', 'adams'),
    (648, 'Balsam Grove', 'adams'),
    (649, 'Rosman', 'adams'),
    (650, 'Lake Toxaway North', 'adams'),
    (651, 'Lake Toxaway North', 'adams'),
    (652, 'Lake Toxaway North', 'adams'),
    (654, 'Lake Toxaway North', 'adams'),
    (655, 'Lake Toxaway North', 'adams'),
    (656, 'Cullowhee', 'adams'),
    (657, 'Cullowhee', 'adams'),
    (659, 'Cullowhee', 'adams'),
    (660, 'Cullowhee', 'adams'),
    (661, 'Brevard North', 'adams'),
    (662, 'Brevard North', 'adams'),
    (663, 'Brevard North', 'adams'),
    (664, 'Saluda-Tryon-Columbus', 'adams'),
    (666, 'Brevard North', 'adams'),
    (667, 'Balsam Grove', 'adams'),
    (668, 'Franklin', 'adams'),
    (669, 'Franklin', 'adams'),
    (670, 'Franklin', 'adams'),
    (671, 'Craggy Gardens', 'adams'),
    (676, 'Cullowhee', 'adams'),
    (677, 'Cullowhee', 'adams'),
    (678, 'Cullowhee', 'adams'),
    (679, 'Cullowhee', 'adams'),
    (680, 'Cullowhee', 'adams'),
    (681, 'Cullowhee', 'adams'),
    (682, 'Brevard North', 'adams'),
    (683, 'Brevard North', 'adams'),
    (685, 'South Mountains', 'adams'),
    (688, 'Brevard North', 'adams'),
    (689, 'Brevard North', 'adams'),
    (693, 'Brevard North', 'adams'),
    (694, 'Brevard North', 'adams'),
    (695, 'Brevard North', 'adams'),
    (696, 'Saluda-Tryon-Columbus', 'adams'),
    (697, 'Saluda-Tryon-Columbus', 'adams'),
    (700, 'Brevard North', 'adams'),
    (701, 'Brevard North', 'adams'),
    (702, 'Brevard North', 'adams'),
    (703, 'Lake Toxaway South', 'adams'),
    (704, 'Lake Toxaway South', 'adams'),
    (705, 'Lake Toxaway South', 'adams'),
    (706, 'Lake Toxaway South', 'adams'),
    (707, 'Shining Rock & Middle Prong', 'adams'),
    (709, 'Highlands', 'adams'),
    (710, 'Highlands', 'adams'),
    (712, 'Lake Toxaway North', 'adams'),
    (713, 'Lake Toxaway South', 'adams'),
    (714, 'Lake Toxaway South', 'adams'),
    (715, 'Lake Toxaway South', 'adams'),
    (716, 'Lake Toxaway North', 'adams'),
    (717, 'Cashiers', 'adams'),
    (718, 'Cashiers', 'adams'),
    (719, 'Highlands', 'adams'),
    (720, 'Robbinsville', 'adams'),
    (721, 'Robbinsville', 'adams'),
    (722, 'Robbinsville', 'adams'),
    (724, 'Robbinsville', 'adams'),
    (725, 'Nantahala Gorge', 'adams'),
    (726, 'Nantahala Gorge', 'adams'),
    (727, 'Highlands', 'adams'),
    (728, 'Highlands', 'adams'),
    (729, 'Highlands', 'adams'),
    (730, 'Franklin', 'adams'),
    (731, 'Highlands', 'adams'),
    (737, 'Highlands', 'adams'),
    (739, 'Franklin', 'adams'),
    (741, 'Franklin', 'adams'),
    (742, 'Franklin', 'adams'),
    (743, 'Murphy & Hayesville', 'adams'),
    (744, 'Murphy & Hayesville', 'adams'),
    (745, 'Murphy & Hayesville', 'adams'),
    (746, 'Murphy & Hayesville', 'adams'),
    (755, 'Hot Springs', 'adams'),
    (756, 'South Mountains', 'adams'),
    (758, 'Nantahala Gorge', 'adams'),
    (759, 'Nantahala Gorge', 'adams'),
    (761, 'Nantahala Gorge', 'adams'),
    (762, 'Nantahala Gorge', 'adams'),
    (763, 'Nantahala Gorge', 'adams'),
    (764, 'Nantahala Gorge', 'adams'),
    (765, 'Blowing Rock', 'adams'),
    (766, 'Blowing Rock', 'adams'),
    (768, 'Blowing Rock', 'adams'),
    (769, 'Blowing Rock', 'adams'),
    (770, 'Elk Park', 'adams'),
    (771, 'Elk Park', 'adams'),
    (772, 'Boone', 'adams'),
    (775, 'Boone', 'adams'),
    (776, 'Shining Rock & Middle Prong', 'adams'),
    (777, 'Shining Rock & Middle Prong', 'adams'),
    (778, 'Shining Rock & Middle Prong', 'adams'),
    (779, 'Shining Rock & Middle Prong', 'adams'),
    (780, 'Lake Toxaway South', 'adams'),
    (781, 'Grandfather Mountain', 'adams'),
    (782, 'Grandfather Mountain', 'adams'),
    (783, 'Grandfather Mountain', 'adams'),
    (784, 'Grandfather Mountain', 'adams'),
    (785, 'Grandfather Mountain', 'adams'),
    (786, 'Grandfather Mountain', 'adams'),
    (787, 'Grandfather Mountain', 'adams'),
    (788, 'Grandfather Mountain', 'adams'),
    (789, 'Grandfather Mountain', 'adams'),
    (790, 'Grandfather Mountain', 'adams'),
    (791, 'Grandfather Mountain', 'adams'),
    (792, 'Grandfather Mountain', 'adams'),
    (793, 'Grandfather Mountain', 'adams'),
    (794, 'Grandfather Mountain', 'adams'),
    (795, 'Grandfather Mountain', 'adams'),
    (797, 'Grandfather Mountain', 'adams'),
    (798, 'Grandfather Mountain', 'adams'),
    (799, 'Grandfather Mountain', 'adams'),
    (805, 'Balsam Grove', 'adams'),
    (806, 'Balsam Grove', 'adams'),
    (808, 'Balsam Grove', 'adams'),
    (810, 'Lake Toxaway South', 'adams'),
    (811, 'Lake Toxaway South', 'adams'),
    (812, 'Robbinsville', 'adams'),
    (813, 'Robbinsville', 'adams'),
    (814, 'Robbinsville', 'adams'),
    (815, 'Robbinsville', 'adams'),
    (816, 'Robbinsville', 'adams'),
    (817, 'Robbinsville', 'adams'),
    (818, 'Robbinsville', 'adams'),
    (819, 'Robbinsville', 'adams'),
    (820, 'Robbinsville', 'adams'),
    (821, 'Old Fort', 'adams'),
    (822, 'Shining Rock & Middle Prong', 'adams'),
    (823, 'Shining Rock & Middle Prong', 'adams'),
    (824, 'Shining Rock & Middle Prong', 'adams'),
    (825, 'Hot Springs', 'adams'),
    (826, 'Hot Springs', 'adams'),
    (827, 'Shining Rock & Middle Prong', 'adams'),
    (828, 'Sylva', 'adams'),
    (829, 'Franklin', 'adams'),
    (830, 'Lake Toxaway North', 'adams'),
    (831, 'Valdese', 'adams'),
    (832, 'Shining Rock & Middle Prong', 'adams'),
    (833, 'Shining Rock & Middle Prong', 'adams'),
    (834, 'Shining Rock & Middle Prong', 'adams'),
    (835, 'Balsam Grove', 'adams'),
    (836, 'Brevard North', 'adams'),
    (837, 'Old Fort', 'adams'),
    (838, 'Shining Rock & Middle Prong', 'adams'),
    (839, 'Big Creek & Harmon Den', 'adams'),
    (840, 'Big Creek & Harmon Den', 'adams'),
    (841, 'Big Creek & Harmon Den', 'adams'),
    (842, 'Cherokee', 'adams'),
    (843, 'Cherokee', 'adams'),
    (844, 'Lake Toxaway North', 'adams'),
    (848, 'Lake Toxaway North', 'adams'),
    (849, 'Saluda', 'adams'),
    (853, 'Linville Gorge', 'adams'),
    (854, 'Linville Gorge', 'adams'),
    (855, 'Lake Toxaway South', 'adams'),
    (856, 'Lake Toxaway South', 'adams'),
    (858, 'Bryson City', 'adams'),
    (859, 'Bryson City', 'adams'),
    (860, 'Bryson City', 'adams'),
    (861, 'Cherokee', 'adams'),
    (862, 'Cherokee', 'adams'),
    (864, 'Lake Toxaway South', 'adams'),
    (865, 'Lake Toxaway South', 'adams'),
    (868, 'Lake Toxaway South', 'adams'),
    (869, 'Lake Toxaway North', 'adams'),
    (870, 'Shining Rock & Middle Prong', 'adams'),
    (871, 'Shining Rock & Middle Prong', 'adams'),
    (872, 'Shining Rock & Middle Prong', 'adams'),
    (873, 'Shining Rock & Middle Prong', 'adams'),
    (878, 'Lake Toxaway South', 'adams'),
    (882, 'Lake Toxaway South', 'adams'),
    (883, 'Murphy & Hayesville', 'adams'),
    (884, 'Murphy & Hayesville', 'adams'),
    (885, 'Marion', 'adams'),
    (886, 'Spruce Pine', 'adams'),
    (887, 'Craggy Gardens', 'adams'),
    (888, 'Burnsville', 'adams'),
    (889, 'Lake Toxaway North', 'adams'),
    (890, 'Cashiers', 'adams'),
    (891, 'South Mountains', 'adams'),
    (892, 'Old Fort', 'adams'),
    (893, 'Balsam Grove', 'adams'),
    (894, 'Balsam Grove', 'adams'),
    (895, 'Balsam Grove', 'adams'),
    (896, 'Asheville', 'adams'),
    (897, 'Spruce Pine', 'adams'),
    (898, 'Linville Gorge', 'adams'),
    (899, 'Linville Gorge', 'adams'),
    (900, 'Linville Gorge', 'adams'),
    (901, 'Grandfather Mountain', 'adams'),
    (902, 'Grandfather Mountain', 'adams'),
    (903, 'Grandfather Mountain', 'adams'),
    (904, 'Grandfather Mountain', 'adams'),
    (905, 'Sylva', 'adams'),
    (906, 'Sylva', 'adams'),
    (907, 'Wilkesboro', 'adams'),
    (908, 'Central and Eastern NC', 'adams'),
    (909, 'Central and Eastern NC', 'adams'),
    (910, 'Central and Eastern NC', 'adams'),
    (911, 'Central and Eastern NC', 'adams'),
    (912, 'Central and Eastern NC', 'adams'),
    (913, 'Lake Toxaway South', 'adams'),
    (914, 'Lake Toxaway South', 'adams'),
    (915, 'Lake Toxaway South', 'adams'),
    (916, 'Lake Toxaway South', 'adams'),
    (919, 'Franklin', 'adams'),
    (920, 'Franklin', 'adams'),
    (921, 'Franklin', 'adams'),
    (922, 'Franklin', 'adams'),
    (923, 'Franklin', 'adams'),
    (924, 'Cherokee', 'adams'),
    (925, 'Cherokee', 'adams'),
    (926, 'Brevard North', 'adams'),
    (927, 'Brevard North', 'adams'),
    (928, 'Grandfather Mountain', 'adams'),
    (929, 'West Jefferson', 'adams'),
    (930, 'West Jefferson', 'adams'),
    (931, 'West Jefferson', 'adams'),
    (932, 'Stone Mountain State Park', 'adams'),
    (934, 'Nantahala Gorge', 'adams'),
    (935, 'Nantahala Gorge', 'adams'),
    (936, 'Nantahala Gorge', 'adams'),
    (938, 'Lake Toxaway South', 'adams'),
    (940, 'Lake Toxaway South', 'adams'),
    (941, 'Lake Toxaway South', 'adams'),
    (942, 'Cherokee', 'adams'),
    (943, 'Cherokee', 'adams'),
    (944, 'Bryson City', 'adams'),
    (945, 'Grandfather Mountain', 'adams'),
    (946, 'Grandfather Mountain', 'adams'),
    (947, 'Big Creek & Harmon Den', 'adams'),
    (948, 'Big Creek & Harmon Den', 'adams'),
    (950, 'Franklin', 'adams'),
    (952, 'Grandfather Mountain', 'adams'),
    (953, 'Linville Gorge', 'adams'),
    (954, 'Brevard North', 'adams'),
    (963, 'Shining Rock & Middle Prong', 'adams'),
    (970, 'South Mountains', 'adams'),
    (973, 'Lake Toxaway South', 'adams'),
    (991, 'Lake Toxaway North', 'adams'),
    (1011, 'Shining Rock & Middle Prong', 'adams'),
    (1012, 'Shining Rock & Middle Prong', 'adams'),
    (1014, 'Brevard North', 'adams'),
    (1051, 'Brevard North', 'adams'),
    (1090, 'Lake Toxaway South', 'adams'),
    (1101, 'Brevard North', 'adams'),
    (1157, 'Shining Rock & Middle Prong', 'adams'),
    (1209, 'Balsam Grove', 'adams'),
    (1212, 'Lake Toxaway South', 'adams'),
    (1238, 'Lake Toxaway North', 'adams'),
    (1256, 'Lake Toxaway North', 'adams'),
    (1257, 'Lake Toxaway North', 'adams'),
    (1261, 'Lake Toxaway North', 'adams'),
    (1262, 'Lake Toxaway North', 'adams'),
    (1263, 'Lake Toxaway North', 'adams'),
    (1264, 'Lake Toxaway North', 'adams'),
    (1265, 'Lake Toxaway North', 'adams'),
    (1266, 'Lake Toxaway North', 'adams')
) AS v(fid, nm, src)
JOIN areas a ON a.name = v.nm
WHERE EXISTS (SELECT 1 FROM features f WHERE f.id = v.fid);

COMMIT;
