-- Owner, official CMC areas, and a place for user-submitted corrections.
--
-- Source: the Carolina Mountain Club WC100 log form, revised 18 Feb 2024, 115
-- entries. Matched to features by name, then disambiguated by the form's own
-- area column -- it lists four different "High Falls", three "Rainbow Falls"
-- and two "Twin Falls", so the name alone cannot resolve any of them.
-- 106 of 115 matched; the rest are left alone rather than guessed.
--
-- Note the form's areas are already fine-grained (Lake Toxaway North/South,
-- Brevard North/South). The coarsening to plain "Lake Toxaway" came from
-- seed.csv, not from CMC. Obvious typos in the form are corrected on the way
-- in: Linviille -> Linville, Shinning -> Shining.

BEGIN;

-- 1. who owns the land it sits on -------------------------------------------
ALTER TABLE features ADD COLUMN owner varchar(40);

COMMENT ON COLUMN features.owner IS
    'Landowner/manager: Federal, State, GSMNP, Cherokee, Conservancy, Private, Duke Energy. Drives access expectations -- Private may charge, Conservancy may restrict hours.';

UPDATE features SET owner = v.owner FROM (VALUES
    (310, 'Federal'),
    (312, 'Federal'),
    (313, 'Federal'),
    (314, 'Federal'),
    (315, 'GSMNP'),
    (316, 'Federal'),
    (318, 'Federal'),
    (319, 'Federal'),
    (324, 'Cherokee'),
    (325, 'Cherokee'),
    (326, 'Federal'),
    (327, 'Federal'),
    (328, 'Federal'),
    (329, 'State'),
    (330, 'Federal'),
    (331, 'Federal'),
    (332, 'Federal'),
    (333, 'State'),
    (334, 'State'),
    (336, 'Federal'),
    (337, 'Federal'),
    (338, 'Federal'),
    (340, 'Federal'),
    (341, 'Federal'),
    (342, 'State'),
    (343, 'State'),
    (344, 'Federal'),
    (345, 'Federal'),
    (347, 'Federal'),
    (349, 'Federal'),
    (350, 'Federal'),
    (351, 'Federal'),
    (352, 'GSMNP'),
    (353, 'State'),
    (354, 'State'),
    (355, 'Federal'),
    (357, 'State'),
    (359, 'State'),
    (360, 'Federal'),
    (361, 'State'),
    (362, 'Federal'),
    (363, 'State'),
    (364, 'Private'),
    (366, 'Federal'),
    (367, 'Federal'),
    (368, 'Federal'),
    (369, 'State'),
    (370, 'Federal'),
    (371, 'Federal'),
    (372, 'State'),
    (373, 'Federal'),
    (374, 'Federal'),
    (375, 'Federal'),
    (376, 'Federal'),
    (378, 'Federal'),
    (379, 'Federal'),
    (380, 'Federal'),
    (381, 'Federal'),
    (383, 'Federal'),
    (384, 'State'),
    (385, 'Federal'),
    (386, 'Federal'),
    (387, 'Federal'),
    (388, 'Federal'),
    (390, 'GSMNP'),
    (391, 'State'),
    (392, 'Federal'),
    (393, 'State'),
    (394, 'State'),
    (395, 'Federal'),
    (396, 'Federal'),
    (397, 'GSMNP'),
    (398, 'Federal'),
    (399, 'Federal'),
    (400, 'Federal'),
    (401, 'Federal'),
    (402, 'Federal'),
    (403, 'Federal'),
    (404, 'Federal'),
    (405, 'Federal'),
    (406, 'Federal'),
    (407, 'Federal'),
    (408, 'Private'),
    (410, 'Federal'),
    (417, 'State'),
    (419, 'Conservancy'),
    (420, 'Conservancy'),
    (421, 'Federal'),
    (422, 'Federal'),
    (423, 'Conservancy'),
    (424, 'Conservancy'),
    (425, 'Federal'),
    (426, 'Federal'),
    (427, 'Federal'),
    (429, 'State'),
    (430, 'State'),
    (432, 'Federal'),
    (433, 'Federal'),
    (434, 'Federal'),
    (435, 'GSMNP'),
    (436, 'GSMNP'),
    (481, 'Federal'),
    (643, 'Federal'),
    (644, 'Federal'),
    (838, 'Federal'),
    (1101, 'Federal')
) AS v(fid, owner) WHERE features.id = v.fid;

-- 2. the official areas, as more tags ---------------------------------------
INSERT INTO areas (name) VALUES
    ('Blowing Rock'),
    ('Boone'),
    ('Brevard North'),
    ('Brevard South'),
    ('Bryson City'),
    ('Cherokee'),
    ('Craggy Gardens'),
    ('Elk Falls'),
    ('Franklin'),
    ('GSMNP'),
    ('Grandfather Mountain'),
    ('Greenville County SC'),
    ('Hickory Nut Gorge'),
    ('Highlands'),
    ('Lake Toxaway North'),
    ('Lake Toxaway South'),
    ('Linville Falls'),
    ('Little Switzerland'),
    ('Maggie Valley'),
    ('Marion'),
    ('Morganton'),
    ('Mount Mitchell'),
    ('Oconee County SC'),
    ('Old Fort'),
    ('Pickens County SC'),
    ('Robbinsville'),
    ('Rosman'),
    ('Saluda'),
    ('Shining Rock')
ON CONFLICT (name) DO NOTHING;

INSERT INTO feature_areas (feature_id, area_id, source)
SELECT v.fid, a.id, 'cmc-official'
FROM (VALUES
    (310, 'Lake Toxaway North'),
    (312, 'Oconee County SC'),
    (313, 'Brevard North'),
    (314, 'Elk Falls'),
    (315, 'GSMNP'),
    (316, 'Lake Toxaway South'),
    (318, 'Lake Toxaway South'),
    (319, 'Lake Toxaway North'),
    (324, 'Cherokee'),
    (325, 'Cherokee'),
    (326, 'Franklin'),
    (327, 'Franklin'),
    (328, 'Grandfather Mountain'),
    (329, 'Greenville County SC'),
    (330, 'Highlands'),
    (331, 'Highlands'),
    (332, 'Highlands'),
    (333, 'Lake Toxaway South'),
    (334, 'Lake Toxaway South'),
    (336, 'Oconee County SC'),
    (337, 'Oconee County SC'),
    (338, 'Rosman'),
    (340, 'Brevard North'),
    (341, 'Brevard North'),
    (342, 'Lake Toxaway South'),
    (343, 'Hickory Nut Gorge'),
    (344, 'Lake Toxaway North'),
    (345, 'Lake Toxaway North'),
    (347, 'Oconee County SC'),
    (349, 'Rosman'),
    (350, 'Shining Rock'),
    (351, 'Brevard North'),
    (352, 'Bryson City'),
    (353, 'Brevard South'),
    (354, 'Brevard South'),
    (355, 'Grandfather Mountain'),
    (357, 'Greenville County SC'),
    (359, 'Lake Toxaway South'),
    (360, 'Highlands'),
    (361, 'Lake Toxaway South'),
    (362, 'Lake Toxaway South'),
    (363, 'Morganton'),
    (364, 'Rosman'),
    (366, 'Brevard North'),
    (367, 'Grandfather Mountain'),
    (368, 'Highlands'),
    (369, 'Lake Toxaway North'),
    (370, 'Lake Toxaway North'),
    (371, 'Oconee County SC'),
    (372, 'Greenville County SC'),
    (373, 'Maggie Valley'),
    (374, 'Grandfather Mountain'),
    (375, 'Oconee County SC'),
    (376, 'Blowing Rock'),
    (378, 'Brevard North'),
    (379, 'Brevard North'),
    (380, 'Brevard North'),
    (381, 'Brevard North'),
    (383, 'Brevard North'),
    (384, 'Brevard South'),
    (385, 'Brevard North'),
    (386, 'Grandfather Mountain'),
    (387, 'Grandfather Mountain'),
    (388, 'Grandfather Mountain'),
    (390, 'GSMNP'),
    (391, 'Lake Toxaway North'),
    (392, 'Lake Toxaway North'),
    (393, 'Lake Toxaway South'),
    (394, 'Lake Toxaway South'),
    (395, 'Linville Falls'),
    (396, 'Little Switzerland'),
    (397, 'Maggie Valley'),
    (398, 'Marion'),
    (399, 'Mount Mitchell'),
    (400, 'Mount Mitchell'),
    (401, 'Craggy Gardens'),
    (402, 'Oconee County SC'),
    (403, 'Oconee County SC'),
    (404, 'Oconee County SC'),
    (405, 'Old Fort'),
    (406, 'Pickens County SC'),
    (407, 'Rosman'),
    (408, 'Saluda'),
    (410, 'Saluda'),
    (417, 'Brevard South'),
    (419, 'Boone'),
    (420, 'Boone'),
    (421, 'Elk Falls'),
    (422, 'Old Fort'),
    (423, 'Hickory Nut Gorge'),
    (424, 'Saluda'),
    (425, 'Brevard North'),
    (426, 'Shining Rock'),
    (427, 'Shining Rock'),
    (429, 'Lake Toxaway South'),
    (430, 'Lake Toxaway North'),
    (432, 'Bryson City'),
    (433, 'Robbinsville'),
    (434, 'Pickens County SC'),
    (435, 'GSMNP'),
    (436, 'GSMNP'),
    (481, 'Shining Rock'),
    (643, 'Lake Toxaway South'),
    (644, 'Shining Rock'),
    (838, 'Shining Rock'),
    (1101, 'Brevard North')
) AS v(fid, nm)
JOIN areas a ON a.name = v.nm
ON CONFLICT DO NOTHING;

-- 3. corrections submitted by users -----------------------------------------
-- This session alone turned up seven bad coordinates and a duplicated GPS
-- pair, all inherited from upstream. People who actually stand at these
-- waterfalls will find more, and there is currently nowhere for them to say so.
CREATE TABLE corrections (
    id            serial PRIMARY KEY,
    user_id       integer REFERENCES users(id) ON DELETE SET NULL,
    -- nullable: "you are missing a fall entirely" is a correction too, and has
    -- no feature to hang off. subject carries the name in that case.
    feature_id    integer REFERENCES features(id) ON DELETE CASCADE,
    subject       text,
    field         varchar(40),
    current_value text,
    suggested_value text,
    comment       text,
    status        varchar(20) NOT NULL DEFAULT 'open',
    resolved_by   integer REFERENCES users(id) ON DELETE SET NULL,
    resolved_at   timestamp,
    created_at    timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT corrections_status_check
        CHECK (status IN ('open','accepted','rejected','duplicate')),
    CONSTRAINT corrections_has_target
        CHECK (feature_id IS NOT NULL OR subject IS NOT NULL)
);

CREATE INDEX corrections_open_idx ON corrections (status, created_at DESC);
CREATE INDEX corrections_feature_idx ON corrections (feature_id);

COMMIT;
