-- What dwhike.kml says, recorded as dwhike's own readings.
--
-- Generated by script/backfill_claims/kml.py. A dozen falls carry a point
-- hikingwnc never published, and this is where it came from. The file covers
-- the WC100 list, but the coordinates in it are dwhike's, so that is the name
-- they are filed under. Matched by name, and only where the name picks out
-- exactly one feature.

BEGIN;

INSERT INTO claim_groups (ref, feature_id, source, identity_certain, note) VALUES
('dwhike|400|Setrock Creek Falls', 400, 'dwhike', true, NULL),
('dwhike|399|Roaring Fork Falls', 399, 'dwhike', true, NULL),
('dwhike|363|High Shoals Falls', 363, 'dwhike', true, NULL),
('dwhike|398|<![CDATA[Tom''s Creek Falls]]>', 398, 'dwhike', true, NULL),
('dwhike|396|Crabtree Falls', 396, 'dwhike', true, NULL),
('dwhike|387|Hunt-Fish Falls', 387, 'dwhike', true, NULL),
('dwhike|376|Hebron Colony Falls', 376, 'dwhike', true, NULL),
('dwhike|386|Upper Creek Falls', 386, 'dwhike', true, NULL),
('dwhike|378|Looking Glass Falls', 378, 'dwhike', true, NULL),
('dwhike|350|Second Falls', 350, 'dwhike', true, NULL),
('dwhike|359|Drift Falls', 359, 'dwhike', true, NULL),
('dwhike|334|Turtleback Falls', 334, 'dwhike', true, NULL),
('dwhike|407|Courthouse Falls', 407, 'dwhike', true, NULL),
('dwhike|321|Eastatoe Falls', 321, 'dwhike', true, NULL),
('dwhike|380|Moore Cove Falls', 380, 'dwhike', true, NULL),
('dwhike|353|Triple Falls', 353, 'dwhike', true, NULL),
('dwhike|384|High Falls (Little River)', 384, 'dwhike', true, NULL),
('dwhike|412|Wash Hollow Falls', 412, 'dwhike', true, NULL),
('dwhike|327|Rufus Morgan Falls', 327, 'dwhike', true, NULL),
('dwhike|360|Dry Falls', 360, 'dwhike', true, NULL),
('dwhike|323|Silver Run Falls', 323, 'dwhike', true, NULL),
('dwhike|403|Issaqueena Falls', 403, 'dwhike', true, NULL),
('dwhike|371|Spoonauger Falls', 371, 'dwhike', true, NULL),
('dwhike|395|Linville Falls', 395, 'dwhike', true, NULL),
('dwhike|364|Bird Rock Falls', 364, 'dwhike', true, NULL),
('dwhike|1101|Long Branch Falls', 1101, 'dwhike', false, 'Matched to this feature by name alone. The placemark is 21.5 km from where we have it, so it may be a different fall of the same name.'),
('dwhike|391|Schoolhouse Falls', 391, 'dwhike', true, NULL),
('dwhike|324|Mingo Falls', 324, 'dwhike', true, NULL),
('dwhike|325|Soco Falls', 325, 'dwhike', true, NULL),
('dwhike|318|White Owl Falls', 318, 'dwhike', true, NULL),
('dwhike|333|Stairway Falls', 333, 'dwhike', true, NULL),
('dwhike|394|Whitewater Falls', 394, 'dwhike', true, NULL),
('dwhike|406|Twin Falls, SC', 406, 'dwhike', true, NULL),
('dwhike|401|Douglas Falls', 401, 'dwhike', true, NULL),
('dwhike|410|Little Bradley Falls', 410, 'dwhike', true, NULL),
('dwhike|496|Upper Courthouse Falls', 496, 'dwhike', true, NULL),
('dwhike|343|Hickory Nut Falls', 343, 'dwhike', true, NULL),
('dwhike|347|Yellow Branch Falls', 347, 'dwhike', false, 'Matched to this feature by name alone. The placemark is 62.1 km from where we have it, so it may be a different fall of the same name.'),
('dwhike|336|Lee Falls', 336, 'dwhike', false, 'Matched to this feature by name alone. The placemark is 50.4 km from where we have it, so it may be a different fall of the same name.'),
('dwhike|404|Station Cove Falls', 404, 'dwhike', false, 'Matched to this feature by name alone. The placemark is 50.1 km from where we have it, so it may be a different fall of the same name.'),
('dwhike|357|Moonshine Falls', 357, 'dwhike', true, NULL),
('dwhike|337|Brasstown Falls', 337, 'dwhike', true, NULL),
('dwhike|312|Long Creek Falls', 312, 'dwhike', false, 'Matched to this feature by name alone. The placemark is 62.0 km from where we have it, so it may be a different fall of the same name.'),
('dwhike|335|Opossum Creek Falls', 335, 'dwhike', true, NULL),
('dwhike|373|Little Fall Branch Falls', 373, 'dwhike', true, NULL),
('dwhike|344|Greenland Creek Falls', 344, 'dwhike', true, NULL),
('dwhike|351|High Falls (South Fork Mills River)', 351, 'dwhike', true, NULL),
('dwhike|397|Mouse Creek Falls', 397, 'dwhike', true, NULL),
('dwhike|570|Lower Catawba Falls', 570, 'dwhike', true, NULL),
('dwhike|821|Upper Catawba Falls', 821, 'dwhike', true, NULL),
('dwhike|313|Cove Creek Falls', 313, 'dwhike', true, NULL),
('dwhike|390|Grotto Falls', 390, 'dwhike', true, NULL),
('dwhike|341|Shuck Ridge Creek Falls', 341, 'dwhike', true, NULL),
('dwhike|414|Dismal Falls', 414, 'dwhike', true, NULL),
('dwhike|310|Rhapsodie Falls', 310, 'dwhike', true, NULL),
('dwhike|349|Dill Falls', 349, 'dwhike', true, NULL),
('dwhike|503|Upper Dill Falls', 503, 'dwhike', true, NULL),
('dwhike|537|Big Bradley Falls', 537, 'dwhike', true, NULL),
('dwhike|392|Flat Creek Falls', 392, 'dwhike', true, NULL),
('dwhike|326|Big Laurel Falls', 326, 'dwhike', true, NULL),
('dwhike|358|Enloe Creek Falls', 358, 'dwhike', true, NULL),
('dwhike|320|Big Falls (Thompson River)', 320, 'dwhike', true, NULL),
('dwhike|362|High Falls (Thompson River)', 362, 'dwhike', true, NULL),
('dwhike|367|Harper Creek Falls', 367, 'dwhike', true, NULL),
('dwhike|782|Upper Little Lost Cove Falls', 782, 'dwhike', true, NULL),
('dwhike|355|North Harper Creek Falls', 355, 'dwhike', false, 'Matched to this feature by name alone. The placemark is 22.8 km from where we have it, so it may be a different fall of the same name.'),
('dwhike|788|Upper Gragg Prong Falls', 788, 'dwhike', true, NULL),
('dwhike|374|South Harper Creek Falls', 374, 'dwhike', true, NULL),
('dwhike|501|Discovery Falls', 501, 'dwhike', true, NULL),
('dwhike|385|Logging Road Falls', 385, 'dwhike', true, NULL),
('dwhike|348|Middle Falls (Snowbird Creek)', 348, 'dwhike', true, NULL),
('dwhike|945|Burnthouse Branch Falls', 945, 'dwhike', true, NULL);

INSERT INTO claims (group_id, feature_id, field, value)
SELECT g.id, g.feature_id, v.field, v.value::jsonb
FROM (VALUES
('dwhike|400|Setrock Creek Falls', 'coordinate', '{"lat": 35.74977, "lon": -82.22818}'),
('dwhike|400|Setrock Creek Falls', 'name', '"Setrock Creek Falls"'),
('dwhike|399|Roaring Fork Falls', 'coordinate', '{"lat": 35.75998, "lon": -82.19167}'),
('dwhike|399|Roaring Fork Falls', 'name', '"Roaring Fork Falls"'),
('dwhike|363|High Shoals Falls', 'coordinate', '{"lat": 35.59448, "lon": -81.63553}'),
('dwhike|363|High Shoals Falls', 'name', '"High Shoals Falls"'),
('dwhike|398|<![CDATA[Tom''s Creek Falls]]>', 'coordinate', '{"lat": 35.77757, "lon": -82.0622}'),
('dwhike|398|<![CDATA[Tom''s Creek Falls]]>', 'name', '"<![CDATA[Tom''s Creek Falls]]>"'),
('dwhike|396|Crabtree Falls', 'coordinate', '{"lat": 35.819672, "lon": -82.149582}'),
('dwhike|396|Crabtree Falls', 'name', '"Crabtree Falls"'),
('dwhike|387|Hunt-Fish Falls', 'coordinate', '{"lat": 36.013976, "lon": -81.804286}'),
('dwhike|387|Hunt-Fish Falls', 'name', '"Hunt-Fish Falls"'),
('dwhike|376|Hebron Colony Falls', 'coordinate', '{"lat": 36.154511, "lon": -81.734414}'),
('dwhike|376|Hebron Colony Falls', 'name', '"Hebron Colony Falls"'),
('dwhike|386|Upper Creek Falls', 'coordinate', '{"lat": 35.960518, "lon": -81.86339}'),
('dwhike|386|Upper Creek Falls', 'name', '"Upper Creek Falls"'),
('dwhike|378|Looking Glass Falls', 'coordinate', '{"lat": 35.2962, "lon": -82.76887}'),
('dwhike|378|Looking Glass Falls', 'name', '"Looking Glass Falls"'),
('dwhike|350|Second Falls', 'coordinate', '{"lat": 35.32228, "lon": -82.84671}'),
('dwhike|350|Second Falls', 'name', '"Second Falls"'),
('dwhike|359|Drift Falls', 'coordinate', '{"lat": 35.093523, "lon": -82.969262}'),
('dwhike|359|Drift Falls', 'name', '"Drift Falls"'),
('dwhike|334|Turtleback Falls', 'coordinate', '{"lat": 35.09256, "lon": -82.9662}'),
('dwhike|334|Turtleback Falls', 'name', '"Turtleback Falls"'),
('dwhike|407|Courthouse Falls', 'coordinate', '{"lat": 35.27157, "lon": -82.89431}'),
('dwhike|407|Courthouse Falls', 'name', '"Courthouse Falls"'),
('dwhike|321|Eastatoe Falls', 'coordinate', '{"lat": 35.111602, "lon": -82.817506}'),
('dwhike|321|Eastatoe Falls', 'name', '"Eastatoe Falls"'),
('dwhike|380|Moore Cove Falls', 'coordinate', '{"lat": 35.31181, "lon": -82.77776}'),
('dwhike|380|Moore Cove Falls', 'name', '"Moore Cove Falls"'),
('dwhike|353|Triple Falls', 'coordinate', '{"lat": 35.19897, "lon": -82.61705}'),
('dwhike|353|Triple Falls', 'name', '"Triple Falls"'),
('dwhike|384|High Falls (Little River)', 'coordinate', '{"lat": 35.19282, "lon": -82.61361}'),
('dwhike|384|High Falls (Little River)', 'name', '"High Falls (Little River)"'),
('dwhike|412|Wash Hollow Falls', 'coordinate', '{"lat": 35.3418, "lon": -82.89762}'),
('dwhike|412|Wash Hollow Falls', 'name', '"Wash Hollow Falls"'),
('dwhike|327|Rufus Morgan Falls', 'coordinate', '{"lat": 35.14273, "lon": -83.54792}'),
('dwhike|327|Rufus Morgan Falls', 'name', '"Rufus Morgan Falls"'),
('dwhike|360|Dry Falls', 'coordinate', '{"lat": 35.067466, "lon": -83.2390738}'),
('dwhike|360|Dry Falls', 'name', '"Dry Falls"'),
('dwhike|323|Silver Run Falls', 'coordinate', '{"lat": 35.06617, "lon": -83.06542}'),
('dwhike|323|Silver Run Falls', 'name', '"Silver Run Falls"'),
('dwhike|403|Issaqueena Falls', 'coordinate', '{"lat": 34.80684, "lon": -83.121462}'),
('dwhike|403|Issaqueena Falls', 'name', '"Issaqueena Falls"'),
('dwhike|371|Spoonauger Falls', 'coordinate', '{"lat": 34.97461, "lon": -83.109685}'),
('dwhike|371|Spoonauger Falls', 'name', '"Spoonauger Falls"'),
('dwhike|395|Linville Falls', 'coordinate', '{"lat": 35.94967, "lon": -81.92657}'),
('dwhike|395|Linville Falls', 'name', '"Linville Falls"'),
('dwhike|364|Bird Rock Falls', 'coordinate', '{"lat": 35.221175, "lon": -82.861245}'),
('dwhike|364|Bird Rock Falls', 'name', '"Bird Rock Falls"'),
('dwhike|1101|Long Branch Falls', 'coordinate', '{"lat": 35.27892, "lon": -82.82491}'),
('dwhike|1101|Long Branch Falls', 'name', '"Long Branch Falls"'),
('dwhike|391|Schoolhouse Falls', 'coordinate', '{"lat": 35.16308, "lon": -83.00665}'),
('dwhike|391|Schoolhouse Falls', 'name', '"Schoolhouse Falls"'),
('dwhike|324|Mingo Falls', 'coordinate', '{"lat": 35.53182, "lon": -83.27512}'),
('dwhike|324|Mingo Falls', 'name', '"Mingo Falls"'),
('dwhike|325|Soco Falls', 'coordinate', '{"lat": 35.49246, "lon": -83.16953}'),
('dwhike|325|Soco Falls', 'name', '"Soco Falls"'),
('dwhike|318|White Owl Falls', 'coordinate', '{"lat": 35.07649, "lon": -82.99714}'),
('dwhike|318|White Owl Falls', 'name', '"White Owl Falls"'),
('dwhike|333|Stairway Falls', 'coordinate', '{"lat": 35.085548, "lon": -82.956244}'),
('dwhike|333|Stairway Falls', 'name', '"Stairway Falls"'),
('dwhike|394|Whitewater Falls', 'coordinate', '{"lat": 35.035088, "lon": -83.016827}'),
('dwhike|394|Whitewater Falls', 'name', '"Whitewater Falls"'),
('dwhike|406|Twin Falls, SC', 'coordinate', '{"lat": 35.013675, "lon": -82.818387}'),
('dwhike|406|Twin Falls, SC', 'name', '"Twin Falls, SC"'),
('dwhike|401|Douglas Falls', 'coordinate', '{"lat": 35.721013, "lon": -82.374236}'),
('dwhike|401|Douglas Falls', 'name', '"Douglas Falls"'),
('dwhike|410|Little Bradley Falls', 'coordinate', '{"lat": 35.254479, "lon": -82.295146}'),
('dwhike|410|Little Bradley Falls', 'name', '"Little Bradley Falls"'),
('dwhike|496|Upper Courthouse Falls', 'coordinate', '{"lat": 35.29197, "lon": -82.90373}'),
('dwhike|496|Upper Courthouse Falls', 'name', '"Upper Courthouse Falls"'),
('dwhike|343|Hickory Nut Falls', 'coordinate', '{"lat": 35.43323, "lon": -82.25948}'),
('dwhike|343|Hickory Nut Falls', 'name', '"Hickory Nut Falls"'),
('dwhike|347|Yellow Branch Falls', 'coordinate', '{"lat": 34.79505, "lon": -83.134367}'),
('dwhike|347|Yellow Branch Falls', 'name', '"Yellow Branch Falls"'),
('dwhike|336|Lee Falls', 'coordinate', '{"lat": 34.895677, "lon": -83.101303}'),
('dwhike|336|Lee Falls', 'name', '"Lee Falls"'),
('dwhike|404|Station Cove Falls', 'coordinate', '{"lat": 34.849467, "lon": -83.085608}'),
('dwhike|404|Station Cove Falls', 'name', '"Station Cove Falls"'),
('dwhike|357|Moonshine Falls', 'coordinate', '{"lat": 35.094581, "lon": -82.631354}'),
('dwhike|357|Moonshine Falls', 'name', '"Moonshine Falls"'),
('dwhike|337|Brasstown Falls', 'coordinate', '{"lat": 34.718869, "lon": -83.304426}'),
('dwhike|337|Brasstown Falls', 'name', '"Brasstown Falls"'),
('dwhike|312|Long Creek Falls', 'coordinate', '{"lat": 34.785621, "lon": -83.322563}'),
('dwhike|312|Long Creek Falls', 'name', '"Long Creek Falls"'),
('dwhike|335|Opossum Creek Falls', 'coordinate', '{"lat": 34.757566, "lon": -83.314413}'),
('dwhike|335|Opossum Creek Falls', 'name', '"Opossum Creek Falls"'),
('dwhike|373|Little Fall Branch Falls', 'coordinate', '{"lat": 35.75514, "lon": -82.97633}'),
('dwhike|373|Little Fall Branch Falls', 'name', '"Little Fall Branch Falls"'),
('dwhike|344|Greenland Creek Falls', 'coordinate', '{"lat": 35.150836, "lon": -82.998131}'),
('dwhike|344|Greenland Creek Falls', 'name', '"Greenland Creek Falls"'),
('dwhike|351|High Falls (South Fork Mills River)', 'coordinate', '{"lat": 35.34926, "lon": -82.73215}'),
('dwhike|351|High Falls (South Fork Mills River)', 'name', '"High Falls (South Fork Mills River)"'),
('dwhike|397|Mouse Creek Falls', 'coordinate', '{"lat": 35.73507, "lon": -83.13356}'),
('dwhike|397|Mouse Creek Falls', 'name', '"Mouse Creek Falls"'),
('dwhike|570|Lower Catawba Falls', 'coordinate', '{"lat": 35.604374, "lon": -82.244917}'),
('dwhike|570|Lower Catawba Falls', 'name', '"Lower Catawba Falls"'),
('dwhike|821|Upper Catawba Falls', 'coordinate', '{"lat": 35.601921, "lon": -82.247484}'),
('dwhike|821|Upper Catawba Falls', 'name', '"Upper Catawba Falls"'),
('dwhike|313|Cove Creek Falls', 'coordinate', '{"lat": 35.294006, "lon": -82.817483}'),
('dwhike|313|Cove Creek Falls', 'name', '"Cove Creek Falls"'),
('dwhike|390|Grotto Falls', 'coordinate', '{"lat": 35.673823, "lon": -83.449581}'),
('dwhike|390|Grotto Falls', 'name', '"Grotto Falls"'),
('dwhike|341|Shuck Ridge Creek Falls', 'coordinate', '{"lat": 35.29555, "lon": -82.86156}'),
('dwhike|341|Shuck Ridge Creek Falls', 'name', '"Shuck Ridge Creek Falls"'),
('dwhike|414|Dismal Falls', 'coordinate', '{"lat": 35.1802, "lon": -82.97418}'),
('dwhike|414|Dismal Falls', 'name', '"Dismal Falls"'),
('dwhike|310|Rhapsodie Falls', 'coordinate', '{"lat": 35.183498, "lon": -82.975155}'),
('dwhike|310|Rhapsodie Falls', 'name', '"Rhapsodie Falls"'),
('dwhike|349|Dill Falls', 'coordinate', '{"lat": 35.28328, "lon": -82.9436}'),
('dwhike|349|Dill Falls', 'name', '"Dill Falls"'),
('dwhike|503|Upper Dill Falls', 'coordinate', '{"lat": 35.28402, "lon": -82.94332}'),
('dwhike|503|Upper Dill Falls', 'name', '"Upper Dill Falls"'),
('dwhike|537|Big Bradley Falls', 'coordinate', '{"lat": 35.267891, "lon": -82.291779}'),
('dwhike|537|Big Bradley Falls', 'name', '"Big Bradley Falls"'),
('dwhike|392|Flat Creek Falls', 'coordinate', '{"lat": 35.22039, "lon": -83.03287}'),
('dwhike|392|Flat Creek Falls', 'name', '"Flat Creek Falls"'),
('dwhike|326|Big Laurel Falls', 'coordinate', '{"lat": 35.018188, "lon": -83.505878}'),
('dwhike|326|Big Laurel Falls', 'name', '"Big Laurel Falls"'),
('dwhike|358|Enloe Creek Falls', 'coordinate', '{"lat": 35.61128, "lon": -83.2612}'),
('dwhike|358|Enloe Creek Falls', 'name', '"Enloe Creek Falls"'),
('dwhike|320|Big Falls (Thompson River)', 'coordinate', '{"lat": 35.04495, "lon": -82.982145}'),
('dwhike|320|Big Falls (Thompson River)', 'name', '"Big Falls (Thompson River)"'),
('dwhike|362|High Falls (Thompson River)', 'coordinate', '{"lat": 35.0703, "lon": -82.99432}'),
('dwhike|362|High Falls (Thompson River)', 'name', '"High Falls (Thompson River)"'),
('dwhike|367|Harper Creek Falls', 'coordinate', '{"lat": 35.983059, "lon": -81.779544}'),
('dwhike|367|Harper Creek Falls', 'name', '"Harper Creek Falls"'),
('dwhike|782|Upper Little Lost Cove Falls', 'coordinate', '{"lat": 36.021649, "lon": -81.829518}'),
('dwhike|782|Upper Little Lost Cove Falls', 'name', '"Upper Little Lost Cove Falls"'),
('dwhike|355|North Harper Creek Falls', 'coordinate', '{"lat": 36.00423, "lon": -81.84013}'),
('dwhike|355|North Harper Creek Falls', 'name', '"North Harper Creek Falls"'),
('dwhike|788|Upper Gragg Prong Falls', 'coordinate', '{"lat": 36.0253, "lon": -81.797382}'),
('dwhike|788|Upper Gragg Prong Falls', 'name', '"Upper Gragg Prong Falls"'),
('dwhike|374|South Harper Creek Falls', 'coordinate', '{"lat": 35.98062, "lon": -81.81048}'),
('dwhike|374|South Harper Creek Falls', 'name', '"South Harper Creek Falls"'),
('dwhike|501|Discovery Falls', 'coordinate', '{"lat": 35.32744, "lon": -82.80904}'),
('dwhike|501|Discovery Falls', 'name', '"Discovery Falls"'),
('dwhike|385|Logging Road Falls', 'coordinate', '{"lat": 35.32121, "lon": -82.81118}'),
('dwhike|385|Logging Road Falls', 'name', '"Logging Road Falls"'),
('dwhike|348|Middle Falls (Snowbird Creek)', 'coordinate', '{"lat": 35.26225, "lon": -83.9817}'),
('dwhike|348|Middle Falls (Snowbird Creek)', 'name', '"Middle Falls (Snowbird Creek)"'),
('dwhike|945|Burnthouse Branch Falls', 'coordinate', '{"lat": 35.951276, "lon": -81.822267}'),
('dwhike|945|Burnthouse Branch Falls', 'name', '"Burnthouse Branch Falls"')
) AS v(ref, field, value)
JOIN claim_groups g ON g.ref = v.ref;
-- no feature matched the placemark "Elk Falls"
-- no feature matched the placemark "Upper Falls (Yellowstone Prong)"
-- no feature matched the placemark "<![CDATA[Cathey's Creek Falls]]>"
-- no feature matched the placemark "Skinny Dip Falls"
-- no feature matched the placemark "Lower Sam Branch Falls"
-- no feature matched the placemark "King Creek Falls"
-- no feature matched the placemark "Glenn Falls"
-- no feature matched the placemark "Picklesimer Rock House Falls"
-- no feature matched the placemark "Cedar Rock Creek Falls"
-- no feature matched the placemark "D.E.W. Falls"
-- no feature matched the placemark "Pearsons Falls"
-- no feature matched the placemark "Rainbow Falls, SC"
-- no feature matched the placemark "Eastatoe Gorge Narrows"
-- no feature matched the placemark "Scotsman Creek Falls"
-- no feature matched the placemark "Bridal Veil Falls"
-- no feature matched the placemark "Twin Falls, NC"
-- no feature matched the placemark "Rileymoore Falls"
-- no feature matched the placemark "Paradise Falls"
-- no feature matched the placemark "<![CDATA[Upper Sol's Creek Falls]]>"
-- no feature matched the placemark "Still House Falls"
-- no feature matched the placemark "Ramsay Cascades"
-- no feature matched the placemark "<![CDATA[Tom's Spring (Daniel Ridge) Falls]]>"
-- no feature matched the placemark "Lower Little Lost Cove Falls"
-- no feature matched the placemark "Rainbow Falls, TN"
-- no feature matched the placemark "<![CDATA[Steel's Creeek Falls]]>"
-- no feature matched the placemark "Hilliard (Bearcamp) Falls"
-- placemark "Indian Creek Falls" matched 2 features, left alone
-- placemark "Rainbow Falls" matched 5 features, left alone
-- placemark "Secret Falls" matched 3 features, left alone
-- placemark "Raven Cliff Falls" matched 2 features, left alone
-- placemark "Wintergreen Falls" matched 2 features, left alone
-- placemark "Long Branch Falls" is 21.5 km from our "Long Branch Falls (Mills River)"; claimed, but flagged in its note
-- placemark "Yellow Branch Falls" is 62.1 km from our "Yellow Branch Falls"; claimed, but flagged in its note
-- placemark "Lee Falls" is 50.4 km from our "Lee Falls"; claimed, but flagged in its note
-- placemark "Station Cove Falls" is 50.1 km from our "Station Cove Falls"; claimed, but flagged in its note
-- placemark "Long Creek Falls" is 62.0 km from our "Long Creek Falls"; claimed, but flagged in its note
-- placemark "North Harper Creek Falls" is 22.8 km from our "North Harper Creek Falls"; claimed, but flagged in its note

UPDATE claims c SET accepted = true
FROM claim_groups cg, features f JOIN locations l ON l.id = f.feature_location_id
WHERE c.group_id = cg.id AND c.feature_id = f.id
  AND cg.source = 'dwhike' AND c.field = 'coordinate'
  AND round(l.latitude, 5) = round((c.value->>'lat')::numeric, 5)
  AND round(l.longitude, 5) = round((c.value->>'lon')::numeric, 5)
  AND NOT EXISTS (SELECT 1 FROM claims a
                  WHERE a.feature_id = c.feature_id AND a.field = c.field AND a.accepted);

COMMIT;
