-- Where the WC100 coordinates came from: data/dwhike.kml.
--
-- Generated by script/backfill_claims/kml.py. A dozen falls carry a point
-- hikingwnc never published, and this is it. Matched by name, and only where
-- the name picks out exactly one feature.

BEGIN;

INSERT INTO claims (feature_id, field, value, source, note) VALUES
(400, 'coordinate', '{"lat": 35.74977, "lon": -82.22818}', 'cmc-kml', NULL),
(399, 'coordinate', '{"lat": 35.75998, "lon": -82.19167}', 'cmc-kml', NULL),
(363, 'coordinate', '{"lat": 35.59448, "lon": -81.63553}', 'cmc-kml', NULL),
(398, 'coordinate', '{"lat": 35.77757, "lon": -82.0622}', 'cmc-kml', NULL),
(396, 'coordinate', '{"lat": 35.819672, "lon": -82.149582}', 'cmc-kml', NULL),
(387, 'coordinate', '{"lat": 36.013976, "lon": -81.804286}', 'cmc-kml', NULL),
(376, 'coordinate', '{"lat": 36.154511, "lon": -81.734414}', 'cmc-kml', NULL),
(386, 'coordinate', '{"lat": 35.960518, "lon": -81.86339}', 'cmc-kml', NULL),
(378, 'coordinate', '{"lat": 35.2962, "lon": -82.76887}', 'cmc-kml', NULL),
(350, 'coordinate', '{"lat": 35.32228, "lon": -82.84671}', 'cmc-kml', NULL),
(359, 'coordinate', '{"lat": 35.093523, "lon": -82.969262}', 'cmc-kml', NULL),
(334, 'coordinate', '{"lat": 35.09256, "lon": -82.9662}', 'cmc-kml', NULL),
(407, 'coordinate', '{"lat": 35.27157, "lon": -82.89431}', 'cmc-kml', NULL),
(321, 'coordinate', '{"lat": 35.111602, "lon": -82.817506}', 'cmc-kml', NULL),
(380, 'coordinate', '{"lat": 35.31181, "lon": -82.77776}', 'cmc-kml', NULL),
(353, 'coordinate', '{"lat": 35.19897, "lon": -82.61705}', 'cmc-kml', NULL),
(384, 'coordinate', '{"lat": 35.19282, "lon": -82.61361}', 'cmc-kml', NULL),
(412, 'coordinate', '{"lat": 35.3418, "lon": -82.89762}', 'cmc-kml', NULL),
(327, 'coordinate', '{"lat": 35.14273, "lon": -83.54792}', 'cmc-kml', NULL),
(360, 'coordinate', '{"lat": 35.067466, "lon": -83.2390738}', 'cmc-kml', NULL),
(323, 'coordinate', '{"lat": 35.06617, "lon": -83.06542}', 'cmc-kml', NULL),
(403, 'coordinate', '{"lat": 34.80684, "lon": -83.121462}', 'cmc-kml', NULL),
(371, 'coordinate', '{"lat": 34.97461, "lon": -83.109685}', 'cmc-kml', NULL),
(395, 'coordinate', '{"lat": 35.94967, "lon": -81.92657}', 'cmc-kml', NULL),
(364, 'coordinate', '{"lat": 35.221175, "lon": -82.861245}', 'cmc-kml', NULL),
(1101, 'coordinate', '{"lat": 35.27892, "lon": -82.82491}', 'cmc-kml', 'Matched to this feature by name alone. The placemark is 21.5 km from where we have it, so it may be a different fall of the same name.'),
(391, 'coordinate', '{"lat": 35.16308, "lon": -83.00665}', 'cmc-kml', NULL),
(324, 'coordinate', '{"lat": 35.53182, "lon": -83.27512}', 'cmc-kml', NULL),
(325, 'coordinate', '{"lat": 35.49246, "lon": -83.16953}', 'cmc-kml', NULL),
(318, 'coordinate', '{"lat": 35.07649, "lon": -82.99714}', 'cmc-kml', NULL),
(333, 'coordinate', '{"lat": 35.085548, "lon": -82.956244}', 'cmc-kml', NULL),
(394, 'coordinate', '{"lat": 35.035088, "lon": -83.016827}', 'cmc-kml', NULL),
(406, 'coordinate', '{"lat": 35.013675, "lon": -82.818387}', 'cmc-kml', NULL),
(401, 'coordinate', '{"lat": 35.721013, "lon": -82.374236}', 'cmc-kml', NULL),
(410, 'coordinate', '{"lat": 35.254479, "lon": -82.295146}', 'cmc-kml', NULL),
(496, 'coordinate', '{"lat": 35.29197, "lon": -82.90373}', 'cmc-kml', NULL),
(343, 'coordinate', '{"lat": 35.43323, "lon": -82.25948}', 'cmc-kml', NULL),
(347, 'coordinate', '{"lat": 34.79505, "lon": -83.134367}', 'cmc-kml', 'Matched to this feature by name alone. The placemark is 62.1 km from where we have it, so it may be a different fall of the same name.'),
(336, 'coordinate', '{"lat": 34.895677, "lon": -83.101303}', 'cmc-kml', 'Matched to this feature by name alone. The placemark is 50.4 km from where we have it, so it may be a different fall of the same name.'),
(404, 'coordinate', '{"lat": 34.849467, "lon": -83.085608}', 'cmc-kml', 'Matched to this feature by name alone. The placemark is 50.1 km from where we have it, so it may be a different fall of the same name.'),
(357, 'coordinate', '{"lat": 35.094581, "lon": -82.631354}', 'cmc-kml', NULL),
(337, 'coordinate', '{"lat": 34.718869, "lon": -83.304426}', 'cmc-kml', NULL),
(312, 'coordinate', '{"lat": 34.785621, "lon": -83.322563}', 'cmc-kml', 'Matched to this feature by name alone. The placemark is 62.0 km from where we have it, so it may be a different fall of the same name.'),
(335, 'coordinate', '{"lat": 34.757566, "lon": -83.314413}', 'cmc-kml', NULL),
(373, 'coordinate', '{"lat": 35.75514, "lon": -82.97633}', 'cmc-kml', NULL),
(344, 'coordinate', '{"lat": 35.150836, "lon": -82.998131}', 'cmc-kml', NULL),
(351, 'coordinate', '{"lat": 35.34926, "lon": -82.73215}', 'cmc-kml', NULL),
(397, 'coordinate', '{"lat": 35.73507, "lon": -83.13356}', 'cmc-kml', NULL),
(570, 'coordinate', '{"lat": 35.604374, "lon": -82.244917}', 'cmc-kml', NULL),
(821, 'coordinate', '{"lat": 35.601921, "lon": -82.247484}', 'cmc-kml', NULL),
(313, 'coordinate', '{"lat": 35.294006, "lon": -82.817483}', 'cmc-kml', NULL),
(390, 'coordinate', '{"lat": 35.673823, "lon": -83.449581}', 'cmc-kml', NULL),
(341, 'coordinate', '{"lat": 35.29555, "lon": -82.86156}', 'cmc-kml', NULL),
(414, 'coordinate', '{"lat": 35.1802, "lon": -82.97418}', 'cmc-kml', NULL),
(310, 'coordinate', '{"lat": 35.183498, "lon": -82.975155}', 'cmc-kml', NULL),
(349, 'coordinate', '{"lat": 35.28328, "lon": -82.9436}', 'cmc-kml', NULL),
(503, 'coordinate', '{"lat": 35.28402, "lon": -82.94332}', 'cmc-kml', NULL),
(537, 'coordinate', '{"lat": 35.267891, "lon": -82.291779}', 'cmc-kml', NULL),
(392, 'coordinate', '{"lat": 35.22039, "lon": -83.03287}', 'cmc-kml', NULL),
(326, 'coordinate', '{"lat": 35.018188, "lon": -83.505878}', 'cmc-kml', NULL),
(358, 'coordinate', '{"lat": 35.61128, "lon": -83.2612}', 'cmc-kml', NULL),
(320, 'coordinate', '{"lat": 35.04495, "lon": -82.982145}', 'cmc-kml', NULL),
(362, 'coordinate', '{"lat": 35.0703, "lon": -82.99432}', 'cmc-kml', NULL),
(367, 'coordinate', '{"lat": 35.983059, "lon": -81.779544}', 'cmc-kml', NULL),
(782, 'coordinate', '{"lat": 36.021649, "lon": -81.829518}', 'cmc-kml', NULL),
(355, 'coordinate', '{"lat": 36.00423, "lon": -81.84013}', 'cmc-kml', 'Matched to this feature by name alone. The placemark is 22.8 km from where we have it, so it may be a different fall of the same name.'),
(788, 'coordinate', '{"lat": 36.0253, "lon": -81.797382}', 'cmc-kml', NULL),
(374, 'coordinate', '{"lat": 35.98062, "lon": -81.81048}', 'cmc-kml', NULL),
(501, 'coordinate', '{"lat": 35.32744, "lon": -82.80904}', 'cmc-kml', NULL),
(385, 'coordinate', '{"lat": 35.32121, "lon": -82.81118}', 'cmc-kml', NULL),
(348, 'coordinate', '{"lat": 35.26225, "lon": -83.9817}', 'cmc-kml', NULL),
(945, 'coordinate', '{"lat": 35.951276, "lon": -81.822267}', 'cmc-kml', NULL);
-- no feature matched the placemark "Elk Falls"
-- no feature matched the placemark "Upper Falls (Yellowstone Prong)"
-- no feature matched the placemark "<![CDATA[Cathey's Creek Falls]]>"
-- no feature matched the placemark "Skinny Dip Falls"
-- no feature matched the placemark "Lower Sam Branch Falls"
-- no feature matched the placemark "King Creek Falls"
-- no feature matched the placemark "Glenn Falls"
-- no feature matched the placemark "Picklesimer Rock House Falls"
-- no feature matched the placemark "Cedar Rock Creek Falls"
-- no feature matched the placemark "D.E.W. Falls"
-- no feature matched the placemark "Pearsons Falls"
-- no feature matched the placemark "Rainbow Falls, SC"
-- no feature matched the placemark "Eastatoe Gorge Narrows"
-- no feature matched the placemark "Scotsman Creek Falls"
-- no feature matched the placemark "Bridal Veil Falls"
-- no feature matched the placemark "Twin Falls, NC"
-- no feature matched the placemark "Rileymoore Falls"
-- no feature matched the placemark "Paradise Falls"
-- no feature matched the placemark "<![CDATA[Upper Sol's Creek Falls]]>"
-- no feature matched the placemark "Still House Falls"
-- no feature matched the placemark "Ramsay Cascades"
-- no feature matched the placemark "<![CDATA[Tom's Spring (Daniel Ridge) Falls]]>"
-- no feature matched the placemark "Lower Little Lost Cove Falls"
-- no feature matched the placemark "Rainbow Falls, TN"
-- no feature matched the placemark "<![CDATA[Steel's Creeek Falls]]>"
-- no feature matched the placemark "Hilliard (Bearcamp) Falls"
-- placemark "Indian Creek Falls" matched 2 features, left alone
-- placemark "Rainbow Falls" matched 5 features, left alone
-- placemark "Secret Falls" matched 3 features, left alone
-- placemark "Raven Cliff Falls" matched 2 features, left alone
-- placemark "Wintergreen Falls" matched 2 features, left alone
-- placemark "Long Branch Falls" is 21.5 km from our "Long Branch Falls (Mills River)"; claimed, but flagged in its note
-- placemark "Yellow Branch Falls" is 62.1 km from our "Yellow Branch Falls"; claimed, but flagged in its note
-- placemark "Lee Falls" is 50.4 km from our "Lee Falls"; claimed, but flagged in its note
-- placemark "Station Cove Falls" is 50.1 km from our "Station Cove Falls"; claimed, but flagged in its note
-- placemark "Long Creek Falls" is 62.0 km from our "Long Creek Falls"; claimed, but flagged in its note
-- placemark "North Harper Creek Falls" is 22.8 km from our "North Harper Creek Falls"; claimed, but flagged in its note

UPDATE claims c SET accepted = true
FROM features f JOIN locations l ON l.id = f.feature_location_id
WHERE c.feature_id = f.id AND c.source = 'cmc-kml' AND c.field = 'coordinate'
  AND round(l.latitude, 5) = round((c.value->>'lat')::numeric, 5)
  AND round(l.longitude, 5) = round((c.value->>'lon')::numeric, 5)
  AND NOT EXISTS (SELECT 1 FROM claims a
                  WHERE a.feature_id = c.feature_id AND a.field = c.field AND a.accepted);

COMMIT;
