-- Where you stand to see the big ones, from OpenStreetMap.
--
-- Generated by script/import/claims/viewpoints.py. Whitewater Falls has a
-- viewing platform 307 m from the water and an overlook at 340 m, which is the
-- whole point of this field: at the base of a 411 foot fall you see spray and
-- rock.
--
-- Data (c) OpenStreetMap contributors, made available under the ODbL.

BEGIN;

INSERT INTO claim_groups (ref, feature_id, source, url, identity_certain, note) VALUES
('openstreetmap|1253|viewpoint/347687418', 1253, 'openstreetmap', 'https://www.openstreetmap.org/node/347687418', false, '74 m from the fall, but OpenStreetMap calls it Waterfall view, which names something else.'),
('openstreetmap|394|viewpoint/1226186065', 394, 'openstreetmap', 'https://www.openstreetmap.org/node/1226186065', true, 'Named for the fall it looks at.'),
('openstreetmap|372|viewpoint/1541376573', 372, 'openstreetmap', 'https://www.openstreetmap.org/node/1541376573', true, 'Named for the fall it looks at.'),
('openstreetmap|394|viewpoint/2630699407', 394, 'openstreetmap', 'https://www.openstreetmap.org/node/2630699407', true, 'Named for the fall it looks at.'),
('openstreetmap|515|viewpoint/2630720712', 515, 'openstreetmap', 'https://www.openstreetmap.org/node/2630720712', true, 'Named for the fall it looks at.'),
('openstreetmap|371|viewpoint/2717284984', 371, 'openstreetmap', 'https://www.openstreetmap.org/node/2717284984', true, 'Named for the fall it looks at.'),
('openstreetmap|350|viewpoint/2727292831', 350, 'openstreetmap', 'https://www.openstreetmap.org/node/2727292831', false, '424 m from the fall, but OpenStreetMap calls it None, which names something else.'),
('openstreetmap|360|viewpoint/2738692020', 360, 'openstreetmap', 'https://www.openstreetmap.org/node/2738692020', true, 'Named for the fall it looks at.'),
('openstreetmap|325|viewpoint/2744073357', 325, 'openstreetmap', 'https://www.openstreetmap.org/node/2744073357', false, '173 m from the fall, but OpenStreetMap calls it None, which names something else.'),
('openstreetmap|406|viewpoint/3216791809', 406, 'openstreetmap', 'https://www.openstreetmap.org/node/3216791809', true, 'Unnamed and 51 m away, with nothing else to look at.'),
('openstreetmap|359|viewpoint/5055047414', 359, 'openstreetmap', 'https://www.openstreetmap.org/node/5055047414', true, 'Unnamed and 71 m away, with nothing else to look at.'),
('openstreetmap|1238|viewpoint/5249456065', 1238, 'openstreetmap', 'https://www.openstreetmap.org/node/5249456065', false, '481 m from the fall, but OpenStreetMap calls it Purdy Point, which names something else.'),
('openstreetmap|331|viewpoint/5274410691', 331, 'openstreetmap', 'https://www.openstreetmap.org/node/5274410691', true, 'Unnamed and 76 m away, with nothing else to look at.'),
('openstreetmap|331|viewpoint/5274411835', 331, 'openstreetmap', 'https://www.openstreetmap.org/node/5274411835', true, 'Unnamed and 23 m away, with nothing else to look at.'),
('openstreetmap|331|viewpoint/5274411864', 331, 'openstreetmap', 'https://www.openstreetmap.org/node/5274411864', true, 'Named for the fall it looks at.'),
('openstreetmap|403|viewpoint/5523826917', 403, 'openstreetmap', 'https://www.openstreetmap.org/node/5523826917', true, 'Unnamed and 75 m away, with nothing else to look at.'),
('openstreetmap|828|viewpoint/5623023851', 828, 'openstreetmap', 'https://www.openstreetmap.org/node/5623023851', false, '0 m from the fall, but OpenStreetMap calls it Mount Lynn Lowry Overlook, which names something else.'),
('openstreetmap|1253|viewpoint/5877079994', 1253, 'openstreetmap', 'https://www.openstreetmap.org/node/5877079994', false, '104 m from the fall, but OpenStreetMap calls it Waterfall view, which names something else.'),
('openstreetmap|1006|viewpoint/6245894649', 1006, 'openstreetmap', 'https://www.openstreetmap.org/node/6245894649', false, '147 m from the fall, but OpenStreetMap calls it None, which names something else.'),
('openstreetmap|384|viewpoint/7372171356', 384, 'openstreetmap', 'https://www.openstreetmap.org/node/7372171356', true, 'Named for the fall it looks at.'),
('openstreetmap|331|viewpoint/8746041202', 331, 'openstreetmap', 'https://www.openstreetmap.org/node/8746041202', false, '206 m from the fall, but OpenStreetMap calls it None, which names something else.'),
('openstreetmap|777|viewpoint/9179026804', 777, 'openstreetmap', 'https://www.openstreetmap.org/node/9179026804', false, '440 m from the fall, but OpenStreetMap calls it None, which names something else.'),
('openstreetmap|350|viewpoint/10005318009', 350, 'openstreetmap', 'https://www.openstreetmap.org/node/10005318009', false, '176 m from the fall, but OpenStreetMap calls it East Fork Overlook, which names something else.'),
('openstreetmap|325|viewpoint/10195139649', 325, 'openstreetmap', 'https://www.openstreetmap.org/node/10195139649', true, 'Unnamed and 44 m away, with nothing else to look at.'),
('openstreetmap|325|viewpoint/10195139650', 325, 'openstreetmap', 'https://www.openstreetmap.org/node/10195139650', true, 'Unnamed and 36 m away, with nothing else to look at.'),
('openstreetmap|389|viewpoint/11773536326', 389, 'openstreetmap', 'https://www.openstreetmap.org/node/11773536326', true, 'Named for the fall it looks at.'),
('openstreetmap|505|viewpoint/11997963203', 505, 'openstreetmap', 'https://www.openstreetmap.org/node/11997963203', true, 'Unnamed and 89 m away, with nothing else to look at.'),
('openstreetmap|974|viewpoint/12303059021', 974, 'openstreetmap', 'https://www.openstreetmap.org/node/12303059021', false, '481 m from the fall, but OpenStreetMap calls it None, which names something else.'),
('openstreetmap|535|viewpoint/13772777396', 535, 'openstreetmap', 'https://www.openstreetmap.org/node/13772777396', true, 'Unnamed and 53 m away, with nothing else to look at.'),
('openstreetmap|758|viewpoint/14131325014', 758, 'openstreetmap', 'https://www.openstreetmap.org/node/14131325014', true, 'Unnamed and 15 m away, with nothing else to look at.'),
('openstreetmap|758|viewpoint/14131367504', 758, 'openstreetmap', 'https://www.openstreetmap.org/node/14131367504', false, '492 m from the fall, but OpenStreetMap calls it None, which names something else.');

INSERT INTO claims (group_id, feature_id, field, value, note)
SELECT g.id, g.feature_id, v.field, v.value::jsonb, v.note::text
FROM (VALUES
('openstreetmap|1253|viewpoint/347687418', 'view_coordinate', '{"lat": 34.7636253, "lon": -83.712255}', '74 m from the fall.'),
('openstreetmap|394|viewpoint/1226186065', 'view_coordinate', '{"lat": 35.0332586, "lon": -83.0165845}', '340 m from the fall.'),
('openstreetmap|372|viewpoint/1541376573', 'view_coordinate', '{"lat": 35.1090969, "lon": -82.6582366}', '454 m from the fall.'),
('openstreetmap|394|viewpoint/2630699407', 'view_coordinate', '{"lat": 35.0337555, "lon": -83.0161566}', '307 m from the fall.'),
('openstreetmap|515|viewpoint/2630720712', 'view_coordinate', '{"lat": 35.0137998, "lon": -82.9899752}', '444 m from the fall.'),
('openstreetmap|371|viewpoint/2717284984', 'view_coordinate', '{"lat": 34.9748003, "lon": -83.1100162}', '36 m from the fall.'),
('openstreetmap|350|viewpoint/2727292831', 'view_coordinate', '{"lat": 35.3223257, "lon": -82.8462607}', '424 m from the fall.'),
('openstreetmap|360|viewpoint/2738692020', 'view_coordinate', '{"lat": 35.0688564, "lon": -83.2383671}', '56 m from the fall.'),
('openstreetmap|325|viewpoint/2744073357', 'view_coordinate', '{"lat": 35.4926674, "lon": -83.1676478}', '173 m from the fall.'),
('openstreetmap|406|viewpoint/3216791809', 'view_coordinate', '{"lat": 35.0132686, "lon": -82.8188809}', '51 m from the fall.'),
('openstreetmap|359|viewpoint/5055047414', 'view_coordinate', '{"lat": 35.0937483, "lon": -82.9686528}', '71 m from the fall.'),
('openstreetmap|1238|viewpoint/5249456065', 'view_coordinate', '{"lat": 35.1710984, "lon": -83.024482}', '481 m from the fall.'),
('openstreetmap|331|viewpoint/5274410691', 'view_coordinate', '{"lat": 35.0307048, "lon": -83.2387996}', '76 m from the fall.'),
('openstreetmap|331|viewpoint/5274411835', 'view_coordinate', '{"lat": 35.0314107, "lon": -83.2384534}', '23 m from the fall.'),
('openstreetmap|331|viewpoint/5274411864', 'view_coordinate', '{"lat": 35.0316924, "lon": -83.2381457}', '51 m from the fall.'),
('openstreetmap|403|viewpoint/5523826917', 'view_coordinate', '{"lat": 34.8065343, "lon": -83.1217518}', '75 m from the fall.'),
('openstreetmap|828|viewpoint/5623023851', 'view_coordinate', '{"lat": 35.4421162, "lon": -83.0967725}', '0 m from the fall.'),
('openstreetmap|1253|viewpoint/5877079994', 'view_coordinate', '{"lat": 34.7633614, "lon": -83.712198}', '104 m from the fall.'),
('openstreetmap|1006|viewpoint/6245894649', 'view_coordinate', '{"lat": 35.0316143, "lon": -82.8205355}', '147 m from the fall.'),
('openstreetmap|384|viewpoint/7372171356', 'view_coordinate', '{"lat": 35.1937393, "lon": -82.6149186}', '167 m from the fall.'),
('openstreetmap|331|viewpoint/8746041202', 'view_coordinate', '{"lat": 35.0296386, "lon": -83.2394026}', '206 m from the fall.'),
('openstreetmap|777|viewpoint/9179026804', 'view_coordinate', '{"lat": 35.311332, "lon": -82.92781}', '440 m from the fall.'),
('openstreetmap|350|viewpoint/10005318009', 'view_coordinate', '{"lat": 35.321155, "lon": -82.8400486}', '176 m from the fall.'),
('openstreetmap|325|viewpoint/10195139649', 'view_coordinate', '{"lat": 35.4926239, "lon": -83.1697791}', '44 m from the fall.'),
('openstreetmap|325|viewpoint/10195139650', 'view_coordinate', '{"lat": 35.4926126, "lon": -83.1695964}', '36 m from the fall.'),
('openstreetmap|389|viewpoint/11773536326', 'view_coordinate', '{"lat": 35.0903675, "lon": -82.9649857}', '11 m from the fall.'),
('openstreetmap|505|viewpoint/11997963203', 'view_coordinate', '{"lat": 35.3117796, "lon": -82.7775794}', '89 m from the fall.'),
('openstreetmap|974|viewpoint/12303059021', 'view_coordinate', '{"lat": 35.0901532, "lon": -82.5841232}', '481 m from the fall.'),
('openstreetmap|535|viewpoint/13772777396', 'view_coordinate', '{"lat": 34.9298111, "lon": -83.1307876}', '53 m from the fall.'),
('openstreetmap|758|viewpoint/14131325014', 'view_coordinate', '{"lat": 35.3323592, "lon": -83.5955509}', '15 m from the fall.'),
('openstreetmap|758|viewpoint/14131367504', 'view_coordinate', '{"lat": 35.3335118, "lon": -83.5901704}', '492 m from the fall.')
) AS v(ref, field, value, note)
JOIN claim_groups g ON g.ref = v.ref;

-- Accept the nearest viewpoint we are sure about, one per fall.
CREATE TEMP TABLE chosen ON COMMIT DROP AS
SELECT DISTINCT ON (c.feature_id)
       c.feature_id,
       (c.value->>'lat')::numeric AS lat,
       (c.value->>'lon')::numeric AS lon
FROM claims c
JOIN claim_groups cg ON cg.id = c.group_id
JOIN features f ON f.id = c.feature_id
JOIN locations fl ON fl.id = f.feature_location_id
WHERE c.field = 'view_coordinate' AND cg.identity_certain
ORDER BY c.feature_id,
         sqrt(power(fl.latitude - (c.value->>'lat')::numeric, 2) +
              power((fl.longitude - (c.value->>'lon')::numeric) *
                    cos(radians(fl.latitude)), 2));

INSERT INTO locations (latitude, longitude) SELECT lat, lon FROM chosen;

UPDATE features f SET view_location_id = (
    SELECT l.id FROM locations l
    WHERE l.latitude = c.lat AND l.longitude = c.lon
    ORDER BY l.id DESC LIMIT 1)
FROM chosen c WHERE f.id = c.feature_id;

UPDATE claims c SET accepted = true
FROM features f, locations l
WHERE c.feature_id = f.id AND f.view_location_id = l.id
  AND c.field = 'view_coordinate'
  AND (c.value->>'lat')::numeric = l.latitude
  AND (c.value->>'lon')::numeric = l.longitude;

COMMIT;
