-- A second source for 107 waterfalls.
--
-- Generated by script/import_links/ncwaterfalls.py. Every link is checked
-- against the coordinate Kevin Adams publishes on that page: he covers the
-- whole state and we carry the western end, so the names collide and a name
-- match on its own is a coin flip for a dozen of them.
--
-- Re-runnable. The unique constraint on (feature_id, url) makes a second
-- application a no-op.

BEGIN;

INSERT INTO links (feature_id, url, rel, comments) VALUES
(316, 'https://ncwaterfalls.com/waterfalls/dew-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(318, 'https://ncwaterfalls.com/waterfalls/white-owl-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(322, 'https://ncwaterfalls.com/waterfalls/upper-logging-road-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(323, 'https://ncwaterfalls.com/waterfalls/silver-run-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(324, 'https://ncwaterfalls.com/waterfalls/mingo-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.1 km of our coordinate.'),
(325, 'https://ncwaterfalls.com/waterfalls/soco-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(331, 'https://ncwaterfalls.com/waterfalls/glen-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(338, 'https://ncwaterfalls.com/waterfalls/cody-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.1 km of our coordinate.'),
(339, 'https://ncwaterfalls.com/waterfalls/skinny-dip-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.1 km of our coordinate.'),
(340, 'https://ncwaterfalls.com/waterfalls/catheys-creek-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(343, 'https://ncwaterfalls.com/waterfalls/hickory-nut-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.1 km of our coordinate.'),
(349, 'https://ncwaterfalls.com/waterfalls/dill-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.1 km of our coordinate.'),
(350, 'https://ncwaterfalls.com/waterfalls/second-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.4 km of our coordinate.'),
(353, 'https://ncwaterfalls.com/waterfalls/triple-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.1 km of our coordinate.'),
(359, 'https://ncwaterfalls.com/waterfalls/drift-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(360, 'https://ncwaterfalls.com/waterfalls/dry-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(364, 'https://ncwaterfalls.com/waterfalls/bird-rock-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(377, 'https://ncwaterfalls.com/waterfalls/nameless-waterfall-no-1-on-log-hollow-branch', 'ncwaterfalls', 'Matched by name and confirmed within 0.6 km of our coordinate.'),
(378, 'https://ncwaterfalls.com/waterfalls/looking-glass-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(380, 'https://ncwaterfalls.com/waterfalls/moore-cove-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.2 km of our coordinate.'),
(381, 'https://ncwaterfalls.com/waterfalls/cedar-rock-falls-trib-catheys-creek', 'ncwaterfalls', 'Matched by name; neither side publishes a coordinate to check it against.'),
(384, 'https://ncwaterfalls.com/waterfalls/high-falls-little-river', 'ncwaterfalls', 'Matched by name and confirmed within 0.2 km of our coordinate.'),
(385, 'https://ncwaterfalls.com/waterfalls/logging-road-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.1 km of our coordinate.'),
(393, 'https://ncwaterfalls.com/waterfalls/rainbow-falls-horsepasture-river', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(394, 'https://ncwaterfalls.com/waterfalls/whitewater-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.2 km of our coordinate.'),
(395, 'https://ncwaterfalls.com/waterfalls/linville-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.1 km of our coordinate.'),
(405, 'https://ncwaterfalls.com/waterfalls/catawba-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.1 km of our coordinate.'),
(407, 'https://ncwaterfalls.com/waterfalls/courthouse-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(410, 'https://ncwaterfalls.com/waterfalls/little-bradley-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(417, 'https://ncwaterfalls.com/waterfalls/hooker-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(418, 'https://ncwaterfalls.com/waterfalls/upper-log-hollow-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(461, 'https://ncwaterfalls.com/waterfalls/batson-creek-falls', 'ncwaterfalls', 'Matched by name; neither side publishes a coordinate to check it against.'),
(462, 'https://ncwaterfalls.com/waterfalls/connestee-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(468, 'https://ncwaterfalls.com/waterfalls/toxaway-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.4 km of our coordinate.'),
(471, 'https://ncwaterfalls.com/waterfalls/upper-silver-run-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(482, 'https://ncwaterfalls.com/waterfalls/merry-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(496, 'https://ncwaterfalls.com/waterfalls/upper-courthouse-falls', 'ncwaterfalls', 'Matched by name and confirmed within 1.1 km of our coordinate.'),
(498, 'https://ncwaterfalls.com/waterfalls/chestnut-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(501, 'https://ncwaterfalls.com/waterfalls/discovery-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.1 km of our coordinate.'),
(503, 'https://ncwaterfalls.com/waterfalls/upper-dill-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.3 km of our coordinate.'),
(504, 'https://ncwaterfalls.com/waterfalls/sunburst-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.1 km of our coordinate.'),
(505, 'https://ncwaterfalls.com/waterfalls/little-moore-cove-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(512, 'https://ncwaterfalls.com/waterfalls/yellowstone-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.1 km of our coordinate.'),
(531, 'https://ncwaterfalls.com/waterfalls/lemon-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(548, 'https://ncwaterfalls.com/waterfalls/bennett-cove-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.1 km of our coordinate.'),
(550, 'https://ncwaterfalls.com/waterfalls/cullasaja-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.2 km of our coordinate.'),
(551, 'https://ncwaterfalls.com/waterfalls/quarry-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(552, 'https://ncwaterfalls.com/waterfalls/scadin-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(570, 'https://ncwaterfalls.com/waterfalls/lower-catawba-falls', 'ncwaterfalls', 'Matched by name; neither side publishes a coordinate to check it against.'),
(572, 'https://ncwaterfalls.com/waterfalls/glassmine-falls', 'ncwaterfalls', 'Matched by name and confirmed within 1.1 km of our coordinate.'),
(574, 'https://ncwaterfalls.com/waterfalls/kiesee-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.3 km of our coordinate.'),
(576, 'https://ncwaterfalls.com/waterfalls/reese-place-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(577, 'https://ncwaterfalls.com/waterfalls/summey-cove-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.1 km of our coordinate.'),
(578, 'https://ncwaterfalls.com/waterfalls/upper-kiesee-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.3 km of our coordinate.'),
(579, 'https://ncwaterfalls.com/waterfalls/beetree-fork-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(581, 'https://ncwaterfalls.com/waterfalls/east-fork-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.1 km of our coordinate.'),
(586, 'https://ncwaterfalls.com/waterfalls/bradley-cooper-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(590, 'https://ncwaterfalls.com/waterfalls/case-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(594, 'https://ncwaterfalls.com/waterfalls/poundingmill-branch-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(622, 'https://ncwaterfalls.com/waterfalls/no-name-cove-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(632, 'https://ncwaterfalls.com/waterfalls/potholes-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(633, 'https://ncwaterfalls.com/waterfalls/lake-sequoyah-dam', 'ncwaterfalls', 'Matched by name and confirmed within 0.1 km of our coordinate.'),
(636, 'https://ncwaterfalls.com/waterfalls/glencannon-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.2 km of our coordinate.'),
(639, 'https://ncwaterfalls.com/waterfalls/stick-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(640, 'https://ncwaterfalls.com/waterfalls/lower-stick-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(641, 'https://ncwaterfalls.com/waterfalls/slick-stick-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.1 km of our coordinate.'),
(661, 'https://ncwaterfalls.com/waterfalls/cherry-cove-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(685, 'https://ncwaterfalls.com/waterfalls/pot-branch-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(709, 'https://ncwaterfalls.com/waterfalls/little-creek-falls-highlands', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(729, 'https://ncwaterfalls.com/waterfalls/highlands-falls', 'ncwaterfalls', 'Matched by name; his coordinate is 4.9 km from ours, which is close enough to be the same fall seen from the trailhead and far enough to be worth reading before trusting.'),
(743, 'https://ncwaterfalls.com/waterfalls/leatherwood-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.1 km of our coordinate.'),
(744, 'https://ncwaterfalls.com/waterfalls/lower-bald-springs-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(745, 'https://ncwaterfalls.com/waterfalls/bald-springs-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(746, 'https://ncwaterfalls.com/waterfalls/rain-forest-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(765, 'https://ncwaterfalls.com/waterfalls/silvervale-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(774, 'https://ncwaterfalls.com/waterfalls/cascade-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(775, 'https://ncwaterfalls.com/waterfalls/betseys-rock-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(799, 'https://ncwaterfalls.com/waterfalls/green-mountain-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(812, 'https://ncwaterfalls.com/waterfalls/burgan-creek-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(821, 'https://ncwaterfalls.com/waterfalls/upper-catawba-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(835, 'https://ncwaterfalls.com/waterfalls/red-rock-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(838, 'https://ncwaterfalls.com/waterfalls/sam-branch-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(861, 'https://ncwaterfalls.com/waterfalls/cliff-branch-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(888, 'https://ncwaterfalls.com/waterfalls/big-creek-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(895, 'https://ncwaterfalls.com/waterfalls/boxcar-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.1 km of our coordinate.'),
(896, 'https://ncwaterfalls.com/waterfalls/graybeard-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(909, 'https://ncwaterfalls.com/waterfalls/jumping-fish-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(910, 'https://ncwaterfalls.com/waterfalls/lanier-falls', 'ncwaterfalls', 'Matched by name; neither side publishes a coordinate to check it against.'),
(911, 'https://ncwaterfalls.com/waterfalls/clark-park-falls', 'ncwaterfalls', 'Matched by name; neither side publishes a coordinate to check it against.'),
(922, 'https://ncwaterfalls.com/waterfalls/burningtown-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.1 km of our coordinate.'),
(923, 'https://ncwaterfalls.com/waterfalls/indian-camp-creek-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(926, 'https://ncwaterfalls.com/waterfalls/kuykendall-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(927, 'https://ncwaterfalls.com/waterfalls/bee-branch-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(944, 'https://ncwaterfalls.com/waterfalls/bear-creek-falls-tributary-forney-creek', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(950, 'https://ncwaterfalls.com/waterfalls/clear-creek-falls-nantahala-lake', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(962, 'https://ncwaterfalls.com/waterfalls/balsam-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(963, 'https://ncwaterfalls.com/waterfalls/lower-balsam-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(964, 'https://ncwaterfalls.com/waterfalls/patricia-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(986, 'https://ncwaterfalls.com/waterfalls/lauren-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(992, 'https://ncwaterfalls.com/waterfalls/sols-creek-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(997, 'https://ncwaterfalls.com/waterfalls/climbing-wall-falls', 'ncwaterfalls', 'Matched by name; his coordinate is 3.8 km from ours, which is close enough to be the same fall seen from the trailhead and far enough to be worth reading before trusting.'),
(999, 'https://ncwaterfalls.com/waterfalls/coyote-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(1001, 'https://ncwaterfalls.com/waterfalls/upper-bear-creek-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(1008, 'https://ncwaterfalls.com/waterfalls/upper-little-creek-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(1105, 'https://ncwaterfalls.com/waterfalls/falling-water-branch-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.'),
(1201, 'https://ncwaterfalls.com/waterfalls/cover-falls', 'ncwaterfalls', 'Matched by name; neither side publishes a coordinate to check it against.'),
(1237, 'https://ncwaterfalls.com/waterfalls/stairstep-falls', 'ncwaterfalls', 'Matched by name and confirmed within 0.0 km of our coordinate.')
ON CONFLICT (feature_id, url) DO NOTHING;

-- Rejected, same name and a different waterfall:
--   Jones Falls                        jones-falls                                 305.2 km
--   Cedar Falls (Fountain Inn)         cedar-falls                                 279.6 km
--   Cutler Falls                       cutler-falls                                118.1 km
--   Big Bearwallow Falls               big-bearwallow-falls                         66.8 km
--   Little Creek Falls                 little-creek-falls-highlands                 56.5 km
--   Milton Bradley Falls               milton-bradley-falls                         45.4 km
--   Waterfall on Long Branch           waterfall-on-long-branch                     21.5 km

COMMIT;
