-- Take everything the sources already publish, and parse it when we need it.
--
-- jw: "yeah I can see us using all of it. Grab it all and we'll parse it as
-- we need more." Which is the right order. All of this has been sitting in
-- data/ since the day it was fetched, unread -- the watercourse had been
-- extracted by the importer and dropped on the floor since 043, and it turned
-- out to be the discriminator this project keeps reaching for. The cost of
-- storing a field we never use is a column of text. The cost of not storing
-- it is discovering two years later that the answer was on disk all along.
--
-- Nothing here is parsed beyond picking the span the source put it in. Values
-- go in as written: "en:Looking Glass Falls", "Medium/large", "Reid NC/SC".
--
-- rows: 1172
--   waterway_type    467
--   river_basin      122
--   usgs_map         122
--   county           121
--   watershed        120
--   fall_type        118
--   tourism          35
--   alias            15
--   wikidata         14
--   direction        11
--   wikipedia        8
--   website          6
--   description      4
--   intermittent     3
--   access           2
--   gnis_id          2
--   wheelchair       2
--
-- The two worth naming. wikidata and wikipedia are stable external
-- identities -- the thing this whole session has been improvising around --
-- and gnis_id is the USGS board's own. Only 14, 8 and 2 features carry one,
-- but an identifier that is right is worth more than a name that is probably
-- right.
--
-- fall_type is the half of ncwaterfalls' "Type and Height" we had been
-- discarding: we took the number and threw away "14-foot overhanging
-- waterfall with a small pool". 118 of those. jw asked for cascade, drop,
-- slide, mixed -- this stores his sentence and leaves the vocabulary to a
-- normalizer, because the prose says things like "steep sliding and
-- cascading falls" that no four-value enum was going to hold.
--
-- alt_name:1 and :2 become aliases. We had been reading alt_name and silently
-- ignoring the numbered ones, which is the same bug as the semicolon list
-- 138 fixed: a source saying several things in a way we only half read.

BEGIN;

ALTER TABLE claims DROP CONSTRAINT claims_field_known;
ALTER TABLE claims ADD CONSTRAINT claims_field_known CHECK (
  field = ANY (ARRAY[
    'coordinate','parking_coordinate','view_coordinate','coordinate_raw',
    'trailhead_coordinate',
    'detour_parking_coordinate','detour_trailhead_coordinate','detour_hike_distance',
    'access_status','disambiguator','watercourse',
    'height','elevation_ft','elevation_gain_ft','petzoldt',
    'beauty_rating','photo_rating','solitude_rating',
    'hike_distance','accessibility','owner','name','alias',
    'photos_count','completed_hikes_count','reviews_count',
    -- new here
    'wikidata','wikipedia','gnis_id','waterway_type','tourism','access',
    'wheelchair','intermittent','website','description','direction',
    'county','river_basin','watershed','usgs_map','fall_type']::text[]));

INSERT INTO claims (group_id, feature_id, field, value, accepted)
SELECT v.group_id, cg.feature_id, v.field, to_jsonb(v.value), false
FROM (VALUES
  (1055, 'wikidata', 'Q6675324'),
  (1055, 'wikipedia', 'en:Looking Glass Falls'),
  (1055, 'waterway_type', 'waterfall'),
  (1661, 'waterway_type', 'waterfall'),
  (1661, 'tourism', 'attraction'),
  (1163, 'waterway_type', 'waterfall'),
  (1411, 'waterway_type', 'waterfall'),
  (1498, 'waterway_type', 'waterfall'),
  (1500, 'waterway_type', 'waterfall'),
  (1608, 'waterway_type', 'waterfall'),
  (1608, 'access', 'private'),
  (1650, 'waterway_type', 'waterfall'),
  (1285, 'waterway_type', 'waterfall'),
  (1109, 'waterway_type', 'waterfall'),
  (1088, 'waterway_type', 'waterfall'),
  (1177, 'waterway_type', 'waterfall'),
  (1410, 'waterway_type', 'waterfall'),
  (1289, 'waterway_type', 'waterfall'),
  (1081, 'waterway_type', 'waterfall'),
  (1079, 'waterway_type', 'waterfall'),
  (1607, 'waterway_type', 'waterfall'),
  (1607, 'alias', 'Tumblin Fun Falls'),
  (1207, 'waterway_type', 'waterfall'),
  (1220, 'waterway_type', 'waterfall'),
  (1497, 'waterway_type', 'waterfall'),
  (1060, 'waterway_type', 'waterfall'),
  (1614, 'waterway_type', 'waterfall'),
  (1262, 'waterway_type', 'waterfall'),
  (1261, 'waterway_type', 'waterfall'),
  (1312, 'waterway_type', 'waterfall'),
  (1615, 'waterway_type', 'waterfall'),
  (1616, 'waterway_type', 'waterfall'),
  (1540, 'waterway_type', 'waterfall'),
  (1540, 'alias', 'Wattacoo Falls'),
  (1061, 'wikidata', 'Q7296397'),
  (1061, 'wikipedia', 'en:Raven Cliff Falls (South Carolina)'),
  (1061, 'waterway_type', 'waterfall'),
  (1077, 'wikidata', 'Q37626'),
  (1077, 'waterway_type', 'waterfall'),
  (1644, 'waterway_type', 'waterfall'),
  (1321, 'waterway_type', 'waterfall'),
  (1251, 'waterway_type', 'waterfall'),
  (1255, 'waterway_type', 'waterfall'),
  (1254, 'waterway_type', 'waterfall'),
  (1375, 'waterway_type', 'waterfall'),
  (1488, 'waterway_type', 'waterfall'),
  (1394, 'waterway_type', 'waterfall'),
  (1395, 'waterway_type', 'waterfall'),
  (1482, 'waterway_type', 'waterfall'),
  (1421, 'waterway_type', 'waterfall'),
  (1154, 'waterway_type', 'waterfall'),
  (1379, 'waterway_type', 'waterfall'),
  (1129, 'waterway_type', 'waterfall'),
  (1519, 'waterway_type', 'waterfall'),
  (1390, 'waterway_type', 'waterfall'),
  (1493, 'waterway_type', 'waterfall'),
  (1399, 'waterway_type', 'waterfall'),
  (1128, 'waterway_type', 'waterfall'),
  (1387, 'waterway_type', 'waterfall'),
  (1116, 'waterway_type', 'waterfall'),
  (1373, 'waterway_type', 'waterfall'),
  (1635, 'waterway_type', 'waterfall'),
  (1504, 'waterway_type', 'waterfall'),
  (1089, 'waterway_type', 'waterfall'),
  (1113, 'waterway_type', 'waterfall'),
  (1151, 'waterway_type', 'waterfall'),
  (1151, 'alias', 'Holly Falls'),
  (1553, 'waterway_type', 'waterfall'),
  (1555, 'waterway_type', 'waterfall'),
  (1495, 'waterway_type', 'waterfall'),
  (1165, 'waterway_type', 'waterfall'),
  (1655, 'waterway_type', 'waterfall'),
  (1554, 'waterway_type', 'waterfall'),
  (1516, 'waterway_type', 'waterfall'),
  (1656, 'waterway_type', 'waterfall'),
  (1559, 'waterway_type', 'waterfall'),
  (1533, 'waterway_type', 'waterfall'),
  (1070, 'waterway_type', 'waterfall'),
  (1070, 'website', 'https://www.nps.gov/grsm/planyourvisit/waterfalls.htm'),
  (1084, 'waterway_type', 'waterfall'),
  (1609, 'waterway_type', 'waterfall'),
  (1293, 'waterway_type', 'waterfall'),
  (1071, 'waterway_type', 'waterfall'),
  (1651, 'waterway_type', 'waterfall'),
  (1069, 'waterway_type', 'waterfall'),
  (1657, 'waterway_type', 'waterfall'),
  (1150, 'waterway_type', 'waterfall'),
  (1342, 'waterway_type', 'waterfall'),
  (1341, 'waterway_type', 'waterfall'),
  (1418, 'waterway_type', 'waterfall'),
  (1343, 'waterway_type', 'waterfall'),
  (1155, 'waterway_type', 'waterfall'),
  (1120, 'waterway_type', 'waterfall'),
  (1120, 'alias', 'Hebron Falls'),
  (1120, 'alias', 'Hebron Colony Falls'),
  (1120, 'alias', 'Hebron Colony Rocks'),
  (1195, 'waterway_type', 'waterfall'),
  (1063, 'waterway_type', 'waterfall'),
  (1318, 'waterway_type', 'waterfall'),
  (1145, 'waterway_type', 'waterfall'),
  (1176, 'wikidata', 'Q7540272'),
  (1176, 'waterway_type', 'waterfall'),
  (1196, 'waterway_type', 'waterfall'),
  (1225, 'waterway_type', 'waterfall'),
  (1425, 'waterway_type', 'waterfall'),
  (1545, 'waterway_type', 'waterfall'),
  (1333, 'waterway_type', 'waterfall'),
  (1062, 'waterway_type', 'waterfall'),
  (1527, 'waterway_type', 'waterfall'),
  (1182, 'waterway_type', 'waterfall'),
  (1319, 'waterway_type', 'waterfall'),
  (1064, 'waterway_type', 'waterfall'),
  (1114, 'wikidata', 'Q5301461'),
  (1114, 'wikipedia', 'en:Douglas Falls'),
  (1114, 'waterway_type', 'waterfall'),
  (1073, 'waterway_type', 'waterfall'),
  (1073, 'alias', 'Falls on Grogan Creek'),
  (1306, 'waterway_type', 'waterfall'),
  (1483, 'waterway_type', 'waterfall'),
  (1250, 'waterway_type', 'waterfall'),
  (1183, 'waterway_type', 'waterfall'),
  (1140, 'waterway_type', 'waterfall'),
  (1140, 'tourism', 'attraction'),
  (1461, 'waterway_type', 'waterfall'),
  (1422, 'waterway_type', 'waterfall'),
  (1423, 'waterway_type', 'waterfall'),
  (1437, 'waterway_type', 'waterfall'),
  (1162, 'waterway_type', 'waterfall'),
  (1630, 'waterway_type', 'waterfall'),
  (1239, 'waterway_type', 'waterfall'),
  (1478, 'waterway_type', 'waterfall'),
  (1098, 'wikipedia', 'en:Roaring Fork Falls (Yancey County)'),
  (1098, 'waterway_type', 'waterfall'),
  (1238, 'waterway_type', 'waterfall'),
  (1361, 'waterway_type', 'waterfall'),
  (1134, 'waterway_type', 'waterfall'),
  (1136, 'waterway_type', 'waterfall'),
  (1191, 'waterway_type', 'waterfall'),
  (1065, 'wikipedia', 'en:Graveyard Fields'),
  (1065, 'waterway_type', 'waterfall'),
  (1095, 'waterway_type', 'waterfall'),
  (1095, 'intermittent', 'no'),
  (1123, 'waterway_type', 'waterfall'),
  (1125, 'waterway_type', 'waterfall'),
  (1126, 'waterway_type', 'waterfall'),
  (1097, 'wikidata', 'Q37332'),
  (1097, 'wikipedia', 'en:Crabtree Falls (North Carolina)'),
  (1097, 'waterway_type', 'waterfall'),
  (1096, 'wikidata', 'Q37354'),
  (1096, 'waterway_type', 'waterfall'),
  (1107, 'waterway_type', 'waterfall'),
  (1107, 'tourism', 'attraction'),
  (1066, 'waterway_type', 'waterfall'),
  (1223, 'waterway_type', 'waterfall'),
  (1184, 'waterway_type', 'waterfall'),
  (1184, 'tourism', 'attraction'),
  (1452, 'waterway_type', 'waterfall'),
  (1148, 'gnis_id', '1652085'),
  (1148, 'waterway_type', 'waterfall'),
  (1439, 'waterway_type', 'waterfall'),
  (1642, 'waterway_type', 'waterfall'),
  (1133, 'waterway_type', 'waterfall'),
  (1216, 'waterway_type', 'waterfall'),
  (1216, 'tourism', 'attraction'),
  (1216, 'website', 'https://www.hdcarolina.com/episode/big-bradley-falls'),
  (1216, 'description', 'A nice waterfall with good flow. Very difficult to reach and reaching the base is not too safe.'),
  (1451, 'waterway_type', 'waterfall'),
  (1087, 'waterway_type', 'waterfall'),
  (1087, 'website', 'https://www.hdcarolina.com/episode/little-bradley-falls'),
  (1271, 'waterway_type', 'waterfall'),
  (1271, 'tourism', 'attraction'),
  (1272, 'waterway_type', 'waterfall'),
  (1053, 'waterway_type', 'waterfall'),
  (1053, 'tourism', 'attraction'),
  (1197, 'waterway_type', 'waterfall'),
  (1197, 'tourism', 'attraction'),
  (1067, 'waterway_type', 'waterfall'),
  (1193, 'waterway_type', 'waterfall'),
  (1175, 'wikidata', 'Q37255'),
  (1175, 'waterway_type', 'waterfall'),
  (1175, 'tourism', 'attraction'),
  (1175, 'wheelchair', 'no'),
  (1075, 'wikidata', 'Q38075'),
  (1075, 'waterway_type', 'waterfall'),
  (1641, 'waterway_type', 'waterfall'),
  (1365, 'waterway_type', 'waterfall'),
  (1351, 'waterway_type', 'waterfall'),
  (1648, 'waterway_type', 'waterfall'),
  (1170, 'waterway_type', 'waterfall'),
  (1135, 'waterway_type', 'waterfall'),
  (1135, 'access', 'private'),
  (1135, 'alias', 'Bust-Yer-Butt Falls;Driftwood Falls'),
  (1135, 'alias', 'Bust Your Butt Falls'),
  (1058, 'waterway_type', 'waterfall'),
  (1643, 'gnis_id', '1275431'),
  (1643, 'waterway_type', 'waterfall'),
  (1260, 'waterway_type', 'waterfall'),
  (1550, 'waterway_type', 'waterfall'),
  (1550, 'tourism', 'attraction'),
  (1603, 'waterway_type', 'waterfall'),
  (1603, 'tourism', 'attraction'),
  (1602, 'waterway_type', 'waterfall'),
  (1057, 'waterway_type', 'waterfall'),
  (1057, 'tourism', 'attraction'),
  (1094, 'wikidata', 'Q37634'),
  (1094, 'wikipedia', 'en:Linville Falls'),
  (1094, 'waterway_type', 'waterfall'),
  (1094, 'tourism', 'attraction'),
  (1094, 'website', 'https://www.visitnc.com'),
  (1324, 'waterway_type', 'waterfall'),
  (1324, 'tourism', 'attraction'),
  (1323, 'waterway_type', 'waterfall'),
  (1323, 'tourism', 'attraction'),
  (1237, 'waterway_type', 'waterfall'),
  (1086, 'waterway_type', 'waterfall'),
  (1086, 'alias', 'Thompson Falls'),
  (1218, 'waterway_type', 'waterfall'),
  (1167, 'waterway_type', 'waterfall'),
  (1054, 'waterway_type', 'waterfall'),
  (1054, 'tourism', 'attraction'),
  (1367, 'waterway_type', 'waterfall'),
  (1115, 'waterway_type', 'waterfall'),
  (1468, 'waterway_type', 'waterfall'),
  (1201, 'waterway_type', 'waterfall'),
  (1639, 'waterway_type', 'waterfall'),
  (1130, 'waterway_type', 'waterfall'),
  (1619, 'waterway_type', 'waterfall'),
  (1101, 'waterway_type', 'waterfall'),
  (1101, 'alias', 'Nellie''s Falls'),
  (1085, 'waterway_type', 'waterfall'),
  (1152, 'waterway_type', 'waterfall'),
  (1253, 'waterway_type', 'waterfall'),
  (1228, 'waterway_type', 'waterfall'),
  (1304, 'waterway_type', 'waterfall'),
  (1074, 'waterway_type', 'waterfall'),
  (1068, 'waterway_type', 'waterfall'),
  (1181, 'waterway_type', 'waterfall'),
  (1174, 'waterway_type', 'waterfall'),
  (1173, 'waterway_type', 'waterfall'),
  (1168, 'waterway_type', 'waterfall'),
  (1108, 'waterway_type', 'waterfall'),
  (1158, 'waterway_type', 'waterfall'),
  (1471, 'waterway_type', 'waterfall'),
  (1469, 'waterway_type', 'waterfall'),
  (1194, 'waterway_type', 'waterfall'),
  (1620, 'waterway_type', 'waterfall'),
  (1121, 'waterway_type', 'waterfall'),
  (1121, 'description', 'Elk River Falls and swimming hole'),
  (1056, 'wikidata', 'Q6908151'),
  (1056, 'waterway_type', 'waterfall'),
  (1146, 'wikidata', 'Q38328'),
  (1146, 'waterway_type', 'waterfall'),
  (1209, 'waterway_type', 'waterfall'),
  (1208, 'waterway_type', 'waterfall'),
  (1652, 'waterway_type', 'waterfall'),
  (1164, 'waterway_type', 'waterfall'),
  (1149, 'waterway_type', 'waterfall'),
  (1653, 'waterway_type', 'waterfall'),
  (1479, 'waterway_type', 'waterfall'),
  (1366, 'waterway_type', 'waterfall'),
  (1083, 'waterway_type', 'waterfall'),
  (1083, 'intermittent', 'no'),
  (1083, 'website', 'https://www.pearsonsfalls.org/'),
  (1564, 'waterway_type', 'waterfall'),
  (1534, 'waterway_type', 'waterfall'),
  (1534, 'alias', 'Grotto Falls'),
  (1536, 'waterway_type', 'waterfall'),
  (1593, 'waterway_type', 'waterfall'),
  (1592, 'waterway_type', 'waterfall'),
  (1139, 'waterway_type', 'waterfall'),
  (1082, 'waterway_type', 'waterfall'),
  (1144, 'waterway_type', 'waterfall'),
  (1211, 'waterway_type', 'waterfall'),
  (1287, 'waterway_type', 'waterfall'),
  (1287, 'alias', 'Gravely Falls'),
  (1435, 'waterway_type', 'waterfall'),
  (1632, 'waterway_type', 'waterfall'),
  (1247, 'waterway_type', 'waterfall'),
  (1188, 'waterway_type', 'waterfall'),
  (1535, 'waterway_type', 'waterfall'),
  (1582, 'waterway_type', 'waterfall'),
  (1574, 'waterway_type', 'waterfall'),
  (1328, 'waterway_type', 'waterfall'),
  (1328, 'description', 'Collectively these four falls are known as Paw Paw Falls'),
  (1515, 'waterway_type', 'waterfall'),
  (1448, 'waterway_type', 'waterfall'),
  (1455, 'waterway_type', 'waterfall'),
  (1080, 'waterway_type', 'waterfall'),
  (1080, 'alias', 'Dorothy Ehrlich Walker Falls'),
  (1645, 'waterway_type', 'waterfall'),
  (1169, 'waterway_type', 'waterfall'),
  (1229, 'waterway_type', 'waterfall'),
  (1141, 'waterway_type', 'waterfall'),
  (1441, 'waterway_type', 'waterfall'),
  (1539, 'waterway_type', 'waterfall'),
  (1618, 'waterway_type', 'waterfall'),
  (1392, 'waterway_type', 'waterfall'),
  (1127, 'waterway_type', 'waterfall'),
  (1617, 'waterway_type', 'waterfall'),
  (1613, 'waterway_type', 'waterfall'),
  (1572, 'waterway_type', 'waterfall'),
  (1598, 'waterway_type', 'waterfall'),
  (1596, 'waterway_type', 'waterfall'),
  (1658, 'waterway_type', 'waterfall'),
  (1090, 'waterway_type', 'waterfall'),
  (1654, 'waterway_type', 'waterfall'),
  (1078, 'waterway_type', 'waterfall'),
  (1198, 'waterway_type', 'waterfall'),
  (1157, 'waterway_type', 'waterfall'),
  (1611, 'waterway_type', 'waterfall'),
  (1166, 'waterway_type', 'waterfall'),
  (1403, 'waterway_type', 'waterfall'),
  (1507, 'waterway_type', 'waterfall'),
  (1450, 'waterway_type', 'waterfall'),
  (1449, 'waterway_type', 'waterfall'),
  (1518, 'waterway_type', 'waterfall'),
  (1429, 'waterway_type', 'waterfall'),
  (1514, 'waterway_type', 'waterfall'),
  (1513, 'waterway_type', 'waterfall'),
  (1389, 'waterway_type', 'waterfall'),
  (1605, 'waterway_type', 'waterfall'),
  (1265, 'waterway_type', 'waterfall'),
  (1327, 'waterway_type', 'waterfall'),
  (1327, 'description', 'Collectively these four falls are known as Paw Paw Falls'),
  (1329, 'waterway_type', 'waterfall'),
  (1459, 'waterway_type', 'waterfall'),
  (1485, 'waterway_type', 'waterfall'),
  (1486, 'waterway_type', 'waterfall'),
  (1372, 'waterway_type', 'waterfall'),
  (1268, 'waterway_type', 'waterfall'),
  (1269, 'waterway_type', 'waterfall'),
  (1270, 'waterway_type', 'waterfall'),
  (1266, 'waterway_type', 'waterfall'),
  (1280, 'waterway_type', 'waterfall'),
  (1264, 'waterway_type', 'waterfall'),
  (1340, 'waterway_type', 'waterfall'),
  (1563, 'waterway_type', 'waterfall'),
  (1156, 'waterway_type', 'waterfall'),
  (1475, 'waterway_type', 'waterfall'),
  (1526, 'waterway_type', 'waterfall'),
  (1396, 'waterway_type', 'waterfall'),
  (1397, 'waterway_type', 'waterfall'),
  (1290, 'waterway_type', 'waterfall'),
  (1391, 'waterway_type', 'waterfall'),
  (1374, 'waterway_type', 'waterfall'),
  (1314, 'waterway_type', 'waterfall'),
  (1245, 'waterway_type', 'waterfall'),
  (1349, 'waterway_type', 'waterfall'),
  (1307, 'waterway_type', 'waterfall'),
  (1308, 'waterway_type', 'waterfall'),
  (1190, 'waterway_type', 'waterfall'),
  (1557, 'waterway_type', 'waterfall'),
  (1259, 'waterway_type', 'waterfall'),
  (1604, 'waterway_type', 'waterfall'),
  (1511, 'waterway_type', 'waterfall'),
  (1388, 'waterway_type', 'waterfall'),
  (1606, 'waterway_type', 'waterfall'),
  (1409, 'waterway_type', 'waterfall'),
  (1315, 'waterway_type', 'waterfall'),
  (1316, 'waterway_type', 'waterfall'),
  (1137, 'waterway_type', 'waterfall'),
  (1138, 'waterway_type', 'waterfall'),
  (1302, 'waterway_type', 'waterfall'),
  (1303, 'waterway_type', 'waterfall'),
  (1288, 'waterway_type', 'waterfall'),
  (1595, 'waterway_type', 'waterfall'),
  (1509, 'waterway_type', 'waterfall'),
  (1508, 'waterway_type', 'waterfall'),
  (1159, 'waterway_type', 'waterfall'),
  (1444, 'waterway_type', 'waterfall'),
  (1243, 'waterway_type', 'waterfall'),
  (1431, 'waterway_type', 'waterfall'),
  (1501, 'waterway_type', 'waterfall'),
  (1420, 'waterway_type', 'waterfall'),
  (1415, 'waterway_type', 'waterfall'),
  (1344, 'waterway_type', 'waterfall'),
  (1412, 'waterway_type', 'waterfall'),
  (1199, 'waterway_type', 'waterfall'),
  (1215, 'waterway_type', 'waterfall'),
  (1484, 'waterway_type', 'waterfall'),
  (1281, 'waterway_type', 'waterfall'),
  (1524, 'waterway_type', 'waterfall'),
  (1419, 'waterway_type', 'waterfall'),
  (1473, 'waterway_type', 'waterfall'),
  (1525, 'waterway_type', 'waterfall'),
  (1427, 'waterway_type', 'waterfall'),
  (1503, 'waterway_type', 'waterfall'),
  (1521, 'waterway_type', 'waterfall'),
  (1522, 'waterway_type', 'waterfall'),
  (1359, 'waterway_type', 'waterfall'),
  (1401, 'waterway_type', 'waterfall'),
  (1400, 'waterway_type', 'waterfall'),
  (1402, 'waterway_type', 'waterfall'),
  (1309, 'wikidata', 'Q37429'),
  (1309, 'waterway_type', 'waterfall'),
  (1496, 'waterway_type', 'waterfall'),
  (1356, 'waterway_type', 'waterfall'),
  (1357, 'waterway_type', 'waterfall'),
  (1499, 'waterway_type', 'waterfall'),
  (1436, 'waterway_type', 'waterfall'),
  (1131, 'waterway_type', 'waterfall'),
  (1076, 'waterway_type', 'waterfall'),
  (1358, 'waterway_type', 'waterfall'),
  (1378, 'waterway_type', 'waterfall'),
  (1277, 'waterway_type', 'waterfall'),
  (1278, 'waterway_type', 'waterfall'),
  (1355, 'waterway_type', 'waterfall'),
  (1386, 'waterway_type', 'waterfall'),
  (1313, 'waterway_type', 'waterfall'),
  (1660, 'waterway_type', 'waterfall'),
  (1634, 'waterway_type', 'waterfall'),
  (1172, 'waterway_type', 'waterfall'),
  (1171, 'waterway_type', 'waterfall'),
  (1586, 'waterway_type', 'waterfall'),
  (1585, 'waterway_type', 'waterfall'),
  (1506, 'waterway_type', 'waterfall'),
  (1490, 'waterway_type', 'waterfall'),
  (1505, 'waterway_type', 'waterfall'),
  (1413, 'waterway_type', 'waterfall'),
  (1103, 'waterway_type', 'waterfall'),
  (1474, 'waterway_type', 'waterfall'),
  (1325, 'waterway_type', 'waterfall'),
  (1414, 'waterway_type', 'waterfall'),
  (1532, 'waterway_type', 'waterfall'),
  (1531, 'waterway_type', 'waterfall'),
  (1551, 'waterway_type', 'waterfall'),
  (1119, 'waterway_type', 'waterfall'),
  (1132, 'waterway_type', 'waterfall'),
  (1406, 'waterway_type', 'waterfall'),
  (1393, 'waterway_type', 'waterfall'),
  (1226, 'waterway_type', 'waterfall'),
  (1445, 'waterway_type', 'waterfall'),
  (1512, 'waterway_type', 'waterfall'),
  (1100, 'waterway_type', 'waterfall'),
  (1458, 'waterway_type', 'waterfall'),
  (1457, 'waterway_type', 'waterfall'),
  (1296, 'waterway_type', 'waterfall'),
  (1232, 'waterway_type', 'waterfall'),
  (1529, 'waterway_type', 'waterfall'),
  (1301, 'waterway_type', 'waterfall'),
  (1276, 'waterway_type', 'waterfall'),
  (1258, 'waterway_type', 'waterfall'),
  (1249, 'waterway_type', 'waterfall'),
  (1292, 'waterway_type', 'waterfall'),
  (1424, 'waterway_type', 'waterfall'),
  (1460, 'waterway_type', 'waterfall'),
  (1462, 'waterway_type', 'waterfall'),
  (1463, 'waterway_type', 'waterfall'),
  (1241, 'waterway_type', 'waterfall'),
  (1248, 'waterway_type', 'waterfall'),
  (1432, 'waterway_type', 'waterfall'),
  (1383, 'waterway_type', 'waterfall'),
  (1384, 'waterway_type', 'waterfall'),
  (1385, 'waterway_type', 'waterfall'),
  (1246, 'waterway_type', 'waterfall'),
  (1659, 'waterway_type', 'waterfall'),
  (1610, 'waterway_type', 'waterfall'),
  (1234, 'waterway_type', 'waterfall'),
  (1443, 'waterway_type', 'waterfall'),
  (1236, 'waterway_type', 'waterfall'),
  (1360, 'waterway_type', 'waterfall'),
  (1362, 'waterway_type', 'waterfall'),
  (1363, 'waterway_type', 'waterfall'),
  (1370, 'waterway_type', 'waterfall'),
  (1352, 'waterway_type', 'waterfall'),
  (1353, 'waterway_type', 'waterfall'),
  (1489, 'waterway_type', 'waterfall'),
  (1336, 'waterway_type', 'waterfall'),
  (1546, 'waterway_type', 'waterfall'),
  (1510, 'waterway_type', 'waterfall'),
  (1300, 'waterway_type', 'waterfall'),
  (1590, 'waterway_type', 'waterfall'),
  (1298, 'waterway_type', 'waterfall'),
  (1584, 'waterway_type', 'waterfall'),
  (1428, 'waterway_type', 'waterfall'),
  (1283, 'waterway_type', 'waterfall'),
  (1299, 'waterway_type', 'waterfall'),
  (1118, 'waterway_type', 'waterfall'),
  (1332, 'waterway_type', 'waterfall'),
  (1480, 'waterway_type', 'waterfall'),
  (1212, 'waterway_type', 'waterfall'),
  (1417, 'waterway_type', 'waterfall'),
  (1338, 'waterway_type', 'waterfall'),
  (1331, 'waterway_type', 'waterfall'),
  (1481, 'waterway_type', 'waterfall'),
  (1284, 'waterway_type', 'waterfall'),
  (1416, 'waterway_type', 'waterfall'),
  (1492, 'waterway_type', 'waterfall'),
  (1291, 'waterway_type', 'waterfall'),
  (1434, 'waterway_type', 'waterfall'),
  (1217, 'waterway_type', 'waterfall'),
  (1530, 'waterway_type', 'waterfall'),
  (1631, 'waterway_type', 'waterfall'),
  (1629, 'waterway_type', 'waterfall'),
  (1244, 'waterway_type', 'waterfall'),
  (1240, 'waterway_type', 'waterfall'),
  (1502, 'waterway_type', 'waterfall'),
  (1491, 'waterway_type', 'waterfall'),
  (1099, 'waterway_type', 'waterfall'),
  (1153, 'waterway_type', 'waterfall'),
  (1153, 'intermittent', 'no'),
  (1124, 'waterway_type', 'waterfall'),
  (1224, 'waterway_type', 'waterfall'),
  (1562, 'waterway_type', 'waterfall'),
  (1446, 'waterway_type', 'waterfall'),
  (1322, 'waterway_type', 'waterfall'),
  (1407, 'waterway_type', 'waterfall'),
  (1408, 'waterway_type', 'waterfall'),
  (1405, 'waterway_type', 'waterfall'),
  (1517, 'waterway_type', 'waterfall'),
  (1102, 'waterway_type', 'waterfall'),
  (1105, 'waterway_type', 'waterfall'),
  (1257, 'waterway_type', 'waterfall'),
  (1091, 'waterway_type', 'waterfall'),
  (1601, 'waterway_type', 'waterfall'),
  (1547, 'waterway_type', 'waterfall'),
  (1547, 'alias', 'Sid''s Falls'),
  (1371, 'waterway_type', 'waterfall'),
  (1549, 'waterway_type', 'waterfall'),
  (1561, 'waterway_type', 'waterfall'),
  (1638, 'waterway_type', 'waterfall'),
  (1213, 'waterway_type', 'waterfall'),
  (1214, 'waterway_type', 'waterfall'),
  (1569, 'waterway_type', 'waterfall'),
  (1106, 'waterway_type', 'waterfall'),
  (1106, 'website', 'https://www.hdcarolina.com/episode/riley-moore-falls'),
  (1649, 'wikidata', 'Q37410'),
  (1649, 'wikipedia', 'en:Anna Ruby Falls'),
  (1649, 'waterway_type', 'waterfall'),
  (1464, 'waterway_type', 'waterfall'),
  (1567, 'waterway_type', 'waterfall'),
  (1568, 'waterway_type', 'waterfall'),
  (1600, 'waterway_type', 'waterfall'),
  (1548, 'waterway_type', 'waterfall'),
  (1566, 'waterway_type', 'waterfall'),
  (1472, 'waterway_type', 'waterfall'),
  (1621, 'waterway_type', 'waterfall'),
  (1627, 'waterway_type', 'waterfall'),
  (1664, 'tourism', 'viewpoint'),
  (1664, 'direction', '350'),
  (1665, 'tourism', 'viewpoint'),
  (1666, 'tourism', 'viewpoint'),
  (1666, 'direction', '330'),
  (1667, 'tourism', 'viewpoint'),
  (1668, 'tourism', 'viewpoint'),
  (1670, 'tourism', 'viewpoint'),
  (1670, 'wheelchair', 'yes'),
  (1670, 'direction', 'W'),
  (1672, 'tourism', 'viewpoint'),
  (1673, 'tourism', 'viewpoint'),
  (1673, 'direction', '270'),
  (1675, 'tourism', 'viewpoint'),
  (1675, 'direction', 'n'),
  (1676, 'tourism', 'viewpoint'),
  (1676, 'direction', 'n'),
  (1677, 'tourism', 'viewpoint'),
  (1677, 'direction', 'S'),
  (1678, 'tourism', 'viewpoint'),
  (1682, 'tourism', 'viewpoint'),
  (1686, 'tourism', 'viewpoint'),
  (1686, 'direction', '180'),
  (1687, 'tourism', 'viewpoint'),
  (1687, 'direction', '180'),
  (1688, 'tourism', 'viewpoint'),
  (1689, 'tourism', 'viewpoint'),
  (1691, 'tourism', 'viewpoint'),
  (1691, 'direction', '225'),
  (1692, 'tourism', 'viewpoint'),
  (1692, 'direction', '55'),
  (1694, 'county', 'Transylvania'),
  (1694, 'river_basin', 'Savannah'),
  (1694, 'watershed', 'Medium/large'),
  (1694, 'usgs_map', 'Reid NC/SC'),
  (1694, 'fall_type', '14-foot overhanging waterfall with large pool'),
  (1695, 'county', 'Transylvania'),
  (1695, 'river_basin', 'French Broad'),
  (1695, 'watershed', 'Very small'),
  (1695, 'usgs_map', 'Shining Rock'),
  (1695, 'fall_type', 'High falls dropping off massive rock face; overall height estimated around 80 feet'),
  (1698, 'county', 'Rutherford'),
  (1698, 'river_basin', 'Catawba'),
  (1698, 'watershed', 'Very small'),
  (1698, 'usgs_map', 'Benn Knob'),
  (1698, 'fall_type', 'Series of slides, drops, and potholes, about 25 feet high'),
  (1699, 'county', 'Transylvania'),
  (1699, 'river_basin', 'French Broad'),
  (1699, 'watershed', 'Small'),
  (1699, 'usgs_map', 'Sam Knob'),
  (1699, 'fall_type', 'Upper 7-foot drop with a lower long slide about 16 feet high'),
  (1700, 'county', 'Jackson'),
  (1700, 'river_basin', 'Savannah'),
  (1700, 'watershed', 'Small'),
  (1700, 'usgs_map', 'Cashiers NC/SC/GA'),
  (1700, 'fall_type', 'Cascade and slide leading to 30-foot vertical falls'),
  (1701, 'county', 'Transylvania'),
  (1701, 'river_basin', 'French Broad'),
  (1701, 'watershed', 'Small'),
  (1701, 'usgs_map', 'Sam Knob'),
  (1701, 'fall_type', 'Cascading falls about 20 feet high'),
  (1702, 'county', 'Transylvania'),
  (1702, 'river_basin', 'Savannah'),
  (1702, 'watershed', 'Medium/large'),
  (1702, 'usgs_map', 'Reid NC/SC'),
  (1702, 'fall_type', 'Long steep, river-wide slide measuring 42 feet high'),
  (1704, 'county', 'Clay'),
  (1704, 'river_basin', 'Little Tennessee'),
  (1704, 'watershed', 'Small'),
  (1704, 'usgs_map', 'Topton'),
  (1704, 'fall_type', 'Two-level steep cascade, about 35 feet high'),
  (1705, 'county', 'Transylvania'),
  (1705, 'river_basin', 'French Broad'),
  (1705, 'watershed', 'Medium'),
  (1705, 'usgs_map', 'Shining Rock'),
  (1705, 'fall_type', 'Beautiful sheer drop of 60 feet Measured with rangefinder'),
  (1707, 'county', 'Polk'),
  (1707, 'river_basin', 'Broad'),
  (1707, 'watershed', 'Small'),
  (1707, 'usgs_map', 'Cliffield Mountain'),
  (1707, 'fall_type', 'Two-tiered, cascading falls about 25’ high'),
  (1709, 'county', 'Yancey'),
  (1709, 'river_basin', 'French Broad'),
  (1709, 'watershed', 'Small'),
  (1709, 'usgs_map', 'Mount Mitchell'),
  (1709, 'fall_type', '130-foot cascading falls with steep 50-foot lower section'),
  (1710, 'county', 'Yancey'),
  (1710, 'river_basin', 'French Broad'),
  (1710, 'watershed', 'Small'),
  (1710, 'usgs_map', 'Chestoa NC/TN'),
  (1710, 'fall_type', 'Steep sliding falls about 25 feet high'),
  (1711, 'county', 'Transylvania'),
  (1711, 'river_basin', 'Savannah'),
  (1711, 'watershed', 'Small'),
  (1711, 'usgs_map', 'Cashiers NC/SC/GA'),
  (1711, 'fall_type', 'Mostly freefalling 12-foot-high falls'),
  (1712, 'county', 'Transylvania'),
  (1712, 'river_basin', 'French Broad'),
  (1712, 'watershed', 'Small'),
  (1712, 'usgs_map', 'Shining Rock'),
  (1712, 'fall_type', '16-foot creek-wide, multi-ledge falls'),
  (4916, 'county', 'Buncombe'),
  (4916, 'river_basin', 'French Broad'),
  (4916, 'watershed', 'Itsy-bitsy'),
  (4916, 'usgs_map', 'Montreat'),
  (4916, 'fall_type', 'Very steep, sliding falls, approximately 250 feet high'),
  (1713, 'county', 'Macon'),
  (1713, 'river_basin', 'Savannah'),
  (1713, 'watershed', 'Small'),
  (1713, 'usgs_map', 'Highlands NC/GA'),
  (1713, 'fall_type', 'Very long and steep slide about 200 feet high'),
  (1714, 'county', 'Henderson'),
  (1714, 'river_basin', 'Broad'),
  (1714, 'watershed', 'Very small'),
  (1714, 'usgs_map', 'Cliffield Mountain'),
  (1714, 'fall_type', 'Freefall and cascades about 35 feet high'),
  (1716, 'county', 'Transylvania'),
  (1716, 'river_basin', 'French Broad'),
  (1716, 'watershed', 'Medium/large'),
  (1716, 'usgs_map', 'Standing Stone Mtn NC/SC'),
  (1716, 'fall_type', 'Large, steep, sliding and cascading falls about 110 feet high'),
  (1717, 'county', 'Swain'),
  (1717, 'river_basin', 'Little Tennessee'),
  (1717, 'watershed', 'Small'),
  (1717, 'usgs_map', 'Noland Creek'),
  (1717, 'fall_type', 'Long section of cascades and slides It’s nearly impossible to calculate the height accurately. As well as I can determine using LiDAR, it’s somewhere around 55 feet overall'),
  (1718, 'county', 'Macon'),
  (1718, 'river_basin', 'Savannah'),
  (1718, 'watershed', 'Small'),
  (1718, 'usgs_map', 'Highlands NC/GA'),
  (1718, 'fall_type', 'Cascading, free-falling, and sliding falls approx. 600 feet high'),
  (1719, 'county', 'Wilkes'),
  (1719, 'river_basin', 'Yadkin-Pee Dee'),
  (1719, 'watershed', 'Very small'),
  (1719, 'usgs_map', 'Glendale Springs'),
  (1719, 'fall_type', 'Multilevel falls at least 200 feet high'),
  (1720, 'county', 'Rutherford'),
  (1720, 'river_basin', 'Broad'),
  (1720, 'watershed', 'Very small'),
  (1720, 'usgs_map', 'Bat Cave'),
  (1720, 'fall_type', 'Narrow, very steep falls over 350 feet high See the Measuring section for details about the height'),
  (1723, 'county', 'Graham'),
  (1723, 'river_basin', 'Little Tennessee'),
  (1723, 'watershed', 'Very small'),
  (1723, 'usgs_map', 'Robbinsville'),
  (1723, 'fall_type', 'Near-vertical slide, 65 feet high'),
  (1724, 'county', 'Swain'),
  (1724, 'river_basin', 'Little Tennessee'),
  (1724, 'watershed', 'Small'),
  (1724, 'usgs_map', 'Noland Creek'),
  (1724, 'fall_type', '30-foot drop over mini-ledges, with series of cascades below'),
  (1725, 'county', 'Transylvania'),
  (1725, 'river_basin', 'French Broad'),
  (1725, 'watershed', 'Very small'),
  (1725, 'usgs_map', 'Shining Rock'),
  (1725, 'fall_type', 'High cascading and freefalling falls; overall height is over 100 feet I couldn’t get an accurate height measurement with the rangefinder. Suffice it to say that if you include all the drops, this waterfall is very high'),
  (1727, 'county', 'Transylvania'),
  (1727, 'river_basin', 'French Broad'),
  (1727, 'watershed', 'Medium/large'),
  (1727, 'usgs_map', 'Rosman'),
  (1727, 'fall_type', 'Steep sliding cascade about 20 feet high'),
  (4917, 'county', 'Transylvania'),
  (4917, 'river_basin', 'French Broad'),
  (4917, 'watershed', 'Small'),
  (4917, 'usgs_map', 'Sam Knob'),
  (4917, 'fall_type', 'Two-section drop totaling about 18 feet'),
  (1728, 'county', 'Macon'),
  (1728, 'river_basin', 'Little Tennessee'),
  (1728, 'watershed', 'Very small'),
  (1728, 'usgs_map', 'Highlands NC/GA'),
  (1728, 'fall_type', 'Upper slide and lower freefall totaling 116 feet'),
  (1729, 'county', 'Transylvania'),
  (1729, 'river_basin', 'French Broad'),
  (1729, 'watershed', 'Very small'),
  (1729, 'usgs_map', 'Shining Rock'),
  (1729, 'fall_type', 'Multilevel falls about 70 feet high'),
  (1730, 'county', 'Macon'),
  (1730, 'river_basin', 'Little Tennessee'),
  (1730, 'watershed', 'Medium'),
  (1730, 'usgs_map', 'Scaly Mountain'),
  (1730, 'fall_type', 'Steep, cascading falls about 180 feet high'),
  (1731, 'county', 'McDowell'),
  (1731, 'river_basin', 'Catawba'),
  (1731, 'watershed', 'Small'),
  (1731, 'usgs_map', 'Moffitt Hill'),
  (1731, 'fall_type', 'Freefalling and cascading falls about 65 feet high'),
  (1732, 'county', 'Polk'),
  (1732, 'river_basin', 'Broad'),
  (1732, 'watershed', 'Medium/large'),
  (1732, 'usgs_map', 'Cliffield Mountain'),
  (1733, 'county', 'Polk'),
  (1733, 'river_basin', 'Broad'),
  (1733, 'watershed', 'Small'),
  (1733, 'usgs_map', 'Cliffield Mountain'),
  (1733, 'fall_type', 'Steep, cascading, 22’ falls'),
  (1734, 'county', 'Transylvania'),
  (1734, 'river_basin', 'French Broad'),
  (1734, 'watershed', 'Very small'),
  (1734, 'usgs_map', 'Shining Rock'),
  (1734, 'fall_type', 'Freefalling falls over a bluff, with a total height of about 35 feet'),
  (1735, 'county', 'Transylvania'),
  (1735, 'river_basin', 'French Broad'),
  (1735, 'watershed', 'Small/medium'),
  (1735, 'usgs_map', 'Table Rock SC/NC'),
  (1735, 'fall_type', 'Cascade about 12 feet high'),
  (1737, 'county', 'Macon'),
  (1737, 'river_basin', 'Little Tennessee'),
  (1737, 'watershed', 'Medium'),
  (1737, 'usgs_map', 'Highlands NC/GA'),
  (1737, 'fall_type', '85-foot slide, cascade, and freefall, with most of it freefalling'),
  (3977, 'county', 'Macon'),
  (3977, 'river_basin', 'Little Tennessee'),
  (3977, 'watershed', 'Small/medium'),
  (3977, 'usgs_map', 'Highlands NC/GA'),
  (3977, 'fall_type', 'Sliding, freefalling, and cascading falls approx. 100 feet high'),
  (1739, 'county', 'Jackson'),
  (1739, 'river_basin', 'Savannah'),
  (1739, 'watershed', 'Small'),
  (1739, 'usgs_map', 'Cashiers NC/SC/GA'),
  (1739, 'fall_type', 'Very steep sliding and cascading falls, about 48 feet high'),
  (1740, 'county', 'Macon'),
  (1740, 'river_basin', 'Little Tennessee'),
  (1740, 'watershed', 'Medium'),
  (1740, 'usgs_map', 'Scaly Mountain'),
  (1740, 'fall_type', 'Multilevel falls 103 feet high'),
  (1741, 'county', 'Transylvania'),
  (1741, 'river_basin', 'French Broad'),
  (1741, 'watershed', 'Very small'),
  (1741, 'usgs_map', 'Shining Rock'),
  (1741, 'fall_type', 'Long series of steep slides and cascades; overall height is 88 feet'),
  (1742, 'county', 'Macon'),
  (1742, 'river_basin', 'Savannah'),
  (1742, 'watershed', 'Medium'),
  (1742, 'usgs_map', 'Highlands NC/GA'),
  (1742, 'fall_type', '15-foot cascading falls over sculpted rock'),
  (1743, 'county', 'Jackson'),
  (1743, 'river_basin', 'Little Tennessee'),
  (1743, 'watershed', 'Small/medium'),
  (1743, 'usgs_map', 'Sam Knob'),
  (1743, 'fall_type', 'Two-tier cascading and freefalling falls , 25 feet high'),
  (1745, 'county', 'McDowell'),
  (1745, 'river_basin', 'Catawba'),
  (1745, 'watershed', 'Small'),
  (1745, 'usgs_map', 'Moffitt Hill'),
  (1745, 'fall_type', 'Long series of cascades and short drops measuring more than 250 feet high'),
  (1747, 'county', 'Macon'),
  (1747, 'river_basin', 'Savannah'),
  (1747, 'watershed', 'Small'),
  (1747, 'usgs_map', 'Highlands NC/GA'),
  (1747, 'fall_type', 'Steep cascading falls, 12’ high'),
  (1748, 'county', 'Transylvania'),
  (1748, 'river_basin', 'French Broad'),
  (1748, 'watershed', 'Small'),
  (1748, 'usgs_map', 'Rosman'),
  (1748, 'fall_type', 'Long, steep sliding cascade into large pool approx. 80 feet high'),
  (1749, 'county', 'Transylvania'),
  (1749, 'river_basin', 'French Broad'),
  (1749, 'watershed', 'Very small'),
  (1749, 'usgs_map', 'Shining Rock'),
  (1749, 'fall_type', 'Two levels with an overall height of 64 feet'),
  (1750, 'county', 'Burke'),
  (1750, 'river_basin', 'Catawba'),
  (1750, 'watershed', 'Large'),
  (1750, 'usgs_map', 'Linville Falls'),
  (1750, 'fall_type', 'Powerful cascades and freefalls totaling 100 feet'),
  (1751, 'county', 'Macon'),
  (1751, 'river_basin', 'Savannah'),
  (1751, 'watershed', 'Small/medium'),
  (1751, 'usgs_map', 'Highlands NC/GA'),
  (1751, 'fall_type', 'Very steep falls measuring 53 feet high'),
  (1752, 'county', 'Macon'),
  (1752, 'river_basin', 'Little Tennessee'),
  (1752, 'watershed', 'Medium'),
  (1752, 'usgs_map', 'Highlands NC/GA'),
  (1752, 'fall_type', 'Small concrete dam about 22 feet high'),
  (1753, 'county', 'Henderson'),
  (1753, 'river_basin', 'French Broad'),
  (1753, 'watershed', 'Small'),
  (1753, 'usgs_map', 'Dunsmore Mountain'),
  (1753, 'fall_type', 'Multilevel falls, 145 feet high'),
  (1755, 'county', 'Clay'),
  (1755, 'river_basin', 'Hiwassee'),
  (1755, 'watershed', 'Small'),
  (1755, 'usgs_map', 'Hayesville'),
  (1755, 'fall_type', 'Multilevel Falls with a main lower section of 31 feet'),
  (1756, 'county', 'Ashe'),
  (1756, 'river_basin', 'New'),
  (1756, 'watershed', 'Very small'),
  (1756, 'usgs_map', 'Jefferson'),
  (1756, 'fall_type', 'Multilevel cascade about 35 feet high'),
  (1757, 'county', 'Jackson'),
  (1757, 'river_basin', 'Little Tennessee'),
  (1757, 'watershed', 'Small/medium'),
  (1757, 'usgs_map', 'Sam Knob'),
  (1757, 'fall_type', 'Multiledge falls, 41 feet high'),
  (1758, 'county', 'Transylvania'),
  (1758, 'river_basin', 'French Broad'),
  (1758, 'watershed', 'Small'),
  (1758, 'usgs_map', 'Sam Knob'),
  (1758, 'fall_type', 'Steep sliding falls about 22 feet high'),
  (1759, 'county', 'Jackson'),
  (1759, 'river_basin', 'Little Tennessee'),
  (1759, 'watershed', 'Small/medium'),
  (1759, 'usgs_map', 'Big Ridge'),
  (1759, 'fall_type', '150 feet of sheer awesomeness'),
  (1760, 'county', 'Transylvania'),
  (1760, 'river_basin', 'French Broad'),
  (1760, 'watershed', 'Small'),
  (1760, 'usgs_map', 'Rosman'),
  (1760, 'fall_type', 'Short free fall with cascades over mini-ledges below; total height is about 35 feet'),
  (1762, 'county', 'Clay'),
  (1762, 'river_basin', 'Hiwassee'),
  (1762, 'watershed', 'Small'),
  (1762, 'usgs_map', 'Andrews'),
  (1762, 'fall_type', '27-foot-high waterfall cascading over mossy rocks'),
  (1763, 'county', 'Haywood'),
  (1763, 'river_basin', 'French Broad'),
  (1763, 'watershed', 'Small'),
  (1763, 'usgs_map', 'Sam Knob'),
  (1763, 'fall_type', 'A wild waterfall with a main drop of about 110 feet'),
  (1764, 'county', 'Henderson'),
  (1764, 'river_basin', 'French Broad'),
  (1764, 'watershed', 'Small/medium'),
  (1764, 'usgs_map', 'Dunsmore Mountain'),
  (1764, 'fall_type', 'Nearly vertical 4-foot-high drop'),
  (1765, 'county', 'Swain'),
  (1765, 'river_basin', 'Little Tennessee'),
  (1765, 'watershed', 'Small'),
  (1765, 'usgs_map', 'Smokemont'),
  (1765, 'fall_type', 'Very steep 175+-foot-high waterfall falling over countless tiny ledges 175 feet is the portion visible from base, measured with rangefinder. There is more above this'),
  (1766, 'county', 'Swain'),
  (1766, 'river_basin', 'Little Tennessee'),
  (1766, 'watershed', 'Very small'),
  (1766, 'usgs_map', 'Smokemont'),
  (1766, 'fall_type', 'Steep, cascading falls about 18 feet high'),
  (1767, 'county', 'Jackson'),
  (1767, 'river_basin', 'Little Tennessee'),
  (1767, 'watershed', 'Small/medium'),
  (1767, 'usgs_map', 'Sam Knob'),
  (1767, 'fall_type', 'Near free-fall of 36 feet into large deep pool'),
  (1768, 'county', 'Transylvania'),
  (1768, 'river_basin', 'French Broad'),
  (1768, 'watershed', 'Small'),
  (1768, 'usgs_map', 'Brevard NC/SC'),
  (1768, 'fall_type', 'Multilevel drop totaling about 85 feet'),
  (1769, 'county', 'Transylvania'),
  (1769, 'river_basin', 'French Broad'),
  (1769, 'watershed', 'Very small'),
  (1769, 'usgs_map', 'Sam Knob'),
  (1769, 'fall_type', 'Cascading and free-falling falls nearly 200 feet high'),
  (1771, 'county', 'Transylvania'),
  (1771, 'river_basin', 'French Broad'),
  (1771, 'watershed', 'Medium'),
  (1771, 'usgs_map', 'Shining Rock'),
  (1771, 'fall_type', 'Long, wide, sliding falls, 18 feet high'),
  (1772, 'county', 'Transylvania'),
  (1772, 'river_basin', 'French Broad'),
  (1772, 'watershed', 'Small'),
  (1772, 'usgs_map', 'Table Rock SC/NC'),
  (1772, 'fall_type', '60-foot-high waterfall, falling in two sections'),
  (1773, 'county', 'Transylvania'),
  (1773, 'river_basin', 'French Broad'),
  (1773, 'watershed', 'Small'),
  (1773, 'usgs_map', 'Sam Knob'),
  (1773, 'fall_type', 'Multi-ledge cascade about 30 feet high'),
  (1774, 'county', 'Macon'),
  (1774, 'river_basin', 'Little Tennessee'),
  (1774, 'watershed', 'Very small'),
  (1774, 'usgs_map', 'Wayah Bald'),
  (1774, 'fall_type', 'Steep, cascading falls about 60 feet high'),
  (1775, 'county', 'Polk'),
  (1775, 'river_basin', 'Broad'),
  (1775, 'watershed', 'Very small'),
  (1775, 'usgs_map', 'Cliffield Mountain'),
  (1775, 'fall_type', 'Small, multilevel falls, 26 feet high'),
  (1776, 'county', 'Haywood'),
  (1776, 'river_basin', 'French Broad'),
  (1776, 'watershed', 'Small'),
  (1776, 'usgs_map', 'Shining Rock'),
  (1776, 'fall_type', 'Very steep sliding and freefalling falls over 100 feet high'),
  (1777, 'county', 'Transylvania'),
  (1777, 'river_basin', 'French Broad'),
  (1777, 'watershed', 'Very small'),
  (1777, 'usgs_map', 'Shining Rock'),
  (1777, 'fall_type', '60 feet high with lots of little ledges and freefalls'),
  (1778, 'county', 'Transylvania'),
  (1778, 'river_basin', 'Savannah'),
  (1778, 'watershed', 'Medium/large'),
  (1778, 'usgs_map', 'Reid NC/SC'),
  (1778, 'fall_type', 'Near vertical cascade measuring 146 feet high'),
  (1779, 'county', 'Haywood'),
  (1779, 'river_basin', 'French Broad'),
  (1779, 'watershed', 'Medium'),
  (1779, 'usgs_map', 'Sam Knob'),
  (1779, 'fall_type', 'Long, twisting, cascading, sliding waterfall about 100 feet high'),
  (1780, 'county', 'Harnett'),
  (1780, 'river_basin', 'Cape Fear'),
  (1780, 'watershed', 'Amazon'),
  (1780, 'usgs_map', 'Mamers'),
  (1780, 'fall_type', 'River-wide Class II rapid'),
  (1781, 'county', 'Transylvania'),
  (1781, 'river_basin', 'French Broad'),
  (1781, 'watershed', 'Small'),
  (1781, 'usgs_map', 'Sam Knob'),
  (1781, 'fall_type', '35-foot high, steep slide into large, deep pool'),
  (4911, 'county', 'Transylvania'),
  (4911, 'river_basin', 'French Broad'),
  (4911, 'watershed', 'Very small'),
  (4911, 'usgs_map', 'Shining Rock'),
  (4911, 'fall_type', '75-foot-high, with 45 feet freefalling over bluff'),
  (1786, 'county', 'Transylvania'),
  (1786, 'river_basin', 'French Broad'),
  (1786, 'watershed', 'Medium/large'),
  (1786, 'usgs_map', 'Standing Stone Mtn NC/SC'),
  (1786, 'fall_type', 'River-wide falls, 13 feet high'),
  (1787, 'county', 'Polk'),
  (1787, 'river_basin', 'Broad'),
  (1787, 'watershed', 'Small'),
  (1787, 'usgs_map', 'Saluda NC/SC'),
  (1787, 'fall_type', 'Multi-ledge waterfall about 100 feet high'),
  (4920, 'county', 'Haywood'),
  (4920, 'river_basin', 'French Broad'),
  (4920, 'watershed', 'Small'),
  (4920, 'usgs_map', 'Shining Rock'),
  (4920, 'fall_type', 'Series of small cascades and steep slides; overall drop about 40 feet'),
  (1789, 'county', 'Transylvania'),
  (1789, 'river_basin', 'French Broad'),
  (1789, 'watershed', 'Small'),
  (1789, 'usgs_map', 'Rosman'),
  (1789, 'fall_type', 'Cascading and free-falling falls about 15 feet high'),
  (1790, 'county', 'Transylvania'),
  (1790, 'river_basin', 'French Broad'),
  (1790, 'watershed', 'Medium/large'),
  (1790, 'usgs_map', 'Standing Stone Mtn NC/SC'),
  (1790, 'fall_type', 'Three distinct levels falling about 100 feet'),
  (1791, 'county', 'Jackson'),
  (1791, 'river_basin', 'Little Tennessee'),
  (1791, 'watershed', 'Small'),
  (1791, 'usgs_map', 'Sylva North'),
  (1791, 'fall_type', 'Double cascading waterfall about 50 feet high'),
  (1793, 'county', 'Clay'),
  (1793, 'river_basin', 'Hiwassee'),
  (1793, 'watershed', 'Small'),
  (1793, 'usgs_map', 'Andrews'),
  (1793, 'fall_type', 'Multi-ledge falls nearly 100 feet high'),
  (1794, 'county', 'Transylvania'),
  (1794, 'river_basin', 'French Broad'),
  (1794, 'watershed', 'Small'),
  (1794, 'usgs_map', 'Sam Knob'),
  (1794, 'fall_type', 'Upper drop through a little chasm and lower cascade into a pool; the total drop is about 16 feet'),
  (1795, 'county', 'Transylvania'),
  (1795, 'river_basin', 'Savannah'),
  (1795, 'watershed', 'Medium/large'),
  (1795, 'usgs_map', 'Reid NC/SC'),
  (1795, 'fall_type', 'Cascading, sliding, and freefalling waterfall, 27 feet high'),
  (1797, 'county', 'Avery'),
  (1797, 'river_basin', 'Watauga'),
  (1797, 'watershed', 'Medium/large'),
  (1797, 'usgs_map', 'Elk Park NC/TN'),
  (1797, 'fall_type', 'Near-vertical drop of about 40 feet'),
  (1798, 'county', 'Haywood'),
  (1798, 'river_basin', 'French Broad'),
  (1798, 'watershed', 'Very small'),
  (1798, 'usgs_map', 'Shining Rock'),
  (1798, 'fall_type', 'Steep, cascading slide about 45 feet high with a long series of cascades below'),
  (1799, 'county', 'Macon'),
  (1799, 'river_basin', 'Little Tennessee'),
  (1799, 'watershed', 'Medium'),
  (1799, 'usgs_map', 'Scaly Mountain'),
  (1799, 'fall_type', '18-foot cascading falls'),
  (1801, 'county', 'Transylvania'),
  (1801, 'river_basin', 'French Broad'),
  (1801, 'usgs_map', 'Brevard NC/SC'),
  (1802, 'county', 'Transylvania'),
  (1802, 'river_basin', 'French Broad'),
  (1802, 'watershed', 'Small'),
  (1802, 'usgs_map', 'Shining Rock'),
  (1802, 'fall_type', 'Sliding, cascading, and free-falling falls about 55 feet high'),
  (1803, 'county', 'Clay'),
  (1803, 'river_basin', 'Hiwassee'),
  (1803, 'watershed', 'Small'),
  (1803, 'usgs_map', 'Andrews'),
  (1803, 'fall_type', '35-foot freefalling and cascading falls'),
  (1804, 'county', 'Wilkes'),
  (1804, 'river_basin', 'Yadkin-Pee Dee'),
  (1804, 'watershed', 'Very small'),
  (1804, 'usgs_map', 'Maple Springs'),
  (1804, 'fall_type', 'Long, sliding cascade with a freefalling section near the top'),
  (1805, 'county', 'Transylvania'),
  (1805, 'river_basin', 'French Broad'),
  (1805, 'watershed', 'Small'),
  (1805, 'usgs_map', 'Brevard NC/SC'),
  (1805, 'fall_type', 'Steep cascading and freefalling falls about 31 feet high for the main section'),
  (1806, 'county', 'Transylvania'),
  (1806, 'river_basin', 'French Broad'),
  (1806, 'watershed', 'Small'),
  (1806, 'usgs_map', 'Shining Rock'),
  (1806, 'fall_type', 'Steep, cascading falls about 65 feet high'),
  (1808, 'county', 'Transylvania'),
  (1808, 'river_basin', 'French Broad'),
  (1808, 'watershed', 'Large'),
  (1808, 'usgs_map', 'Rosman'),
  (1808, 'fall_type', '15 foot steep cascade'),
  (1809, 'county', 'Transylvania'),
  (1809, 'river_basin', 'French Broad'),
  (1809, 'watershed', 'Small'),
  (1809, 'usgs_map', 'Shining Rock'),
  (1809, 'fall_type', 'Very steep, sliding cascade, 38 feet high'),
  (1810, 'county', 'Macon'),
  (1810, 'river_basin', 'Savannah'),
  (1810, 'watershed', 'Small'),
  (1810, 'usgs_map', 'Highlands NC/GA'),
  (1810, 'fall_type', 'Sliding and cascading 25’ waterfall over potholed rock'),
  (4918, 'county', 'Haywood'),
  (4918, 'river_basin', 'French Broad'),
  (4918, 'watershed', 'Small'),
  (4918, 'usgs_map', 'Shining Rock'),
  (4918, 'fall_type', 'Sliding, cascading falls about 55 feet high'),
  (1811, 'river_basin', 'French Broad'),
  (1811, 'watershed', 'Small'),
  (1811, 'usgs_map', 'Shining Rock'),
  (1812, 'county', 'Jackson'),
  (1812, 'river_basin', 'Savannah'),
  (1812, 'watershed', 'Small'),
  (1812, 'usgs_map', 'Cashiers NC/SC/GA'),
  (1812, 'fall_type', 'Steep cascading falls about 20 feet high'),
  (1813, 'county', 'Jackson'),
  (1813, 'river_basin', 'Little Tennessee'),
  (1813, 'watershed', 'Small/medium'),
  (1813, 'usgs_map', 'Sam Knob'),
  (1813, 'fall_type', 'Steep, cascading falls, 22 feet high'),
  (1816, 'county', 'Transylvania'),
  (1816, 'river_basin', 'French Broad'),
  (1816, 'watershed', 'Small'),
  (1816, 'usgs_map', 'Sam Knob'),
  (1816, 'fall_type', 'Cascading falls about 25 feet high'),
  (1817, 'county', 'Jackson'),
  (1817, 'river_basin', 'Little Tennessee'),
  (1817, 'watershed', 'Small'),
  (1817, 'usgs_map', 'Sam Knob The topo map mistakenly places Dill Falls at the location for Upper Dill Falls'),
  (1817, 'fall_type', 'A short freefall, then a steep, cascading slide, all totaling nearly 100 feet high'),
  (1818, 'county', 'Transylvania'),
  (1818, 'river_basin', 'French Broad'),
  (1818, 'watershed', 'Medium/large'),
  (1818, 'usgs_map', 'Standing Stone Mtn NC/SC'),
  (1818, 'fall_type', 'Short, overhanging free fall, then long slide ending in short free fall; total drop over 100 feet'),
  (1820, 'county', 'Mitchell'),
  (1820, 'river_basin', 'French Broad'),
  (1820, 'watershed', 'Very small'),
  (1820, 'usgs_map', 'Little Switzerland'),
  (1820, 'fall_type', 'Cascading and freefalling falls about 25 feet high'),
  (1821, 'county', 'Cumberland'),
  (1821, 'river_basin', 'Cape Fear'),
  (1821, 'watershed', 'Very small'),
  (1821, 'usgs_map', 'Vander'),
  (1821, 'fall_type', 'Near-vertical 30-foot drop into pool'),
  (1822, 'county', 'Macon'),
  (1822, 'river_basin', 'Savannah'),
  (1822, 'watershed', 'Small'),
  (1822, 'usgs_map', 'Highlands NC/GA'),
  (1822, 'fall_type', 'Main drop about 30 feet high, with slides above'),
  (1823, 'county', 'Harnett'),
  (1823, 'river_basin', 'Cape Fear'),
  (1823, 'watershed', 'Very small'),
  (1823, 'usgs_map', 'Mamers'),
  (1823, 'fall_type', 'Cascading falls about 5 feet high'),
  (1824, 'county', 'Polk'),
  (1824, 'river_basin', 'Broad'),
  (1824, 'watershed', 'Small'),
  (1824, 'usgs_map', 'Cliffield Mountain'),
  (1824, 'fall_type', 'Multilevel falls nearly 50 feet high'),
  (1825, 'county', 'Transylvania'),
  (1825, 'river_basin', 'Savannah'),
  (1825, 'watershed', 'Small'),
  (1825, 'usgs_map', 'Reid NC/SC'),
  (1825, 'fall_type', 'Cascading 20-foot-high falls'),
  (1826, 'county', 'Transylvania'),
  (1826, 'river_basin', 'French Broad'),
  (1826, 'watershed', 'Small'),
  (1826, 'usgs_map', 'Eastatoe Gap SC/NC'),
  (1826, 'fall_type', 'Steep cascade about 20 feet high'),
  (1827, 'county', 'Transylvania, Jackson'),
  (1827, 'river_basin', 'Savannah'),
  (1827, 'watershed', 'Medium'),
  (1827, 'usgs_map', 'Cashiers NC/SC/GA'),
  (1827, 'fall_type', 'Two-tiered, monster waterfall measuring approximately 335 feet high'),
  (1828, 'county', 'Caldwell, Watauga As best as I can determine, the majority, if not all, of the falls is in Watauga County, but part of the upper section may be in Caldwell County'),
  (1828, 'river_basin', 'Catawba'),
  (1828, 'watershed', 'Small'),
  (1828, 'usgs_map', 'Grandfather Mountain'),
  (1828, 'fall_type', 'Sliding and freefalling falls, dropping 58 feet in two sections'),
  (1829, 'county', 'Haywood'),
  (1829, 'river_basin', 'French Broad'),
  (1829, 'watershed', 'Small'),
  (1829, 'usgs_map', 'Sam Knob'),
  (1829, 'fall_type', 'Long sliding falls a little over 30 feet high'),
  (1830, 'county', 'Transylvania'),
  (1830, 'river_basin', 'French Broad'),
  (1830, 'watershed', 'Very small'),
  (1830, 'usgs_map', 'Shining Rock'),
  (1830, 'fall_type', 'Series of little falls and slides, with an overall height of about 22 feet'),
  (1831, 'county', 'Henderson'),
  (1831, 'river_basin', 'French Broad'),
  (1831, 'watershed', 'Medium'),
  (1831, 'usgs_map', 'Dunsmore Mountain'),
  (1831, 'fall_type', 'Approx. 15 feet high'),
  (1832, 'county', 'Macon'),
  (1832, 'river_basin', 'Little Tennessee'),
  (1832, 'usgs_map', 'Franklin'),
  (3978, 'county', 'Transylvania'),
  (3978, 'river_basin', 'French Broad'),
  (3978, 'watershed', 'Itsy bitsy'),
  (3978, 'usgs_map', 'Shining Rock'),
  (3978, 'fall_type', '100-foot freefalling and sliding falls over massive rock face'),
  (1835, 'county', 'Caldwell'),
  (1835, 'river_basin', 'Catawba'),
  (1835, 'watershed', 'Very small'),
  (1835, 'usgs_map', 'Buffalo Cove'),
  (1835, 'fall_type', 'Cascading and freefalling falls over 100 feet high Portion visible from base measured with rangefinder at 102 feet. According to LiDAR map, there is perhaps another 20 feet above this'),
  (4919, 'county', 'Transylvania'),
  (4919, 'river_basin', 'Savannah'),
  (4919, 'watershed', 'Small/medium'),
  (4919, 'usgs_map', 'Reid NC/SC'),
  (4919, 'fall_type', 'Long, multilevel falls, 301 feet high'),
  (1836, 'county', 'Buncombe'),
  (1836, 'river_basin', 'French Broad'),
  (1836, 'watershed', 'Very small'),
  (1836, 'usgs_map', 'Montreat'),
  (1836, 'fall_type', '21-foot slide on small stream'),
  (1838, 'county', 'Transylvania'),
  (1838, 'river_basin', 'French Broad'),
  (1838, 'watershed', 'Medium/large for North Fork French Broad, Small for Shoal Creek'),
  (1838, 'usgs_map', 'Rosman'),
  (1838, 'fall_type', 'Double 15’ falls, side-by-side Measured with rangefinder')
) AS v(group_id, field, value)
JOIN claim_groups cg ON cg.id = v.group_id
ON CONFLICT DO NOTHING;

-- Tidy them the way every other text claim is tidied.
UPDATE claims c
SET normalized_value = CASE
      WHEN normalize_claim_value(c.value #>> '{}', c.field, cg.source)
           IS DISTINCT FROM (c.value #>> '{}')
       AND normalize_claim_value(c.value #>> '{}', c.field, cg.source) IS NOT NULL
        THEN to_jsonb(normalize_claim_value(c.value #>> '{}', c.field, cg.source))
      ELSE NULL
    END,
    parenthetical = CASE
      WHEN name_parenthetical(c.value #>> '{}') IS NOT NULL
       AND coalesce(normalize_claim_value(c.value #>> '{}', c.field, cg.source), '')
           NOT LIKE '%(' || name_parenthetical(c.value #>> '{}') || ')%'
        THEN name_parenthetical(c.value #>> '{}')
      ELSE NULL
    END
FROM claim_groups cg
WHERE cg.id = c.group_id
  AND c.field IN ('wikidata','wikipedia','gnis_id','waterway_type','tourism',
                  'access','wheelchair','intermittent','website','description',
                  'direction','county','river_basin','watershed','usgs_map',
                  'fall_type','alias');

INSERT INTO schema_migrations (filename) VALUES ('141_adjacent_fields.sql')
ON CONFLICT (filename) DO NOTHING;

COMMIT;
