"""Generate db/migrations/033_hikingwnc_claims.sql from the scraped source.

The claims come from data/hiking_wnc_falls*.json, never from the database --
those columns have been corrected several times and no longer say what
hikingwnc said.
"""
import json, re, sys

def load(path):
    raw = open(path, encoding='utf-8').read()
    raw = re.sub(r',(\s*[\]}])', r'\1', raw)   # the supplement has a trailing comma
    return json.loads(raw)

# The supplement is a second pass over the same site and sometimes reads a
# coordinate differently. Merging it over the main scrape would silently drop
# the disagreement, so it keeps its own source name.
SCRAPES = (('hikingwnc', 'data/hiking_wnc_falls.json'),
           ('hikingwnc-supplement', 'data/hiking_wnc_falls_supplement.json'))

entries = {}
for source, path in SCRAPES:
    for e in load(path):
        if e.get('url'):
            entries.setdefault(e['url'], []).append((source, e))

links = [l.rstrip('\n').split('|', 1) for l in open(sys.argv[1])]

def num(v):
    if v is None:
        return None
    m = re.search(r'\d+', str(v))
    return int(m.group()) if m else None

def text(v):
    if v is None:
        return None
    v = str(v).strip()
    return v or None

def lit(s):
    return "'" + s.replace("'", "''") + "'"

rows, misses, unusable, seen = [], 0, [], set()
for fid, url in links:
    found = entries.get(url)
    if not found:
        misses += 1
        continue
    for source, e in found:
        gps = e.get('GPS') or {}
        claims = []
        if isinstance(gps, str):
            # Some entries carry GPS as prose, sometimes with a malformed number
            # in it ("LONG -82.3.9353"). Kept verbatim: guessing the intended
            # digit would invent a reading, but dropping it loses one.
            unusable.append((fid, e.get('Name'), gps))
            claims.append(('coordinate_raw', json.dumps(gps)))
            gps = {}
        lat, lon = gps.get('Latitude'), gps.get('Longitude')
        if isinstance(lat, (int, float)) and isinstance(lon, (int, float)):
            claims.append(('coordinate', '{"lat": %s, "lon": %s}' % (lat, lon)))
        for field, key in (('beauty_rating', 'Beauty'), ('photo_rating', 'Photo Rating'),
                           ('solitude_rating', 'Solitude'), ('height_ft', 'Height')):
            n = num(e.get(key))
            if n is not None and (field == 'height_ft' or 1 <= n <= 10):
                claims.append((field, str(n)))
        for field, key in (('hike_distance', 'Distance'), ('accessibility', 'Accessibility'),
                           ('name', 'Name')):
            t = text(e.get(key))
            if t:
                claims.append((field, json.dumps(t)))
        for field, value in claims:
            # A few features carry two hikingwnc pages. The same assertion twice
            # is not a second source.
            if (fid, field, value, source) in seen:
                continue
            seen.add((fid, field, value, source))
            rows.append("(%s, '%s', %s, '%s', %s)" % (fid, field, lit(value), source, lit(url)))

out = open('db/migrations/033_hikingwnc_claims.sql', 'w', encoding='utf-8')
out.write("""-- Every assertion hikingwnc makes about a fall we carry, from the scrape.
--
-- Generated by script/backfill_claims/build.py. Read from the JSON in data/,
-- not from the features table: those columns have been corrected repeatedly
-- and would report our conclusions back to us as hikingwnc's.
--
-- Nothing is accepted on insert. The UPDATE at the end accepts a claim only
-- where it still agrees with what the app serves, so whatever is left
-- unaccepted is either a value we overrode or a field we never resolved.

BEGIN;

INSERT INTO claims (feature_id, field, value, source, url) VALUES
""")
out.write(',\n'.join(rows) + ';\n')
for fid, name, gps in unusable:
    out.write('-- %s (feature %s) has no usable point: %s\n' % (name, fid, gps))

out.write("""
-- The two scrapes usually agree, and when they do both match what we serve.
-- Only one of them can be the accepted answer, so the earlier source wins the
-- tie; a genuine disagreement leaves the other claim standing beside it.
WITH matching AS (
    SELECT c.id,
           row_number() OVER (PARTITION BY c.feature_id, c.field ORDER BY c.source, c.id) AS rn
    FROM claims c
    JOIN features f ON f.id = c.feature_id
    LEFT JOIN locations l ON l.id = f.feature_location_id
    WHERE c.source LIKE 'hikingwnc%' AND (
          (c.field = 'coordinate' AND l.latitude IS NOT NULL
           AND round(l.latitude, 5) = round((c.value->>'lat')::numeric, 5)
           AND round(l.longitude, 5) = round((c.value->>'lon')::numeric, 5))
       OR (c.field = 'beauty_rating'   AND f.beauty_rating   = (c.value#>>'{}')::int)
       OR (c.field = 'photo_rating'    AND f.photo_rating    = (c.value#>>'{}')::int)
       OR (c.field = 'solitude_rating' AND f.solitude_rating = (c.value#>>'{}')::int)
       OR (c.field = 'height_ft'       AND f.height_ft       = (c.value#>>'{}')::int)
       OR (c.field = 'accessibility'   AND f.accessibility   = c.value#>>'{}')
       OR (c.field = 'name'            AND f.name            = c.value#>>'{}')))
UPDATE claims SET accepted = true
WHERE id IN (SELECT id FROM matching WHERE rn = 1);

COMMIT;
""")
out.close()
print('claims %d, links with no scrape entry %d' % (len(rows), misses))
