"""Generate db/migrations/040_osm_viewpoints.sql from the viewpoint extract.

Where you stand to see a fall, from OpenStreetMap's tourism=viewpoint nodes.
A viewpoint near a waterfall is not necessarily a viewpoint of it -- the
Parkway is lined with overlooks that face the other way -- so only two cases
are treated as certain: the viewpoint names the fall, or it is unnamed and
within 100 m, which is close enough that it has nowhere else to look.

Data (c) OpenStreetMap contributors, ODbL.
"""
import json, math, re, sys

vps = json.load(open(sys.argv[2], encoding='utf-8'))['elements']

feats = []
for line in open(sys.argv[1], encoding='utf-8'):
    fid, name, lat, lon = line.rstrip('\n').split('|')
    if lat:
        feats.append((int(fid), name, float(lat), float(lon)))

GENERIC = {'falls', 'fall', 'waterfall', 'waterfalls', 'overlook', 'view', 'viewpoint',
           'viewing', 'platform', 'upper', 'lower', 'middle', 'the', 'on', 'of', 'at',
           'creek', 'branch', 'river', 'cascades', 'cascade'}

def words(s):
    return set(re.sub(r'[^a-z ]', ' ', (s or '').lower()).split()) - GENERIC

def km(a, b, c, d):
    return 111.32 * math.hypot(a - c, (b - d) * math.cos(math.radians(a)))

def lit(s):
    return "'" + s.replace("'", "''") + "'"

groups, rows, certain_count = [], [], 0
for v in vps:
    d, f = min(((km(v['lat'], v['lon'], x[2], x[3]), x) for x in feats), key=lambda x: x[0])
    if d > 0.5:
        continue
    fid, fname = f[0], f[1]
    vname = (v.get('tags') or {}).get('name')
    shared = words(vname) & words(fname)
    if shared:
        certain, why = 'true', 'Named for the fall it looks at.'
    elif not vname and d < 0.1:
        certain, why = 'true', 'Unnamed and %d m away, with nothing else to look at.' % round(d * 1000)
    else:
        certain, why = 'false', ('%d m from the fall, but OpenStreetMap calls it %s, '
                                 'which names something else.' % (round(d * 1000), vname))
    if certain == 'true':
        certain_count += 1
    ref = 'openstreetmap|%d|viewpoint/%d' % (fid, v['id'])
    groups.append("(%s, %d, 'openstreetmap', 'https://www.openstreetmap.org/node/%d', %s, %s)"
                  % (lit(ref), fid, v['id'], certain, lit(why)))
    rows.append("(%s, 'view_coordinate', '{\"lat\": %s, \"lon\": %s}', %s)"
                % (lit(ref), v['lat'], v['lon'],
                   lit('%d m from the fall.' % round(d * 1000))))

out = open('db/migrations/040_osm_viewpoints.sql', 'w', encoding='utf-8')
out.write("""-- Where you stand to see the big ones, from OpenStreetMap.
--
-- Generated by script/backfill_claims/viewpoints.py. Whitewater Falls has a
-- viewing platform 307 m from the water and an overlook at 340 m, which is the
-- whole point of this field: at the base of a 411 foot fall you see spray and
-- rock.
--
-- Data (c) OpenStreetMap contributors, made available under the ODbL.

BEGIN;

INSERT INTO claim_groups (ref, feature_id, source, url, identity_certain, note) VALUES
""")
out.write(',\n'.join(groups) + ';\n\n')
out.write("""INSERT INTO claims (group_id, feature_id, field, value, note)
SELECT g.id, g.feature_id, v.field, v.value::jsonb, v.note::text
FROM (VALUES
""")
out.write(',\n'.join(rows) + """
) AS v(ref, field, value, note)
JOIN claim_groups g ON g.ref = v.ref;

-- Accept the nearest viewpoint we are sure about, one per fall.
CREATE TEMP TABLE chosen ON COMMIT DROP AS
SELECT DISTINCT ON (c.feature_id)
       c.feature_id,
       (c.value->>'lat')::numeric AS lat,
       (c.value->>'lon')::numeric AS lon
FROM claims c
JOIN claim_groups cg ON cg.id = c.group_id
JOIN features f ON f.id = c.feature_id
JOIN locations fl ON fl.id = f.feature_location_id
WHERE c.field = 'view_coordinate' AND cg.identity_certain
ORDER BY c.feature_id,
         sqrt(power(fl.latitude - (c.value->>'lat')::numeric, 2) +
              power((fl.longitude - (c.value->>'lon')::numeric) *
                    cos(radians(fl.latitude)), 2));

INSERT INTO locations (latitude, longitude) SELECT lat, lon FROM chosen;

UPDATE features f SET view_location_id = (
    SELECT l.id FROM locations l
    WHERE l.latitude = c.lat AND l.longitude = c.lon
    ORDER BY l.id DESC LIMIT 1)
FROM chosen c WHERE f.id = c.feature_id;

UPDATE claims c SET accepted = true
FROM features f, locations l
WHERE c.feature_id = f.id AND f.view_location_id = l.id
  AND c.field = 'view_coordinate'
  AND (c.value->>'lat')::numeric = l.latitude
  AND (c.value->>'lon')::numeric = l.longitude;

COMMIT;
""")
out.close()
print('viewpoint claims %d, of which certain %d' % (len(rows), certain_count))
