"""Generate db/migrations/036_wc100_kml_claims.sql from data/dwhike.kml.

The KML is the coordinate source for a dozen features that carry a point
hikingwnc never published. It covers the WC100 list, but the readings are
dwhike's own and are recorded under that name. Matched to features by name, and
only where the name picks out exactly one.
"""
import re, sys, json, math

kml = open('data/dwhike.kml', encoding='utf-8').read()
marks = []
for block in re.findall(r'<Placemark>(.*?)</Placemark>', kml, re.S):
    name = re.search(r'<name>(.*?)</name>', block, re.S)
    coord = re.search(r'<coordinates>\s*([-\d.]+),([-\d.]+)', block, re.S)
    if name and coord:
        marks.append((name.group(1).strip(), float(coord.group(2)), float(coord.group(1))))

feats = []
for line in open(sys.argv[1], encoding='utf-8'):
    fid, name, lat, lon = line.rstrip('\n').split('|')
    feats.append((int(fid), name, float(lat) if lat else None, float(lon) if lon else None))

def norm(s):
    # The parenthetical is the disambiguator -- Upper Falls (Yellowstone Prong)
    # and Upper Falls (Snowbird Creek) are 102 km apart. Stripping it matched
    # one to the other.
    s = re.sub(r'<!\[CDATA\[(.*?)\]\]>', r'\1', s)
    s = s.lower().replace('&', 'and')
    s = re.sub(r'[^a-z0-9 ]', ' ', s)
    return ' '.join(s.split())

by_norm = {}
for fid, name, lat, lon in feats:
    by_norm.setdefault(norm(name), []).append((fid, name, lat, lon))

def lit(s):
    return "'" + s.replace("'", "''") + "'"

def km(a, b, c, d):
    return 111.32 * math.hypot(a - c, (b - d) * math.cos(math.radians(a)))

groups, rows, unmatched, ambiguous, far = [], [], [], [], []
for name, lat, lon in marks:
    n = norm(name)
    hits = by_norm.get(n)
    if not hits:
        # "Turtleback Falls" against "Turtleback Falls- Horsepasture River"
        hits = [f for k, v in by_norm.items() if k.startswith(n + ' ') for f in v]
    if not hits:
        unmatched.append(name)
        continue
    if len(hits) > 1:
        ambiguous.append((name, [h[1] for h in hits]))
        continue
    fid, fname, flat, flon = hits[0]
    note, certain = 'NULL', 'true'
    if flat is not None:
        d = km(lat, lon, flat, flon)
        if d > 2:
            # Same name, possibly a different mountain -- there are two Long
            # Creek Falls and one of them is in Georgia. Recorded anyway, since
            # an uncertain identity we can see beats one we cannot.
            far.append((name, fname, round(d, 1)))
            note = ("'Matched to this feature by name alone. The placemark is "
                    "%s km from where we have it, so it may be a different fall "
                    "of the same name.'" % round(d, 1))
            certain = 'false'
    ref = 'dwhike|%d|%s' % (fid, name)
    groups.append("(%s, %d, 'dwhike', %s, %s)" % (lit(ref), fid, certain, note))
    rows.append("(%s, 'coordinate', '{\"lat\": %s, \"lon\": %s}')" % (lit(ref), lat, lon))
    if name:
        rows.append("(%s, 'name', %s)" % (lit(ref), lit(json.dumps(name))))

out = open('db/migrations/036_wc100_kml_claims.sql', 'w', encoding='utf-8')
out.write("""-- What dwhike.kml says, recorded as dwhike's own readings.
--
-- Generated by script/import/claims/kml.py. A dozen falls carry a point
-- hikingwnc never published, and this is where it came from. The file covers
-- the WC100 list, but the coordinates in it are dwhike's, so that is the name
-- they are filed under. Matched by name, and only where the name picks out
-- exactly one feature.

BEGIN;

INSERT INTO claim_groups (ref, feature_id, source, identity_certain, note) VALUES
""")
out.write(',\n'.join(groups) + ';\n\n')
out.write("""INSERT INTO claims (group_id, feature_id, field, value)
SELECT g.id, g.feature_id, v.field, v.value::jsonb
FROM (VALUES
""")
out.write(',\n'.join(rows) + """
) AS v(ref, field, value)
JOIN claim_groups g ON g.ref = v.ref;
""")
for name in unmatched:
    out.write('-- no feature matched the placemark %s\n' % json.dumps(name))
for name, names in ambiguous:
    out.write('-- placemark %s matched %d features, left alone\n' % (json.dumps(name), len(names)))
for name, fname, d in far:
    out.write('-- placemark %s is %s km from our %s; claimed, but flagged in its note\n'
              % (json.dumps(name), d, json.dumps(fname)))
out.write("""
UPDATE claims c SET accepted = true
FROM claim_groups cg, features f JOIN locations l ON l.id = f.feature_location_id
WHERE c.group_id = cg.id AND c.feature_id = f.id
  AND cg.source = 'dwhike' AND c.field = 'coordinate'
  AND round(l.latitude, 5) = round((c.value->>'lat')::numeric, 5)
  AND round(l.longitude, 5) = round((c.value->>'lon')::numeric, 5)
  AND NOT EXISTS (SELECT 1 FROM claims a
                  WHERE a.feature_id = c.feature_id AND a.field = c.field AND a.accepted);

COMMIT;
""")
out.close()
print('placemarks %d, claims %d, unmatched %d, ambiguous %d, far apart %d'
      % (len(marks), len(rows), len(unmatched), len(ambiguous), len(far)))
