"""Generate db/migrations/037_osm_claims.sql from the Overpass extract.

OpenStreetMap is a third reading of most of the map, taken by people in the
field rather than from a guidebook. Attached to a feature by name and distance;
a match on distance alone is recorded with a note saying so, because two falls
on the same creek are often a few hundred metres apart.

Data (c) OpenStreetMap contributors, ODbL.
"""
import json, math, re, sys, collections

nodes = {}
for path in sys.argv[2:]:
    for e in json.load(open(path, encoding='utf-8'))['elements']:
        nodes[e['id']] = e

falls = [e for e in nodes.values() if (e.get('tags') or {}).get('waterway') == 'waterfall']

feats = []
for line in open(sys.argv[1], encoding='utf-8'):
    fid, name, lat, lon = line.rstrip('\n').split('|')
    if lat:
        feats.append((int(fid), name, float(lat), float(lon)))

def norm(s):
    s = (s or '').lower().replace('&', 'and')
    s = re.sub(r'[^a-z0-9 ]', ' ', s)
    return ' '.join(s.split())

def km(a, b, c, d):
    return 111.32 * math.hypot(a - c, (b - d) * math.cos(math.radians(a)))

def lit(s):
    return "'" + s.replace("'", "''") + "'"

def names_agree(a, b):
    a, b = norm(a), norm(b)
    if not a or not b:
        return False
    return a == b or a.startswith(b + ' ') or b.startswith(a + ' ')

groups, rows, taken, by_name, by_distance = [], [], set(), 0, 0
for fid, name, lat, lon in feats:
    scored = sorted(((km(lat, lon, e['lat'], e['lon']), e) for e in falls), key=lambda x: x[0])
    named = [(d, e) for d, e in scored if d < 1.0 and names_agree(name, e['tags'].get('name'))]
    if named:
        d, e = named[0]
        note, certain = 'NULL', 'true'
        by_name += 1
    else:
        d, e = scored[0]
        if d > 0.075:
            continue
        note = lit('Matched on distance alone, %d m, with no agreeing name. '
                   'OpenStreetMap calls this node %s.'
                   % (round(d * 1000), e['tags'].get('name') or 'nothing'))
        certain = 'false'
        by_distance += 1
    taken.add(e['id'])
    t = e['tags']
    ref = 'openstreetmap|%d|node/%d' % (fid, e['id'])
    groups.append("(%s, %d, 'openstreetmap', 'https://www.openstreetmap.org/node/%d', %s, %s)"
                  % (lit(ref), fid, e['id'], certain, note))
    rows.append("(%s, 'coordinate', '{\"lat\": %s, \"lon\": %s}', NULL)"
                % (lit(ref), e['lat'], e['lon']))
    for key in ('name', 'official_name', 'alt_name', 'alt_name:1'):
        v = (t.get(key) or '').strip()
        if v and not (key == 'name' and names_agree(name, v) and norm(v) == norm(name)):
            field = 'name' if key == 'name' else 'alias'
            rows.append("(%s, '%s', %s, NULL)" % (lit(ref), field, lit(json.dumps(v))))
    h = re.search(r'\d+(\.\d+)?', str(t.get('height') or ''))
    if h:
        ft = float(h.group())
        if 'ft' not in str(t.get('height')):
            ft = ft * 3.28084       # OSM heights are metres unless marked
        rows.append("(%s, 'height_ft', '%d', %s)"
                    % (lit(ref), round(ft),
                       lit('OpenStreetMap tag height=%s.' % t['height'])))

unclaimed = [e for e in falls if e['id'] not in taken]

out = open('db/migrations/037_osm_claims.sql', 'w', encoding='utf-8')
out.write("""-- What OpenStreetMap says about the falls we already carry.
--
-- Generated by script/import/claims/osm.py from the Overpass extract in
-- data/. Nothing new is added to features here; this is a third reading of
-- points we already have, plus the names and heights that come with it.
--
-- Data (c) OpenStreetMap contributors, made available under the ODbL. Any
-- value promoted out of these claims carries that attribution with it.

BEGIN;

INSERT INTO claim_groups (ref, feature_id, source, url, identity_certain, note) VALUES
""")
out.write(',\n'.join(groups) + ';\n\n')
out.write("""INSERT INTO claims (group_id, feature_id, field, value, note)
SELECT g.id, g.feature_id, v.field, v.value::jsonb, v.note::text
FROM (VALUES
""")
out.write(',\n'.join(rows) + """
) AS v(ref, field, value, note)
JOIN claim_groups g ON g.ref = v.ref;
""")
out.write("""
-- Accepted only where it agrees with what we already serve, to five decimals.
WITH matching AS (
    SELECT c.id, row_number() OVER (PARTITION BY c.feature_id, c.field ORDER BY c.id) AS rn
    FROM claims c
    JOIN claim_groups cg ON cg.id = c.group_id
    JOIN features f ON f.id = c.feature_id
    JOIN locations l ON l.id = f.feature_location_id
    WHERE cg.source = 'openstreetmap' AND c.field = 'coordinate'
      AND round(l.latitude, 5) = round((c.value->>'lat')::numeric, 5)
      AND round(l.longitude, 5) = round((c.value->>'lon')::numeric, 5)
      AND NOT EXISTS (SELECT 1 FROM claims a WHERE a.feature_id = c.feature_id
                      AND a.field = c.field AND a.accepted))
UPDATE claims SET accepted = true WHERE id IN (SELECT id FROM matching WHERE rn = 1);

COMMIT;
""")
out.write('\n-- %d OpenStreetMap waterfalls in the extract match no feature we carry.\n'
          % len(unclaimed))
out.close()
print('claims %d | matched by name %d, by distance only %d | OSM falls unclaimed %d'
      % (len(rows), by_name, by_distance, len(unclaimed)))
