#!/usr/bin/env python3
"""Turn data/nldi/drainage.jsonl into a migration that populates features.drainage_area_sqmi.

Drainage area is a derived measurement, not a source reading that needs
provenance or arbitration. It lives on features like height_ft or beauty_rating
-- one value per waterfall, set directly, read directly by the API.

    python3 script/import/nldi/build.py > db/migrations/064_nldi_drainage_area.sql
"""

import json
import sys
from datetime import date

INFILE = "data/nldi/drainage.jsonl"


def main():
    rows = []
    errors = 0
    with open(INFILE) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            if row.get("drainage_area_sqmi") is not None:
                rows.append(row)
            else:
                errors += 1

    print(f"""\
-- NLDI drainage area, generated by script/import/nldi/build.py
-- from data/nldi/drainage.jsonl on {date.today()}.
-- Do not hand-edit: re-generate from the JSONL.
--
-- drainage_area_sqmi is the upstream watershed area at each waterfall's
-- accepted coordinate, from USGS NLDI basin delineation. Unit: square miles.
-- {len(rows)} of {len(rows)+errors} waterfalls returned a basin polygon.
--
-- Source: USGS Network-Linked Data Index (api.water.usgs.gov/nldi)

BEGIN;

ALTER TABLE features ADD COLUMN IF NOT EXISTS drainage_area_sqmi numeric;

COMMENT ON COLUMN features.drainage_area_sqmi IS
    'Upstream watershed area in square miles at the waterfall coordinate, '
    'from USGS NLDI basin delineation (api.water.usgs.gov/nldi). '
    'Larger values mean more water on average.';
""")

    for row in rows:
        fid = row["feature_id"]
        area = row["drainage_area_sqmi"]
        print(f"UPDATE features SET drainage_area_sqmi = {area} WHERE id = {fid};")

    print(f"""
INSERT INTO schema_migrations (filename) VALUES ('064_nldi_drainage_area.sql');

COMMIT;
-- {len(rows)} rows set, {errors} waterfalls had no basin polygon returned
""")


if __name__ == "__main__":
    main()
