"""Generate db/migrations/050_ncwaterfalls_links.sql.

958 of 960 links point at hikingwnc. Kevin Adams covers the same waterfalls and
publishes a page per fall, so this adds a second source for the ones we can
match with confidence.

Matching by name alone is not confidence. Adams covers the whole state and we
carry the western end of it, so the names collide: his Jones Falls is 305 km
from ours, his Cedar Falls 280 km, his Silver Run Falls 396 km. Every candidate
is therefore checked against the coordinate his own page publishes, using the
pages already cached under data/spider-cache -- no refetching.

Candidates come from two places that were built independently:
  - a name-matched list at data/ncwaterfalls-matches.tsv
  - the ncwaterfalls claim groups already in the database

Agreeing is not evidence when both matched on the name, which is why the
coordinate is the arbiter rather than the tiebreak.
"""
import html, math, os, re, subprocess, sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'spider'))
import cache

CACHE = 'data/spider-cache/ncwaterfalls.jsonl.gz'
TSV = 'data/ncwaterfalls-matches.tsv'
NEAR_KM = 2.0       # same waterfall, allowing for trailhead-versus-water
FAR_KM = 20.0       # a different waterfall that happens to share a name

def psql(sql):
    out = subprocess.run(['psql', '-qAt', '-F|', '-d', 'wc_journey_db', '-c', sql],
                         capture_output=True, text=True)
    return [l.split('|') for l in out.stdout.strip().split('\n') if l]

def km(a, b, c, d):
    return 111.32 * math.hypot(a - c, (b - d) * math.cos(math.radians(a)))

def lit(s):
    return "'" + s.replace("'", "''") + "'"

published = {}
for rec in cache.latest(CACHE):
    text = re.sub(r'\s+', ' ', html.unescape(re.sub(r'<[^>]+>', ' ', rec['html'])))
    m = re.search(r'Waterfall GPS:\s*(-?\d+\.\d+)\s*,\s*(-?\d+\.\d+)', text)
    if m:
        published[rec['url'].rstrip('/')] = (float(m.group(1)), float(m.group(2)))

ours = {int(r[0]): (r[1], float(r[2]), float(r[3]))
        for r in psql("""SELECT f.id, f.name, l.latitude, l.longitude FROM features f
                         JOIN locations l ON l.id = f.feature_location_id""")}
names = {int(r[0]): r[1] for r in psql("SELECT id, name FROM features")}

candidates = {}
if os.path.exists(TSV):
    for line in open(TSV, encoding='utf-8'):
        fid, _, url = line.rstrip('\n').split('\t')
        candidates[int(fid)] = url.rstrip('/')
for r in psql("""SELECT cg.feature_id, cg.url FROM claim_groups cg
                 WHERE cg.source = 'ncwaterfalls' AND cg.url IS NOT NULL
                   AND cg.identity_certain"""):
    candidates.setdefault(int(r[0]), r[1].rstrip('/'))

accepted, rejected, unverifiable = [], [], []
for fid, url in sorted(candidates.items()):
    name = names.get(fid, '?')
    page = published.get(url)
    if fid not in ours or not page:
        # No coordinate on one side or the other. These are the features we know
        # least about, which is exactly where a second source is worth most, so
        # they go in named rather than dropped silently.
        unverifiable.append((fid, name, url))
        accepted.append((fid, name, url, None))
        continue
    d = km(ours[fid][1], ours[fid][2], *page)
    if d > FAR_KM:
        rejected.append((fid, name, url, round(d, 1)))
    else:
        accepted.append((fid, name, url, round(d, 1)))

out = open('db/migrations/050_ncwaterfalls_links.sql', 'w', encoding='utf-8')
out.write("""-- A second source for %d waterfalls.
--
-- Generated by script/import/links/ncwaterfalls.py. Every link is checked
-- against the coordinate Kevin Adams publishes on that page: he covers the
-- whole state and we carry the western end, so the names collide and a name
-- match on its own is a coin flip for a dozen of them.
--
-- Re-runnable. The unique constraint on (feature_id, url) makes a second
-- application a no-op.

BEGIN;

INSERT INTO links (feature_id, url, rel, comments) VALUES
""" % len(accepted))
rows = []
for fid, name, url, d in accepted:
    if d is None:
        note = 'Matched by name; neither side publishes a coordinate to check it against.'
    elif d <= NEAR_KM:
        note = 'Matched by name and confirmed within %s km of our coordinate.' % d
    else:
        note = ('Matched by name; his coordinate is %s km from ours, which is close '
                'enough to be the same fall seen from the trailhead and far enough '
                'to be worth reading before trusting.' % d)
    rows.append("(%d, %s, 'ncwaterfalls', %s)" % (fid, lit(url), lit(note)))
out.write(',\n'.join(rows) + "\nON CONFLICT (feature_id, url) DO NOTHING;\n")

out.write("\n-- Rejected, same name and a different waterfall:\n")
for fid, name, url, d in sorted(rejected, key=lambda x: -x[3]):
    out.write('--   %-34s %-40s %8s km\n' % (name[:34], url.rsplit('/', 1)[-1][:40], d))
out.write("\nCOMMIT;\n")
out.close()
print('accepted %d (of which %d unverifiable), rejected %d'
      % (len(accepted), len(unverifiable), len(rejected)))
